import type { PlaySheetPlay, PlaySheetWithPlays } from "@/lib/playSheetTypes";
import { DEMO_PLAY_SHEET_ID } from "@/lib/playSheetTypes";
import { SCHEME_IDS } from "@/lib/staticData";

const DEMO_PLAYS: Omit<PlaySheetPlay, "play_sheet_id">[] = [
  {
    id: "00000003-0000-4000-8000-000000000101",
    situation: "1st & 10",
    situation_order: 0,
    play_order: 0,
    formation: "Gun Empty Base Flex",
    play_name: "Y SHALLOW CROSS",
    coaching_note:
      "Shallow cross attacks the hook/curl zone — LBs can't drop fast enough",
    counter_formation: null,
    counter_play: "STICK",
    custom_note: null,
    is_featured: true,
    is_used: false,
    play_type: "Pass",
  },
  {
    id: "00000003-0000-4000-8000-000000000102",
    situation: "2nd & Medium",
    situation_order: 1,
    play_order: 0,
    formation: "Pistol Wing Slot",
    play_name: "READ OPTION WK",
    coaching_note:
      "RPO reads the overhang — if he crashes, QB pulls and throws bubble",
    counter_formation: null,
    counter_play: "Y STICK",
    custom_note: null,
    is_featured: false,
    is_used: false,
    play_type: "RPO",
  },
  {
    id: "00000003-0000-4000-8000-000000000103",
    situation: "2nd & Long",
    situation_order: 2,
    play_order: 0,
    formation: "Pistol Wing Slot",
    play_name: "PA DEEP OUT",
    coaching_note:
      "Play action holds the safeties — deep out to the boundary beats Cover 3",
    counter_formation: null,
    counter_play: "PA BOOT LT",
    custom_note: null,
    is_featured: false,
    is_used: false,
    play_type: "Play Action",
  },
  {
    id: "00000003-0000-4000-8000-000000000104",
    situation: "3rd & Short",
    situation_order: 3,
    play_order: 0,
    formation: "Pistol U Off",
    play_name: "RPO PEEK SLANT FLAT",
    coaching_note:
      "Slant-flat combo — one of the two is always open vs single-high",
    counter_formation: null,
    counter_play: "READ OPTION",
    custom_note: null,
    is_featured: false,
    is_used: false,
    play_type: "RPO",
  },
  {
    id: "00000003-0000-4000-8000-000000000105",
    situation: "3rd & Medium",
    situation_order: 4,
    play_order: 0,
    formation: "Gun Empty Base Flex",
    play_name: "LEVELS SWITCH",
    coaching_note:
      "High-low concept attacks zone coverage — the switch creates natural pick",
    counter_formation: null,
    counter_play: "MIDDLE HI LO",
    custom_note: null,
    is_featured: false,
    is_used: false,
    play_type: "Pass",
  },
  {
    id: "00000003-0000-4000-8000-000000000106",
    situation: "3rd & Long",
    situation_order: 5,
    play_order: 0,
    formation: "Gun Empty Trips Y Off",
    play_name: "LEVELS SEAM",
    coaching_note:
      "Three levels vs Cover 3 — the seam splits the hook and the deep third",
    counter_formation: null,
    counter_play: "RPO ALERT BUBBLE QB POWER",
    custom_note: null,
    is_featured: true,
    is_used: false,
    play_type: "Pass",
  },
  {
    id: "00000003-0000-4000-8000-000000000107",
    situation: "Red Zone",
    situation_order: 6,
    play_order: 0,
    formation: "Pistol Wing Slot",
    play_name: "PA DEEP OUT",
    coaching_note:
      "Play action isolates the boundary WR — back shoulder vs press man",
    counter_formation: null,
    counter_play: "HITCH CORNERS",
    custom_note: null,
    is_featured: false,
    is_used: false,
    play_type: "Play Action",
  },
  {
    id: "00000003-0000-4000-8000-000000000108",
    situation: "Goal Line",
    situation_order: 7,
    play_order: 0,
    formation: "Pistol U Off",
    play_name: "MTN HB POWER",
    coaching_note:
      "Power blocking at the goal line — numbers advantage vs 5-DB look",
    counter_formation: null,
    counter_play: "INSIDE ZONE SPLIT",
    custom_note: null,
    is_featured: false,
    is_used: false,
    play_type: "Run",
  },
  {
    id: "00000003-0000-4000-8000-000000000109",
    situation: "2-Minute Drill",
    situation_order: 8,
    play_order: 0,
    formation: "Gun Empty Base Flex",
    play_name: "STICK",
    coaching_note:
      "Fast, safe throw to the flat — QB gets the ball out in under 2 seconds",
    counter_formation: null,
    counter_play: "WR SCREEN",
    custom_note: null,
    is_featured: false,
    is_used: false,
    play_type: "Pass",
  },
  {
    id: "00000003-0000-4000-8000-000000000110",
    situation: "Backed Up",
    situation_order: 9,
    play_order: 0,
    formation: "Pistol U Off",
    play_name: "HB STRETCH",
    coaching_note:
      "Get outside the box — stretch the defense horizontally before throwing",
    counter_formation: null,
    counter_play: "PA BOOT Y DRAG",
    custom_note: null,
    is_featured: false,
    is_used: false,
    play_type: "Run",
  },
];

export function getStaticDemoPlaySheet(): PlaySheetWithPlays {
  const sheetId = DEMO_PLAY_SHEET_ID;
  return {
    id: sheetId,
    name: "Arbuckle vs 4-2-5 — Demo",
    offensive_scheme_id: SCHEME_IDS.arbuckle,
    defensive_scheme: "4-2-5",
    opponent_team: null,
    plays: DEMO_PLAYS.map((p) => ({
      ...p,
      play_sheet_id: sheetId,
    })),
  };
}
