import { TeamPlaybookSeed } from '../types';

export const CFB27_4_2_5_ZONE_SEED: TeamPlaybookSeed = {
  team: "4-2-5 Zone",
  scheme: "4-2-5 Zone",
  sideOfBall: 'defense',
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/4-2-5-zone-def/",
    verified: "2026-07-01",
  },
  formations: [
    {
      formation: "5-2 Normal",
      formationType: "5-2",
      plays: [
        { playName: "COVER 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DT LOOP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FIRE ZONE 2", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FLASH BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PINCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TRIO SKY ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Nickel 2-4 Single Mug",
      formationType: "Nickel",
      plays: [
        { playName: "1 LB DOG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COV 2 INVERT HARD FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 INVERT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 CLOUD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 9", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DT MIKE LOOP 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Nickel Double Mug",
      formationType: "Nickel",
      plays: [
        { playName: "2 INVERT HARD FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BLITZ LOOP 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 INVERT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MID BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL 2 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Nickel Load Dbl Mug",
      formationType: "Nickel",
      plays: [
        { playName: "1 DT LB LOOP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BLITZ LOOP 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CB BENCH SIM 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 LB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL SIM 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SIDE BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Nickel Load Mug",
      formationType: "Nickel",
      plays: [
        { playName: "COVER 1 LB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 CLOUD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HOT BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB DE TWIST 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL SIM 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Nickel Over",
      formationType: "Nickel",
      plays: [
        { playName: "COV 2 MAN CONTAIN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 CONTAIN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 HOLE PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 DROP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 HARD FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 INVERT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 BUZZ STRONG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 CLOUD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 HARD FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 DROP FIELD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL BLITZ 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OVER STORM BRAVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ROLL COVER 2 INVERT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ROLL COVER 3 CLOUD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "4-2-5 3 High",
      formationType: "4-2-5",
      plays: [
        { playName: "3 DOUBLE CLOUD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "3 DOUBLE SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 LURK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EDGE BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HOT BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "4-2-5 Even",
      formationType: "4-2-5",
      plays: [
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 CONTAIN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SS BLITZ 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SS LB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WS BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WS BLITZ 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WS BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "4-2-5 Over G",
      formationType: "4-2-5",
      plays: [
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 CONTAIN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PINCH BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SS BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SS LB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WS BLITZ 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WS BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "4-2-5 Under",
      formationType: "4-2-5",
      plays: [
        { playName: "2 INVERT HARD FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 INVERT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 HARD FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FREE FIRE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAMMER 0 BLAST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WILL GO FIRE 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Dime 3-2",
      formationType: "Dime",
      plays: [
        { playName: "COVER 1 CONTAIN SPY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 HARD FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 BUZZ MATCH WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 CLOUD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 HARD FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 LOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 DROP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL SAFETY GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EDGE BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HOT BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2 DROP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZERO BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Dime Normal",
      formationType: "Dime",
      plays: [
        { playName: "3 DOUBLE BUZZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COV 3BUZZ SHOW 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 CONTAIN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 BUZZ MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL SAFETY BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIME BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OVERLOAD 3 SHOW 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SS BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Prevent 3 Deep",
      formationType: "Prevent",
      plays: [
        { playName: "COVER 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MAN 3 DEEP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PREVENT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Goal Line 5-3",
      formationType: "Goal Line",
      plays: [
        { playName: "GAPS AB", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GAPS ALL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GAPS ALL LB", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GAPS B", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GL MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MLB GAP A", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Goal Line 6-2",
      formationType: "Goal Line",
      plays: [
        { playName: "60 BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "60 HALF OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "60 OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "60 OUT JACKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "60 PINCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
