import { TeamPlaybookSeed } from '../types';

export const CFB27_KANSAS_STATE_SEED: TeamPlaybookSeed = {
  team: "Kansas State",
  scheme: "Multiple O",
  sideOfBall: 'offense',
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/kansas-state-off/",
    verified: "2026-07-01",
  },
  formations: [
    {
      formation: "I Form Slot",
      formationType: "I Form",
      plays: [
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DUO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB LEAD DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET LEAD ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA X DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y THROWBACK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SAIL Y SHAKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WEAK FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y COP SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "I Form Wing",
      formationType: "I Form",
      plays: [
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB FAKE HB FLIP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER G", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ISO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN POWER WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT FLOW", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA X BURST CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST SHOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "I Form Wing Over",
      formationType: "I Form",
      plays: [
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB LEAD", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER G", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT FLOW", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA MTN POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "X SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Strong I Twins Over",
      formationType: "Strong I",
      plays: [
        { playName: "HB BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ROLLOUT SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Strong",
      formationType: "Pistol",
      plays: [
        { playName: "HB BLAST ALERT X SMOKE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH ALERT X LOOKIE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT LT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "X OFF JET DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "X OFF JET HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "X OFF JET HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "X OFF JET PA COUNTER F FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "X OFF JET PA POWER WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "X OFF JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol U Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "DBL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CORNER DIG", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FL CLOWN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Weak Slot Over",
      formationType: "Pistol",
      plays: [
        { playName: "COUNTER STR", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "F LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "ZONE ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Wing Slot",
      formationType: "Pistol",
      plays: [
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HITCH CORNERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LEAD OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT LT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CTR WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POSTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Wing Slot Over",
      formationType: "Pistol",
      plays: [
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA STRETCH SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ROLLOUT FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO GLANCE POST BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPLIT ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ZONE ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Ace",
      formationType: "Gun",
      plays: [
        { playName: "DBL MTN HB BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DBL MTN HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DBL MTN HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FLOOD POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MIDLINE READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO ALERT Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN RPO READ SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "PA INVERTED VEER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Bunch Open Offset",
      formationType: "Gun",
      plays: [
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPRINT Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Bunch Str Nasty",
      formationType: "Gun",
      plays: [
        { playName: "AROUND FAKE COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CHEAT INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CRACK TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLANKER DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH FLAT SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DOUBLE PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA BUNCH SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CHEAT DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CHEAT VERTICALS Y SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "Z MESH QUICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Deuce",
      formationType: "Gun",
      plays: [
        { playName: "EXIT PA WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "EXIT RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "EXIT RPO SNAG", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "FK TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "ZONE TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Deuce Twins Over",
      formationType: "Gun",
      plays: [
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RELOAD LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RELOAD RPO READ U SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RELOAD Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO READ U SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Doubles",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER BASH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET PASS POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FOUR VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INVERTED VEER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO READ SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "ORBIT QB WRAP SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ORBIT RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "ORBIT Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA QB CHOICE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB WRAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPOT SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X UNDER SEAMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Doubles Y Off",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ANGLE CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FADE STOP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET PASS POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET HB SPLIT ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET RPO GLANCE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "JET TE MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "POST X CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHARK HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERT COMEBACKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Empty Base Flex",
      formationType: "Gun",
      plays: [
        { playName: "LEVELS SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MIDDLE HI LO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Empty Trips Y Off",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURLS SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HITCHES X DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INS SLOT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LEVELS SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB G DOWN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE QB POWER", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Split Slot Open",
      formationType: "Gun",
      plays: [
        { playName: "BACKS CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIY SWEEP REVERSE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LOAD OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN SPOT HB CHOICE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA F SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER READ HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SNEAK BANG", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SWING LEAD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA VERTS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WHEEL SWITCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "POWER READ FOLLOW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHOVEL OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLOT POST ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TRIPLE OPTION LT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TRIPLE OPTION RT", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Split Y Off",
      formationType: "Gun",
      plays: [
        { playName: "HB INSIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN LEAD SWING", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN LEAD SWING SPACING", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN MESH RAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA HB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SNAG HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ZONE PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT CROSSING DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Dbl Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FL CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLANKER DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIRECT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HITCH CORNERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DIG", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB WRAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS MIDDLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Stack Y Off",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET PASS POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FLOOD DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "JET QB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LEVELS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT POWER CURL", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SWITCH WR DRAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Tight Open",
      formationType: "Gun",
      plays: [
        { playName: "BENCH DIG PIVOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE STUTTER FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "POST CORNER DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SAME SIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPOT X OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "VERTICALS HB BURST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y-SPOT SALEM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH HB CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB COUNTER U", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA WHEEL OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN RPO SPLIT SNAG", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA Y OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RZ MTN PA CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Pair",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA TE ATTACK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO DUO ALERT POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SNAG SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET HB ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET HB DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET QB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET SPRINT HB SLIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Wing Slot Over",
      formationType: "Gun",
      plays: [
        { playName: "HB STRONG ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA INVERTED VEER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POST CURL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WHEEL CURLS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB WRAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT SLANT-HITCH", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPRINT SWITCH SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINTOUT SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUCK SWEEP READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EMPTY HB BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EMPTY QB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "EMPTY RPO PEEK QB POWER", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA BUBBLE SLUGGO", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO PEEK POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO SWEEP ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANT STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DASH Z COMEBACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN FOLD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN LEAD OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA X CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT ZONE SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO BUBBLE Y POP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO COUNTER ALERT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE ALERT SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHOT HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINT CORNER Z CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINTOUT SLOT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "COUNTER BASH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DASH FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DASH X HITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "PA DEEP CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER Y POP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QUICK SHORT POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "REVERSE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT QB COUNTER", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO QB POWER ALERT FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SNAG Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "WIDE TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "X ISO POCO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAIL MARY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
