import { TeamPlaybookSeed } from '../types';

export const CFB27_UL_MONROE_SEED: TeamPlaybookSeed = {
  team: "UL Monroe",
  scheme: "Spread",
  sideOfBall: 'offense',
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/ul-monroe-off/",
    verified: "2026-06-30",
  },
  formations: [
    {
      formation: "I Form Wing",
      formationType: "I Form",
      plays: [
        { playName: "HB INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "X FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Bunch Wide",
      formationType: "Gun",
      plays: [
        { playName: "BRANCH RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CLEAROUT FL IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLANKER DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEVELS DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN CROSS Z DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN STICK WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB WRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SEAM DIVIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT BRANCH RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "SHIFT WHIP FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Doubles Y Off",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ANGLE CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET HB ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET HB TRAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET RPO GLANCE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA GO SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT HITCHES", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT SPLIT HITCHES", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK KNIFE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Doubles Z Close",
      formationType: "Gun",
      plays: [
        { playName: "DOUBLE SLANT SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MID ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SLUGGO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SHOCK Y-OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN SMASH Y-ZIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO GLANCE POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "Y-SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z CROSS OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z CROSSER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Doubles Z Close Wk",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER Z COMEBACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP POST SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MID ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN FK SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA X SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SWITCH WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "REDZONE FORK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Empty Base",
      formationType: "Gun",
      plays: [
        { playName: "DOUBLE SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRAG DOUBLE SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FOUR VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HITCHES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT SLOT MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "ORBIT WR SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "ORBIT Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT DIG SLOT RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT DOUBLE SCREENS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "SHIFT SHOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Slot Left",
      formationType: "Gun",
      plays: [
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PA X DEEP CHOICE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN Y LEAD READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DEEP CHOICE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "X DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Slot Left Stack",
      formationType: "Gun",
      plays: [
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POST CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT SPEED OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Slot Right",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB ISO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA MTN SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA STICKS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Slot Right Wk",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN SLUGGO SHOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER G", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO GLANCE BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE SHOCK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RZ MTN BUBBLE SLANT", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "SLANT SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICAL TE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Split Y Offset",
      formationType: "Gun",
      plays: [
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RPO ZONE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN TRIPLE OPTION RT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO COUNTER ALERT WHEEL", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TR OPT LEAD LT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TRIPLE OPTION RT", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Spread Offset",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DAGGER CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE BUBBLE SLANT", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FAKE JET HB CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RPO READ FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "ORBIT MIDDLE DIVIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT RPO ALERT SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT ZONE BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS MIDDLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH BULLSEYE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Spread Y-Flex Wk",
      formationType: "Gun",
      plays: [
        { playName: "DOUBLE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H MTN FOUR VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H MTN MIDDLE DIVIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H MTN Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN H SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RPO READ FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN SPOT Y SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SWING SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN X REPLACE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Spread Y-Slot",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "617", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS SLOT FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO READ FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINT FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINT SLOT LEAK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trio 4WR Str",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CHINA N GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL CORNER SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRAW FK BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FLOOD DELAY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB DIRECT SNAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN DRIVE MILLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN WHIP FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINT DEEP FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINT Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUBBLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DRIVE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA MIDDLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SHALLOW STING", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ SPECIAL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT INS", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK STICK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO QB DRAW SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHALLOW HB CHOICE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STICK BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "SWITCH VERTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUBBLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "CLOSE RZ CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CLOSE SAIL X FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CLOSE STICK FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS SLOT OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DEEP STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIRECT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OHIO SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA WR IN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHALLOW CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "SHOCK H OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips Offset",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE BUBBLE SLANT", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DEEP CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT ZONE BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT ZONE SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Trips TE",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CHINA GO Y-POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COMEBACK Y ANGLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURLS X GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DAGGER TEXAS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RETURN LEVELS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "ORBIT PA HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "PA BOOT SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT OUT N UP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT QUICK FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "VERTICALS HB ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips X Nasty",
      formationType: "Gun",
      plays: [
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HI LO CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HI LO DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MID ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA X CROSS SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK FORK ZIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QUICK SHORT POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT FADE H WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SNAG SLOT DIGS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SWITCH HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS X SHALLOW", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips X Nasty Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HI LO DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DRAG SLUGGO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SLOT FADES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN TRIPLE SLANTS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QUICK FORK ZIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QUICK SHORT POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QUICK UNDERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SNAG SLOT DIGS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips Y-Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DAGGER POCO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ATTACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MID ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA SWITCH DIG", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST HITCH POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLOT FORK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG FLOOD X-CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS X SHALLOW", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "GT COUNTER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER RT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN Y LEAD READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT STUTTER WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT SHOCK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO BUBBLE Y POP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO X GLANCE BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS Y OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Y Off Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HI LO DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN PUMP AND GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST N CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT SHOCK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STING", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAIL MARY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
