import { TeamPlaybookSeed } from '../types';

export const CFB27_NEVADA_SEED: TeamPlaybookSeed = {
  team: "Nevada",
  scheme: "Spread",
  sideOfBall: 'offense',
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/nevada-off/",
    verified: "2026-07-01",
  },
  formations: [
    {
      formation: "Singleback Spread",
      formationType: "Singleback",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUBBLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FLANKER DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA HB OUT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT CROSSES", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SLANT FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Wildcat Unbalanced",
      formationType: "Wildcat",
      plays: [
        { playName: "BLAST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET REVERSE PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Spread",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FADE SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WHEELIE CURLS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WHEELIES", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QUICK SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RNS HOOK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT DIVE HITCHES", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT DIVE OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ZONE ALERT X SMOKE", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Strong",
      formationType: "Pistol",
      plays: [
        { playName: "494 F FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "F LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB BLAST ALERT X SMOKE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH ALERT X LOOKIE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT LT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "X POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Trips Left Open",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUT N UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CTR WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DEEP IN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol U Off",
      formationType: "Pistol",
      plays: [
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT Y DRAG", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DEEP CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SHOT GOS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Y Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER GT ALERT SMOKE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER G", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ZONE X GLANCE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRETCH ALERT X LOOKIE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICAL TE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun 5WR",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS Z DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP DIVIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE PIVOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB BLAST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SWITCH SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TIGHT FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TIGHT SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TIGHT SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Z SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Bunch Str Wide",
      formationType: "Gun",
      plays: [
        { playName: "DIG RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD SWING OUT N UP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD SWING Z CORNER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN BENCH RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN LEAD SWING SPOT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN LEVELS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN X REPLACE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z SHORT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Double Stack",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ FL SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMOKE N GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Doubles Off Close Wk",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PIVOT IN SEAMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "X DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Doubles Y Off",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA GO SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHARK HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERT COMEBACKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y-SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Doubles Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO SPLIT ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Empty Base Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL HITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER Z UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIVIDE SLOT FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HOSS Y JUKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JAILBREAK SLOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "LEVELS SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MIDDLE HI LO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OMAHA FADE UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "REDZONE UP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT DRAW STICK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SCISSORS DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK N NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TRAIL SHAKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Slot Left Flex",
      formationType: "Gun",
      plays: [
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIG POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA CHINA GO", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DIG", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SEAMS SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Slot Right",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB ISO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DEEP CHOICE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA MTN SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT SHOCK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Split Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "CURL N GOS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FL DRAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB CROSS BUCK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN STR", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN DOUBLE PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN FB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN LEAD SWING SPOT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA STUTTER GO", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO PEEK SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN TRIPLE OPTION RT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO SPLIT ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHAKES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLANTS MIDDLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Spread",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GT READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN POST CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA FK SCREEN CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA GTZ TUNNEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Z TUNNEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT WR SCREENS", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT FADES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPOT N GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Flex Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIG H SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H MTN FOUR VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H MTN Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H MTN Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB SWING SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SPOT DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SWING SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT FADES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Offset",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DAGGER CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET HB CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO READ FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT ZONE BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS MIDDLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH BULLSEYE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Spread Y-Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CAKE READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "H SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN DASH OVER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN FK SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN G DOWN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO ZONE PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUT N UP WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTS CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Stack Y Off",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET PASS POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LEVELS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "TRAP ALERT OMAHA", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ZONE ALERT OMAHA", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Trips",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUBBLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "DOUBLE PASS RAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEVELS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MIDDLE SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SAIL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB SLOT OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE STICK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "AIR RAID UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUBBLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIRECT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MIDDLE SLAM", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OHIO SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA QB CHOICE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHOCK H OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Z SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips Offset",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE BUBBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "QB SLOT OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT ZONE BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT ZONE SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURLS SLOT WHIP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN Y LEAD READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA ZONE SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT SHOCK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO BUBBLE Y POP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO X GLANCE BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "VERTICALS Y OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAIL MARY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
