import { TeamPlaybookSeed } from '../types';

export const CFB27_4_3_PRESS_QUARTERS_SEED: TeamPlaybookSeed = {
  team: "4-3 Press Quarters",
  scheme: "4-3 Press Quarters",
  sideOfBall: 'defense',
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/4-3-press-quarters-def/",
    verified: "2026-07-01",
  },
  formations: [
    {
      formation: "46 Bear",
      formationType: "46",
      plays: [
        { playName: "46 MID BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 9", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ENGAGE EIGHT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GAP PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SAFETY FIRE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLANT WEAK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLANT WEAK 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "4-3 Over",
      formationType: "4-3",
      plays: [
        { playName: "COVER 1 ROBBER PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 CLOUD PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OLB FIRE MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "4-3 Over Solid",
      formationType: "4-3",
      plays: [
        { playName: "COVER 1 STING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 INVERT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FS BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAMMER 0 BLAST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SAW 0 BLAST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "4-3 Over Wide",
      formationType: "4-3",
      plays: [
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 CLOUD SHOW 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FIRE MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "4-3 Under Wide",
      formationType: "4-3",
      plays: [
        { playName: "COVER 1 ROBBER PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FREE FIRE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MIKE SAM CRASH PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WILL GO FIRE 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Nickel 3-3 Load Mug",
      formationType: "Nickel",
      plays: [
        { playName: "COVER 1 LB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 CLOUD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6 WILLIE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HOT BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB DE TWIST 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL BLITZ 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Nickel Load Dbl Mug",
      formationType: "Nickel",
      plays: [
        { playName: "1 DT LB LOOP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BLITZ LOOP 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BLITZ LOOP 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BLITZ LOOP SIM 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CB BENCH SIM 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 LB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB BLITZ 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "REDZONE DT DROP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SIDE BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Nickel Over",
      formationType: "Nickel",
      plays: [
        { playName: "BRACKET 9 SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COV 2 MAN CONTAIN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COV 3 BUZZ MATCH WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 CONTAIN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 BUZZ MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 DROP FIELD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6 WILLIE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 9 SAMMIE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 9 SHOW 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE BRACKET", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FIELD SIM 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OVER STORM BRAVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Nickel Single Mug",
      formationType: "Nickel",
      plays: [
        { playName: "1 LB DOG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BLITZ TEX 3 SIM 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COV 3 BUZZ MATCH WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 BUZZ MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 CLOUD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 9", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DB BLITZ TEX 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DT MIKE LOOP 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Nickel Wide",
      formationType: "Nickel",
      plays: [
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 LB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 INVERT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL SAFETY BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL 2 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "NICKEL BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SILVER SHOOT PINCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2 CONTAIN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "3-3-5 3 High",
      formationType: "3-3-5",
      plays: [
        { playName: "3 DOUBLE CLOUD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EDGE BLITZ 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HOT BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "4-2-5 Over G",
      formationType: "4-2-5",
      plays: [
        { playName: "BRACKET 9 SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 CONTAIN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 BUZZ MATCH WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6 INVERT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "COVER 6 WILLIE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 9", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE BRACKET", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE BRACKET SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PINCH BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SS BLITZ 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SS BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Dime 3-2",
      formationType: "Dime",
      plays: [
        { playName: "COVER 1 CONTAIN SPY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 BUZZ MATCH WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 CLOUD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 LOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 DROP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6 WILLIE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DB FIRE 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE BRACKET", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HOT BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OKIE EAGLE 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2 DROP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZERO BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Dime Load Weak",
      formationType: "Dime",
      plays: [
        { playName: "COV 1 ROBBER PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 DROP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DB BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DB BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PINCH BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PINCH BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SIM 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SIM PRESSURE 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Dime Rush",
      formationType: "Dime",
      plays: [
        { playName: "COVER 1 CONTAIN SPY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 HARD FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 ROLL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 BUZZ MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 CLOUD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL SAFETY BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIME BLITZ 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FOX FIRE ZONE PRESS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FS MIDDLE BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MUG BLITZ TEX 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MUG DT LOOP 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MUG SIM PRESSURE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SS OVERLOAD 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SS SIM PRESSURE 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Prevent 3 Deep",
      formationType: "Prevent",
      plays: [
        { playName: "COVER 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MAN 3 DEEP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PREVENT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Goal Line 5-3",
      formationType: "Goal Line",
      plays: [
        { playName: "GAPS AB", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GAPS ALL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GAPS ALL LB", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GAPS B", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GL MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MLB GAP A", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Goal Line 6-2",
      formationType: "Goal Line",
      plays: [
        { playName: "60 BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "60 HALF OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "60 OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "60 OUT JACKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "60 PINCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
