import { TeamPlaybookSeed } from '../types';

export const CFB27_3_4_MAN_PRESSURE_SEED: TeamPlaybookSeed = {
  team: "3-4 Man Pressure",
  scheme: "3-4 Man Pressure",
  sideOfBall: 'defense',
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/3-4-man-pressure-def/",
    verified: "2026-07-01",
  },
  formations: [
    {
      formation: "3-4 Grizzly",
      formationType: "3-4",
      plays: [
        { playName: "1 EDGE PINCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "3 EDGE PINCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 INVERT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 DROP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 9", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MIKE BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MIKE HOT BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MIKE SIM 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2 SHOW 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "3-4 Odd",
      formationType: "3-4",
      plays: [
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 DROP SHOW 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CRASH BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS 3 FIRE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PINCH BUCK 0", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SAW BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SS 2 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STORM BRAVE 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WILL BUCK 3 PRESS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "3-4 Over",
      formationType: "3-4",
      plays: [
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 INVERT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6 PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SAW BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SS 2 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SS BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STING PINCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TRIO SKY ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WILL BUCK 3 PRESS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "3-4 Under",
      formationType: "3-4",
      plays: [
        { playName: "COV 1 QB CONTAIN SPY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 FS FIRE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL SAFETY BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FS SLANT 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PINCH BUCK 0", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SAW BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WEAK BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WILL FIRE 3 SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "3-4 Under 4 Tech",
      formationType: "3-4",
      plays: [
        { playName: "COV 1 QB CONTAIN SPY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 FS FIRE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 HOLE WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 INVERT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 HARD FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL SAFETY BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FS SLANT 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MLB CROSS FIRE 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PINCH BUCK 0", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SAW BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WEAK BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WILL FIRE 3 SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Nickel 2-4",
      formationType: "Nickel",
      plays: [
        { playName: "BUCK SLANT 3", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "COVER 1 CONTAIN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 DROP FIELD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6 WILLIE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS SIM 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL SAFETY BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EDGE BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FS WILL BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OVER STORM BRAVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SILVER SHOOT PINCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SIM PRESSURE 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Nickel 2-4 Load Mug",
      formationType: "Nickel",
      plays: [
        { playName: "BLITZ LOOP 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 LB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 CLOUD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6 WILLIE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HOT BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB DE TWIST 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Nickel 2-4 Single Mug",
      formationType: "Nickel",
      plays: [
        { playName: "1 LB DOG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BLITZ TEX 3 SIM 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 INVERT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 BUZZ MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 9", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DB BLITZ TEX 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DT MIKE LOOP 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL 2 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "NICKEL BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Nickel 3-3 Load Dbl Mug",
      formationType: "Nickel",
      plays: [
        { playName: "1 DT LB LOOP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BLITZ LOOP 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BLITZ LOOP 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CB BENCH SIM 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 LB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB BLITZ 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL SIM 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "REDZONE DT DROP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SIDE BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Dime 2-3-6",
      formationType: "Dime",
      plays: [
        { playName: "1 DOUBLE SLOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "1 DOUBLE TE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "1 DOUBLE WR1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "1 DOUBLE WR2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 LB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 QB CONTAIN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER SHOW 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6 WILLIE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL SAFETY BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EDGE BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EDGE BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FIELD SIM 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FS WILL BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MAN DOUBLE BUZZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OVER STORM BRAVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SILVER SHOOT PINCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Dime 3-2",
      formationType: "Dime",
      plays: [
        { playName: "1 DOUBLE WR1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "1 DOUBLE WR2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 CONTAIN SPY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 CLOUD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 LOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 DROP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6 WILLIE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL SAFETY GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EDGE BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EDGE BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2 DROP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZERO BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Prevent 3 Deep",
      formationType: "Prevent",
      plays: [
        { playName: "COVER 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MAN 3 DEEP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PREVENT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Goal Line 5-3",
      formationType: "Goal Line",
      plays: [
        { playName: "GAPS AB", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GAPS ALL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GAPS ALL LB", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GAPS B", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GL MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MLB GAP A", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Goal Line 6-2",
      formationType: "Goal Line",
      plays: [
        { playName: "60 BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "60 HALF OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "60 OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "60 OUT JACKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "60 PINCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
