import { TeamPlaybookSeed } from '../types';

export const CFB27_PURDUE_SEED: TeamPlaybookSeed = {
  team: "Purdue",
  scheme: "Air Raid",
  sideOfBall: 'offense',
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/purdue-off/",
    verified: "2026-06-29",
  },
  formations: [
    {
      formation: "Wildcat U Off Trips",
      formationType: "Wildcat",
      plays: [
        { playName: "BLAST WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIY REVERSE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "POWER EXTRA", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB WRAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Strong Slot Open",
      formationType: "Pistol",
      plays: [
        { playName: "F LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MID SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SCAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHAKES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRETCH ALERT X LOOKIE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Weak Slot Open",
      formationType: "Pistol",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER ALERT SMOKE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DEEP CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OFFSET MTN FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OFFSET MTN RPO PEEK SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "OFFSET MTN WIDE ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SHORT POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE ALERT SMOKE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Doubles Y Off",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BOUNCE HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BOUNCE RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "BOUNCE X SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FK TOSS TE WHEEL", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FK TOSS WK FLOOD", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "GT COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ORBIT ALERT COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ORBIT PA COUNTER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "ORBIT RPO ALERT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "PA COUNTER SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA GO SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA GT Z TUNNEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT COUNTER BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Doubles Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "GT READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "H SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLOW SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FLIP COUNTER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER Y POP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT FLIP COUNTER", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK FLIP Y POP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ COUNTER BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO SPLIT ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "STRIKE HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Empty Base",
      formationType: "Gun",
      plays: [
        { playName: "686", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "986", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "986 SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRAG DOUBLE SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHALLOW SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "SHOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOCK SHAKE CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK N NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK Z POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Empty Chips",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP POST OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "POST CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Empty Quads HB",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUBBLE ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUBBLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "BUBBLE VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLAT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE CROSSES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLOT PIVOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Split Slot",
      formationType: "Gun",
      plays: [
        { playName: "689 HOOK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIY SWEEP REVERSE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB INSIDE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FLAT COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB ANGLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SWEEP WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HORIZONTAL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH POST WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN FK SWING WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN LEAD SWING", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA F SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SNEAK BANG", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO READ SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHAKES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOVEL OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT POST ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Split Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "FL DRAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN DOUBLE PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA COUNTER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA HB SWING", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO PEEK STICK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN RPO PEEK SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN RPO SWING QB DRAW", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN STICK WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA GT Z TUNNEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SNEAK CORNER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO READ CNTR", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ COUNTER SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHAKES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLANTS MIDDLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Spread",
      formationType: "Gun",
      plays: [
        { playName: "617", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GT READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "H SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEVELS Y SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN BUBBLE SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA BUBBLE WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "P AH CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA GT Z TUNNEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SHOT DINO", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO READ SLOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT FADES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH DIGS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Dbl Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS H DIVIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SLOT SHALLOW", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA HB SWING", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT Z SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHALLOW SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "SLOT FADES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT FADES HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK Z POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZIG HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS Z POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB PUMP DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HITCH SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DEEP OUTS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT HITCHES", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ COUNTER SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SEAMS DBL OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLANTS MIDDLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH CORNERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TEAR SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TEAR WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "TEAR Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y CROSS FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Spread HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CAKE READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CNTR READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "H CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HITCH SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTS CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Spread Y-Flex Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H MTN FOUR VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H MTN Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H MTN Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HITCH SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA SWITCH SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT FADES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH HB ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X REPLACE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trey Open",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CLEAROUT RUB RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS X DRAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H MTN MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H MTN MESH POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H MTN X SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WR IN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RZ Z UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHAKES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHALLOW CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "X DRAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y-SAIL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trey Open HB Str",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H MTN MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H MTN MESH POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H MTN MESH WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIRECT SNAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MIDDLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEVELS SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK Y SEAM", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "SPOT SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trey Open Offset",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CAKE READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CROSS Z CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE SHOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN FOUR VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SPOT Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "REDZONE UP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT X OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHOCK SNAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SLOT SCREEN HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DRIVE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SHALLOW STING", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO BASE ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ GT SLOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE STICK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SWITCH VERTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TRIPS CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Y Off Trio Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "IN GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MILLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN MESH OUT N UP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN MESH Y DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN MIDDLE DIVIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA DEEP OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN SMASH GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "ORBIT PA SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA HB SWING", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POST DIG SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT ORBIT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT ORBIT POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT ORBIT SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHOCK H OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPOT SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPOT Y SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK N UP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIY HB DIRECT REVERSE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIRECT SNAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB POWER RT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN STICK N NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA BOOT STUTTER WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ SMASH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO BUBBLE Y POP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO COUNTER ALERT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO COUNTER PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ COUNTER SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ GT FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPRINT FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS Y OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Y Off Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "GT COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "GT READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB FLIP COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PUMP AND GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN X SLANT SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA FLIP COUNTER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST N CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT BUBBLE DIVE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT SPLIT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE FLIP COUNTER", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SNAG Y SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAIL MARY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
