import { TeamPlaybookSeed } from '../types';

export const CFB27_TEMPLE_SEED: TeamPlaybookSeed = {
  team: "Temple",
  scheme: "Spread",
  sideOfBall: 'offense',
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/temple-off/",
    verified: "2026-06-30",
  },
  formations: [
    {
      formation: "I Form Close",
      formationType: "I Form",
      plays: [
        { playName: "HB ISO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT FLOW", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POST CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPIDER MESH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPIDER X CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA TE LEAK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Doubles Off Close",
      formationType: "Pistol",
      plays: [
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Spread Y Slot",
      formationType: "Pistol",
      plays: [
        { playName: "FADE SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FOUR VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN SPLIT DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA CORNER SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT HITCHES", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT OUTSIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Weak Slot",
      formationType: "Pistol",
      plays: [
        { playName: "COUNTER STR", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SMASH Y-CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Wing",
      formationType: "Pistol",
      plays: [
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT LT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TE ATTACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Bunch",
      formationType: "Gun",
      plays: [
        { playName: "BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BUNCH FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DASH FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "END AROUND", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD SLOT GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MID ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN CROSS SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA SAIL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN RPO READ Y SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "QUICK MTN X SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RETURN X POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "REVERSE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPACING SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Bunch Wide",
      formationType: "Gun",
      plays: [
        { playName: "CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLANKER DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PULL SHALLOW", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK RUB RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SEAM DIVIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Deuce",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BENCH SWAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CHIP POCO X DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER GOS FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FK TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN QB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN TE WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK POST FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT Z CURL", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ FLAT WHEEL", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Doubles Y Off",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BOUNCE HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BOUNCE RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "BOUNCE X SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FADE STOP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH OUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RPO 0 COUNTER", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA GO SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Z CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT SPLIT HITCHES", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT FAKE JET DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT FAKE JET LEAD SWING", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT FAKE JET PASS POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT FAKE JET TE WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT JET QB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERT COMEBACKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Doubles Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FK JET TOSS PASS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB TOSS FK JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PASS FK TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RETURN PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RETURN RPO ALERT STICK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RETURN RPO READ SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO JET ALERT SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO JET READ Y SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y RETURN INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Y RETURN MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y RETURN MESH REWIND", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Doubles Y-Flex Offset",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ANGLE SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BOUNCE OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BOUNCE PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "BOUNCE RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FORK WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FOUR VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO READ DBL SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ FLAT SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "WEAK FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Empty Base",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FK SCREEN VERTS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "ORBIT SLOT MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "ORBIT WR SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK N NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CAKE READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLANKER DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HITCH SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SMASH CORNERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trey Open",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CLEAROUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURLS DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEVELS SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WR IN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SALEM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOCK H OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y-DRAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trio HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER SIT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA CROSS SIT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO BUCK PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PIN ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPRINT RUB FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trio Unbalanced",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FL SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB SLOT OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE PASS RAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MIDDLE SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE STICK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips TE Offset Wk",
      formationType: "Gun",
      plays: [
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FLOOD DIVIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DEEP SAIL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FK BUBBLE WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER SLOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT STICK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing",
      formationType: "Gun",
      plays: [
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA FORK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLOT 2 BUC", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y DRIVE CLOWN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRAGON SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET SPRINT HB SLIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN SWITCH HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT JET QB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT JET SPRINT HB SLIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPOT OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STICK NOD VERTICAL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EMPTY HB BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EMPTY QB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "EMPTY RPO PEEK QB POWER", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER U", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH HB CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SLOT OPTION", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN TE LEAD READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CROSS SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO PEEK BUCK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO POWER ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO POWER PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO SWEEP ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Wing Trio",
      formationType: "Gun",
      plays: [
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN POST Y DELAY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN TE MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN WHIP DEEP FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO PEEK Y POP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK N NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Trips",
      formationType: "Gun",
      plays: [
        { playName: "HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT HB SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FAKE SWITCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLANTS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SWITCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA X CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT PA SLOT DIG", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SHIFT RPO ALERT ZONE SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT RPO READ SPOT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINTOUT SLOT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "619 SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ORBIT PA POST CURLS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "ORBIT RPO ALERT SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "ORBIT Y LEAD TRIPLE OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHOT Y WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Z DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing X Off",
      formationType: "Gun",
      plays: [
        { playName: "JET DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PA BOOT HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "JET PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO PEEK JET POP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Y Off Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "CORNER OUT DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURLS SLOT WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GT COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB FLIP COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB PUMP DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN SHOCK H OPT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA FLIP COUNTER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT HITCHES", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT MTN DIVE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT SHOCK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE FLIP COUNTER", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Y Trips X Off",
      formationType: "Gun",
      plays: [
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RPO READ X SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN SPRINTOUT SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT FK SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "ORBIT RPO ALERT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "ORBIT RPO QB POWER", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAIL MARY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
