import { TeamPlaybookSeed } from '../types';

export const CFB27_VIRGINIA_TECH_SEED: TeamPlaybookSeed = {
  team: "Virginia Tech",
  scheme: "Spread",
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/virginia-tech-off/",
    verified: "2026-07-01",
  },
  formations: [
    {
      formation: "Pistol Ace",
      formationType: "Pistol",
      plays: [
        { playName: "CORNER POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FL CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DEEP IN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SKINNY POSTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Bunch",
      formationType: "Pistol",
      plays: [
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OVER HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OVER HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OVER PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SEATTLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol U Off Twins Over",
      formationType: "Pistol",
      plays: [
        { playName: "HB SPLIT DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD RD TRIPLE OPTN", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA TE SLIP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO READ TE SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPLIT ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Wing",
      formationType: "Pistol",
      plays: [
        { playName: "DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT LT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CTR WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA TE SLIP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TE ATTACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Pistol Wing Slot Over",
      formationType: "Pistol",
      plays: [
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA STRETCH SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ROLLOUT FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT DIVE FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPLIT ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Bunch Quads Open",
      formationType: "Gun",
      plays: [
        { playName: "ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUNCH TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "QB BLAST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO 0 SCREEN DRAW", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Bunch Str Wide",
      formationType: "Gun",
      plays: [
        { playName: "CLEAROUT FL IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIG RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD SWING Z CORNER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN BENCH RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN X REPLACE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RETURN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RETURN LEAD SWING", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RETURN WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Bunch Wide",
      formationType: "Gun",
      plays: [
        { playName: "2 SHIELD SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "BUBBLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "CHEAT FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CHEAT SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CHEAT WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PULL SHALLOW", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LEVELS DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "POST SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB WRAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RZ RUB UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Deuce Close",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CHIP DIG 7 STOP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EXIT DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EXIT DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EXIT X OVER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB ORBIT MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB ORBIT SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB ORBIT TE MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DEEP OUT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DEEP OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y LEAK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO READ FLAT WHEEL", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Doubles Y Off",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ANGLE CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FADE STOP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FK TOSS TE WHEEL", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FK TOSS WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SNAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SPOT N GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN X SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Empty Spread",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUBBLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "DOUBLE PIVOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MOTION ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MOTION DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MOTION HB OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB BLAST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK N NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICAL LOOKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR DBL SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Empty Trey Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HI LO READ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LEVELS SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB BLAST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT DRAW STICK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK N NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK OHIO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS Y SHAKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WODT POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Flex Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "27 DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN MESH Y SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SPRINT BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SPRINT TE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA GO SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Normal Y Off",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURLS LEAD SWING", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET PASS POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FOUR VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MIDLINE READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN LEAD OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SWITCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN SPOT WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA QB CHOICE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RETURN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RETURN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO RETURN READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Normal Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "ORBIT PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "ORBIT Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ORBIT Z UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PIVOT IN SEAMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB G DOWN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT SNAG", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "X DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z UNDER SEAMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Split Y Off",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H CHOICE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Y CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Y-Flex",
      formationType: "Gun",
      plays: [
        { playName: "DEEP CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SEAMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN FK SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN FK SWING WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN FL SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN OUT H-ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN TE MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA DRAG", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SEAMS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SMASH CORNERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Y-Slot",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS SLOT WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB FLAT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN CURL FLAT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN MESH DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA WR POWER READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN WR OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN WR POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN X POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA TE WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RETURN CURLS TEXAS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RETURN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RETURN PA POST CURLS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RETURN RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SMASH HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WHEEL HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Y-Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CAKE READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "H SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DASH OVER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN G DOWN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO READ Y SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN RPO ZONE PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUT N UP WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTS CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Tight Y Off Flex",
      formationType: "Gun",
      plays: [
        { playName: "FLOOD LEVELS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Z CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trio HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER SIT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OUTSIDE CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RELOAD INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RELOAD PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RELOAD RPO ALERT BUCK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO BUCK PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPRINT SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Trips Y Slot Str",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FOUR VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN CURL X POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN FK SCREEN VERTS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN LEAD OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN SHOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN Z UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT SHOCK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT 2 BUC", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINT RIGHT SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y MTN HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Y MTN HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y MTN WHEELIES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips Y Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HANK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA QB CHOICE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RELOAD DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RELOAD HB SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "RELOAD SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO STICK QB DRAW", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT RUB RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SWITCH Z CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "POWER ALERT GLANCE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO POWER PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO SWEEP PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Trio",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GT READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN POST Y DELAY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RPO ALERT SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN RPO READ SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN SPRINT FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SWITCH FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN TE MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "ORBIT MESH HB RAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT RPO PEEK Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "PA ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA X CORNER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO PEEK Y POP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RZ ORBIT CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK N NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Trio Wk",
      formationType: "Gun",
      plays: [
        { playName: "27 MIDDLE UP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DASH X HITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DASH FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN TIGERS DASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA Y FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Trips",
      formationType: "Gun",
      plays: [
        { playName: "DBL MTN PA TE LEAK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "DBL MTN RPO ALERT SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "DBL MTN RPO PEEK POP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN DBL SMASH SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SLOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA X CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO PEEK POP SMASH", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHOT HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOT Y WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SWING HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Wing Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "619 SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ORBIT PA POST CURLS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "ORBIT RPO ALERT SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "ORBIT Y LEAD TRIPLE OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHOT Y WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Z DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAIL MARY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
