import { TeamPlaybookSeed } from '../types';

export const CFB27_OPTION_SEED: TeamPlaybookSeed = {
  team: "Option",
  scheme: "Option",
  sideOfBall: 'offense',
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/option-off/",
    verified: "2026-07-01",
  },
  formations: [
    {
      formation: "I Form Pro",
      formationType: "I Form",
      plays: [
        { playName: "BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COMEBACKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "END AROUND", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FB DIVE STRONG", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB FAKE HB FLIP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "GOAL LINE FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLAM FK END ARND", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE VEER TRIPLE OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MIDLINE TRIPLE OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA END AROUND", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "X POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Maryland I Heavy",
      formationType: "Maryland I",
      plays: [
        { playName: "HB BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB LEAD DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Maryland I Normal",
      formationType: "Maryland I",
      plays: [
        { playName: "DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB FAKE HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FLEA FLICKER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB LEAD DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER G", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FB SAIL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Power I Strong",
      formationType: "Power I",
      plays: [
        { playName: "DBL LEAD", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MISDIRECTION", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE VEER TRIPLE OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA LOOCH SPECIAL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "X SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Power I Tight",
      formationType: "Power I",
      plays: [
        { playName: "DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB LEAD DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE VEER TRIPLE OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA FB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Flexbone Close",
      formationType: "Flexbone",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FB LEAD TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB POWER SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB ZONE DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB ZONE TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FK FB TOSS ROLLOUT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FK ROCKET TOSS ROLLOUT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE VEER TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD INSIDE VEER TR WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LOAD OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MIDLINE TRIPLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN FB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA COUNTER OPTION", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FAKE TOSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FB DIVE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WB POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB COUNTER OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ROCKET TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLANT OUT TRAILS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TR CNTR PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TR CNTR WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TR OPTION CNTR", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WR DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Flexbone East",
      formationType: "Flexbone",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FLANKER DRAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE VEER TRIPLE OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MIDLINE TRIPLE OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA FB DIVE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Flexbone Normal",
      formationType: "Flexbone",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FB POWER SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB ZONE DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB ZONE TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FK FB TOSS ROLLOUT RT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FK ROCKET TOSS ROLLOUT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE VEER TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LOAD OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MIDLINE READ ISO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MIDLINE TRIPLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN FB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA COUNTER OPTION", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FB DIVE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ROCKET TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "X DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Flexbone Over Stack",
      formationType: "Flexbone",
      plays: [
        { playName: "27 COMEBACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB ZONE TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE VEER TR OPT WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE VEER TRIPLE OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MIDLINE TRIPLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Flexbone Tackle Over",
      formationType: "Flexbone",
      plays: [
        { playName: "BANG 8 SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB ZONE TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB CHOICE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE VEER TR OPT WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE VEER TRIPLE OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LOAD OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN QB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA SWITCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ROCKET TOSS WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TR CNTR WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR CORNERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Flexbone Tight",
      formationType: "Flexbone",
      plays: [
        { playName: "CORNER HOOKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FB POWER SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB STING", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB SWEEP WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB WHAM", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB ZONE DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB ZONE TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FK ROCKET TOSS ROLLOUT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HOOK FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE VEER TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LOAD OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA FB DIVE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SWITCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WB WHEELS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB CNTR OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ROCKET TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SEAMS FB OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE OPTIONS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ZIG OUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Flexbone U Off",
      formationType: "Flexbone",
      plays: [
        { playName: "FB TOSS LEAD", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB WHAM", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE VEER TRIPLE OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LOAD OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MIDLINE TRIPLE OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SWITCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA TE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "ROCKET TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TR CNTR PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TR OPTION CNTR", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Wishbone Tight",
      formationType: "Wishbone",
      plays: [
        { playName: "DOUBLE ISO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB FLAT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB STING", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB LEAD", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y LEAK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Flexbone",
      formationType: "Pistol",
      plays: [
        { playName: "ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ARC TRIPLE OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN LOAD OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SWITCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN TRIPLE OPTION STR", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN TRIPLE OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA FLOOD WK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WHEELIES", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SHOVEL OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLANT FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPLIT DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TRIPLE OPTION STRONG", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TRIPLE OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Flexbone Slot",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "F LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHOVEL OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Flexbone Trips",
      formationType: "Pistol",
      plays: [
        { playName: "F LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Full House",
      formationType: "Pistol",
      plays: [
        { playName: "DEEP CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA COMEBACKS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FLOOD COMEBACK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FLOOD FB SLIP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA X POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TR OPT SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ZONE READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Full House Twins Over",
      formationType: "Pistol",
      plays: [
        { playName: "COUNTER LEAD", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "TR OPT SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TRIPLE OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "ZONE READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Doubles",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL OUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ANGLE SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DART READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DRIVE SLOT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET PASS POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MIDLINE READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Y-SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Slot Left",
      formationType: "Gun",
      plays: [
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA COMEBACK SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA MTN SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "X DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPT RT", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Slot Right",
      formationType: "Gun",
      plays: [
        { playName: "PA WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB SLOT OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Split Slot",
      formationType: "Gun",
      plays: [
        { playName: "689 HOOK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DART TR OPTION LT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LOAD OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MID SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA F SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA VERTS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHOVEL OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLOT POST ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TRIPLE OPTION LT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TRIPLE OPTION RT", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Split Y Offset",
      formationType: "Gun",
      plays: [
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN RPO ZONE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN TRIPLE OPTION RT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TR OPT LEAD LT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TRIPLE OPTION RT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Offset",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE BUBBLE SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN TR OPTION RT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SMASH CORNERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Wing Slot Over",
      formationType: "Gun",
      plays: [
        { playName: "HB STRONG ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA INVERTED VEER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POST CURL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WHEEL CURLS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB WRAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT SLANT-HITCH", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPRINT SWITCH SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINTOUT SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wingback Doubles Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN LOAD OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ORBIT INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ORBIT PA SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "ORBIT RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT HITCHES", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINT SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "X DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAIL MARY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Wingbone Normal",
      formationType: "Wingbone",
      plays: [
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB LEAD TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FB STING", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ISO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB LEAD", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE VEER TR OPT STR", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE VEER TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD INSIDE VEER TR WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LOAD OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LOAD OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MIDLINE QB ISO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT RT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA COUNTER OPTION", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SWITCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WB DIVE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB COUNTER OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "REDZONE HB CORNER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ROCKET TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SEAM FB ANGLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Z CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Wingbone Split Wing X",
      formationType: "Wingbone",
      plays: [
        { playName: "FB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB LEAD SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB LEAD TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FB WHAM", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER FK VEER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ISO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB LEAD", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE VEER TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD INSIDE VEER TR WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LOAD OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MIDLINE QB ISO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT RT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SWITCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB CNTR OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QUICK SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ROCKET TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TR CNTR PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TR OPTION CNTR", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TR OPTION STR", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TRIPLE OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Wingbone Split Wing Z",
      formationType: "Wingbone",
      plays: [
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB LEAD TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FB WHAM", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE VEER TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD INSIDE VEER TR WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LOAD OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MIDLINE QB ISO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA SWITCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ROCKET TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPRINT Z COMEBACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TR CNTR PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TR OPTION CNTR", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TR OPTION STR", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Wingbone Twins Over",
      formationType: "Wingbone",
      plays: [
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB LEAD TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB LEAD", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE VEER TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD INSIDE VEER TR WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MIDLINE QB ISO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA SWITCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB CNTR OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ROCKET TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TR OPTION STR", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TR OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WB SWING SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
  ],
};
