import { TeamPlaybookSeed } from '../types';

export const CFB27_FLORIDA_ATLANTIC_SEED: TeamPlaybookSeed = {
  team: "Florida Atlantic",
  scheme: "Air Raid",
  sideOfBall: 'offense',
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/florida-atlantic-off/",
    verified: "2026-06-30",
  },
  formations: [
    {
      formation: "Pistol Deuce",
      formationType: "Pistol",
      plays: [
        { playName: "BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HITCH CORNERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DEEP IN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT WHEEL", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Pistol Trips",
      formationType: "Pistol",
      plays: [
        { playName: "DEEP CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FK WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LEAD OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT LT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CTR WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA X DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TE IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "X SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Wing Slot Over",
      formationType: "Pistol",
      plays: [
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER G", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA STRETCH SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ROLLOUT FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO GLANCE POST BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPLIT ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Bunch Open Offset",
      formationType: "Gun",
      plays: [
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPRINT Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Bunch Quads Open",
      formationType: "Gun",
      plays: [
        { playName: "ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUNCH TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "QB BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO 0 SCREEN DRAW", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Double Stack",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL SMASH OWLS SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EMPTY BUBBLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "EMPTY BUBBLE SPOT", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "EMPTY FK BUBBLE POST", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN DRIVE SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT QB DRAW", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT TRAP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ FL SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMOKE N GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STACK OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Doubles",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "617", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "94 Y", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ANGLE SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER BASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS HB ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRAG UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA SLIDE HB SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN RPO READ SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ FL SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPOT DBL SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPOT N GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPOT SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WEAK FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Doubles Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BOUNCE INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BOUNCE PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BOUNCE RPO GLANCE DUO", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FK POWER WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT HITCHES", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Empty Bunch Wide",
      formationType: "Gun",
      plays: [
        { playName: "DRAG CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "POST CORNER READ", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "QB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPACING SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT N GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Empty Y Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL HITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE UNDERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE WHEELS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT FK SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "ORBIT SPOT Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT TE MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "ORBIT VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT WR SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "ORBIT Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK N NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "UNDER SLOT POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREENS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y POST WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y-OPT S SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Monster",
      formationType: "Gun",
      plays: [
        { playName: "FK WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA WHEELS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ZONE ALERT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Normal Flex Close",
      formationType: "Gun",
      plays: [
        { playName: "MTN HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SLOT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT MTN BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO BUCK ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Normal Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DASH HITCH SLOT OVER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EXIT DOUBLE SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EXIT SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EXIT WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MID ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN STICK WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLUGGO SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y MTN SHOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z UNDER SEAMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN FK SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN HB SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RPO READ Y SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN RPO ZONE PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN Z SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "OUT N UP WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTS CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT HITCHES", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT FLAGS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WHEELIES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Spread Y-Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS H DIVIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET MESH WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHUFFLE X MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "SHUFFLE Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHUFFLE Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH HB CHECK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPOT Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK DOUBLE SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Y-Slot",
      formationType: "Gun",
      plays: [
        { playName: "617", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MID ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DOUBLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN H OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN H STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN SLOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN WHIP OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "ORBIT PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT ORBIT SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RZ CROSS HB RAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Stack HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "BENCH SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIY TOSS REVERSE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DOUBLE CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FADE OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FK TOSS CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN DIVIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SHOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT POWER", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "TOSS WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Trey Open",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CLEAROUT RUB RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURLS COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT DRAW STICK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHAKES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPACING HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA SAIL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE STICK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TRIPS CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTS Z FIN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Trips TE Offset",
      formationType: "Gun",
      plays: [
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEVELS SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SCAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOCK H OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TE IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips X Nasty",
      formationType: "Gun",
      plays: [
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HI LO CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HI LO DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MID ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DRAG SLUGGO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN SLOT STICK NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SPOT Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN STICK WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN TRIPLE SLANTS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA X CROSS SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SNAG SLOT DIGS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SWITCH HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS X SHALLOW", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips Y Over",
      formationType: "Gun",
      plays: [
        { playName: "FAKE BUBBLE WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RZ PA Z BANG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "OHIO SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Wing Trio Wk",
      formationType: "Gun",
      plays: [
        { playName: "BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DASH X HITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DASH FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN MESH DBL WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA Y FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z MIDDLE UP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BOUNCE INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BOUNCE OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BOUNCE PA DEEP OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FLOOD HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN Y SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA OWLS CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ SMASH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO BUBBLE Y POP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Y Off Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BOUNCE INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BOUNCE PA POST CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BOUNCE SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN PUMP AND GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN X SLANT SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK FORK ZIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QUICK SHORT POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QUICK UNDERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT SPLIT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANT Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "VERTICALS Y OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Z UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Y Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WR IN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "REVERSE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "REVERSE PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO BASE ALERT LOOKIE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO POWER PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "VERTS SLOT NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y-SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STING", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAIL MARY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
