import { TeamPlaybookSeed } from '../types';

export const CFB27_EASTERN_MICHIGAN_SEED: TeamPlaybookSeed = {
  team: "Eastern Michigan",
  scheme: "Spread",
  sideOfBall: 'offense',
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/eastern-michigan-off/",
    verified: "2026-06-30",
  },
  formations: [
    {
      formation: "Wildcat Bunch HB Str",
      formationType: "Wildcat",
      plays: [
        { playName: "HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB WRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Wildcat Jumbo Z Wk",
      formationType: "Wildcat",
      plays: [
        { playName: "BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB WRAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER G", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Wildcat Unbalanced",
      formationType: "Wildcat",
      plays: [
        { playName: "JET REVERSE PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
      ],
    },
    {
      formation: "Pistol Ace",
      formationType: "Pistol",
      plays: [
        { playName: "CORNER POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FL CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DEEP IN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SKINNY POSTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Spread",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FADE SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FADE STOP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DEEP IN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Pistol Tight Y Off Flex",
      formationType: "Pistol",
      plays: [
        { playName: "BENCH SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO READ FLAT WHEEL", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "WHEEL SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Y Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER GT ALERT SMOKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIY STRETCH REVERSE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "STRETCH ALERT X LOOKIE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICAL TE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun 5WR",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS Z DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP DIVIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE PIVOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK N NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TIGHT FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TIGHT SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TIGHT SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREENS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Bunch Open TE",
      formationType: "Gun",
      plays: [
        { playName: "DIG RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "Y TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Bunch Spread",
      formationType: "Gun",
      plays: [
        { playName: "CLEAROUT FL IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIG RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLANKER DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN CURL FLAT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SLOT HITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SLOT UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SNAG UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y-SHAKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Bunch Str Offset",
      formationType: "Gun",
      plays: [
        { playName: "CRACK TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FK TOSS SLIDE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN DEEP POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN FK TOSS VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN LEAD TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN RPO ALERT SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA SLOT OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PIN PULL TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Z SPOT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SEATTLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLANT SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPRINT DEEP FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTS DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Doubles Y Off",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ANGLE CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET PASS POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SNAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN X SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA GO SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLOT FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERT COMEBACKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y-SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Normal Y Off",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL DIG SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET PASS POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN ALL CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN SPOT WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Spread Y-Slot",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUBBLE SCREENS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB FLAT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN SPLIT ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA TE WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT OUTSIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "UNDER Y-OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "X DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X FOLLOW", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Y-Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CAKE READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "H SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DASH OVER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN G DOWN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RPO READ Y SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN RPO ZONE PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUT N UP WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTS CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Tight Open",
      formationType: "Gun",
      plays: [
        { playName: "BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BENCH DIG PIVOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BENCH RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BENCH Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIG Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "POST CORNER DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHALLOW CORNER STOP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TIGHT SEAMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS HB BURST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Tight Slot Open",
      formationType: "Gun",
      plays: [
        { playName: "BENCH SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BENCH SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL HOOK WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "STICK SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WHEEL SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUBBLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DIGS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WR IN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB SLOT OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ SPECIAL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Trips HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIRECT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OHIO SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA WR IN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RZ LEVELS X FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOCK H OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICKS SLOT POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips TE Offset",
      formationType: "Gun",
      plays: [
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEVELS SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SCAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOCK H OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wide",
      formationType: "Gun",
      plays: [
        { playName: "ALL CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL HITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUBBLE SLANT", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "CURL SEAMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DART READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DEEP CHOICE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DEEP CHOICE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DEEP SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FK SCREEN CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SEAMS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT CHOICE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT WR SCREENS", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO BASE ALERT WR SCREENS", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT CHOICE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Wide Offset",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "45 QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL HITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FADE STOP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DEEP CHOICE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT CHOICE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO TRAP ALERT SCREENS", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE ALERT HITCHES", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS MIDDLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT FADES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WHEELIES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X DEEP CHOICE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X REPLACE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wide Slot Left",
      formationType: "Gun",
      plays: [
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEVELS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CHOICE DEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DEEP CHOICE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POST CURLS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER Y POP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT HITCH", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT Z BANG", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "Y LEAD READ OPT RT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Z SLUGGO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wide Slot Right",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "COUNTER Y READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ISO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA DEEP CHOICE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT CHOICE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT COUNTER", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT POST ISO", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wide Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL HITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP CHOICE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MIDDLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HITCH MILLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA DEEP CHOICE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT CHOICE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE STICK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT TRIPLE SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO BASE HITCHES", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE ALERT SLOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TRIPLE SLANT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WHEEL CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRAGON SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB PUNCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TE SPOT OHIO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WHEEL POST DRAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Wing Tight",
      formationType: "Gun",
      plays: [
        { playName: "HB PUNCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OHIO SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA X CURL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLUGGO SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK NOD VERTICAL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN STICK N NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y LEAD READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN Y SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA ZONE SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO BUBBLE Y POP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT ALL INS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT RPO ALERT SHOCK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT 2 BUC", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS Y OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STING", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAIL MARY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
