import { TeamPlaybookSeed } from '../types';

export const CFB27_SPREAD_SEED: TeamPlaybookSeed = {
  team: "Spread",
  scheme: "Spread",
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/spread-off/",
    verified: "2026-07-01",
  },
  formations: [
    {
      formation: "Pistol Spread",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FADE SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WHEELIE CURLS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WHEELIES", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QUICK SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT DIVE HITCHES", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT DIVE OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT OUTSIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ZONE ALERT X SMOKE", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Wingback Trips",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "F LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Y Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SPLIT DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB WIDE ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT RT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA COUNTER Y SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "ROLLOUT FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Box",
      formationType: "Gun",
      plays: [
        { playName: "DEEP CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP FORK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FL DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QUADS JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "QUADS RPO ALERT QB DRAW", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "QUADS SWITCH SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLANTS FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SWITCH POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Bunch Open Offset",
      formationType: "Gun",
      plays: [
        { playName: "DEEP FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD SWING SPOT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEVELS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT MESH Z OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT SPRINT Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Bunch Open TE",
      formationType: "Gun",
      plays: [
        { playName: "DIG RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "Y TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Bunch Quads Open",
      formationType: "Gun",
      plays: [
        { playName: "ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN DRAG UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SLOT MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN SWING SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Bunch Trio Open",
      formationType: "Gun",
      plays: [
        { playName: "DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FLOOD SWAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FOUR VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA CHOICE VERT COMEBACKS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FAKE SCREEN VERTS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT QB DRAW", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "Y TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Deuce",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BENCH SWAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DOUBLE GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EXIT PA WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "EXIT RPO PEEK SNAG", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "EXIT RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y LEAK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO READ SNAG", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TEAR MESH POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TEAR QB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TEAR SHOVEL OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TEAR SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TEAR SWITCH VERTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TEAR TE MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Double Stack",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN GO", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT TRAP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SMOKE N GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Doubles Offset Wk",
      formationType: "Gun",
      plays: [
        { playName: "FOUR VERTICALS OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ORBIT FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "ORBIT INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ORBIT PA X SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT POWER BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK BUCK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK ORBIT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK ORBIT SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK ORBIT SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO POWER PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRIKE HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Doubles Y Off",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ANGLE CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA Y SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA GO SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Z CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TEAR RZ CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TEAR SHOVEL OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TEAR SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "VERT COMEBACKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Doubles Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB ANGLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN LEAD SWING SPOT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ORBIT INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ORBIT PA SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "ORBIT RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Duo",
      formationType: "Gun",
      plays: [
        { playName: "DOUBLE SNAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB PUNCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET HB PUNCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET PA HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LEVELS HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA ROLLOUT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WHEELIES", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "X DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Duo Slot Open",
      formationType: "Gun",
      plays: [
        { playName: "HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEVELS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LOAD OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA COMEBACKS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FIN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA ROLLOUT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA ROLLOUT OUT-N-UP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA ROLLOUT SMASH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT HITCHES", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT SPOT WHEEL", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ HB FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPOT LEAD SWING", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPRINTOUT FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TRIPLE OPTION RT", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Empty Base Trio",
      formationType: "Gun",
      plays: [
        { playName: "BUBBLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP ATTACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIVIDE DOUBLE IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SLANT STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRAG SLOT FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HITCHES SLOT IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HOSS JUKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHOCK LEVELS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOCK SLOT OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT FADE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS H OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun F Twins Over",
      formationType: "Gun",
      plays: [
        { playName: "JET CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "JET HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET QB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET QB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun F Twins Over Wk",
      formationType: "Gun",
      plays: [
        { playName: "JET INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET QB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "JET SPRINT HB CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO CNTR READ HB SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN WR COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Normal Flex Close",
      formationType: "Gun",
      plays: [
        { playName: "MTN HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN SLOT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT MTN BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO BUCK ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Spread Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP ATTACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DEEP OUTS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DIG", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT FLAGS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH CORNERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TEAR SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TEAR WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "TEAR Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Spread HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CAKE READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLANKER DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "WHEELIES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Wing Y-Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP OUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SMASH SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET FB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LEVELS SLOT SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB LEAD", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT QB COUNTER", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT QB LEAD", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT QB POWER WK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT QB SPLIT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SWITCH SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SWITCH SMASH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Tight Doubles",
      formationType: "Gun",
      plays: [
        { playName: "21G UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS WHEELS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA DEEP CURLS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WR CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SLANT UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TIGHT FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trio 4WR Str",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CHINA N GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL CORNER SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FLOOD DELAY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHORT POSTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINT Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trio Offset Wk",
      formationType: "Gun",
      plays: [
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MIDDLE SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA FLANKER SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB SLOT OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO PEEK POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUBBLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "CURL POST WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FL DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEVELS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA MIDDLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WR IN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO BASE ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE STICK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRAGON SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE ALERT HITCHES", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPOT OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STICK NOD VERTICAL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Trio",
      formationType: "Gun",
      plays: [
        { playName: "DASH CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GT READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN WHIP DEEP FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT MESH HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT RPO PEEK Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "PA ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT CORNER-POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA X CORNER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO PEEK Y POP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RZ ORBIT CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WIDE TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Y FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "619 SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN CROSS Z POCO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DASH HITCH OVER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUADS CROSS Y DELAY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QUADS DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QUADS SPRINT SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SWITCH COMEBACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SWITCH Z CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SWING SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB ZONE TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD SWING ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN Y LEAD READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ SMASH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINT FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAIL MARY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
