import { TeamPlaybookSeed } from '../types';

export const CFB27_MICHIGAN_STATE_SEED: TeamPlaybookSeed = {
  team: "Michigan State",
  scheme: "Pro Style",
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/michigan-state-off/",
    verified: "2026-06-30",
  },
  formations: [
    {
      formation: "Singleback Bunch TE",
      formationType: "Singleback",
      plays: [
        { playName: "HB MISDIRECTION LEAD", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB PUMP DRAW", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA BOOT OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA BOOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA DEEP OVER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA SWITCH REPLACE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET DEEP OUT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SHIFT DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT PA DUO CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SWITCH SNAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR POWER FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Singleback Bunch X Nasty",
      formationType: "Singleback",
      plays: [
        { playName: "CHEAT COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CHEAT HB SLASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CHEAT HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CRACK TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "END AROUND POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET SWEEP WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA DEEP X OVER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN X WHIP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT CHEAT SLIDE LEVELS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CHEAT DEEP CORNER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DEEP CROSS GO", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WR CHEAT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PITCH WR REVERSE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WIDE ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Singleback Tight Y Off Flex",
      formationType: "Singleback",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB WK TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET HB SPLIT ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y MIDDLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Singleback Toad X Nasty",
      formationType: "Singleback",
      plays: [
        { playName: "DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MID ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB POWER G", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB MISDIRECTION", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SLASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA BOOT RT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA BOOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA SLOT OVER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POST DIG", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER G BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER G DRIVE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Strong I H Wing",
      formationType: "Strong I",
      plays: [
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "F TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB CNTR WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OVER HB BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OVER HB DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OVER PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "X SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Bunch TE",
      formationType: "Pistol",
      plays: [
        { playName: "CROSS DRAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FK JET INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "JET TOUCH PASS FK HB", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA CURLS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPOT OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Pistol Wing Flex Close",
      formationType: "Pistol",
      plays: [
        { playName: "HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA BOOT LT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT Y SAIL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DEEP CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO READ JET SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WR UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Bunch",
      formationType: "Gun",
      plays: [
        { playName: "CURL FLAT FLAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURLS ATTACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP ATTACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO READ Y SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT BUCK SWEEP READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT PA DBL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Bunch Str Offset",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FK TOSS DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FK TOSS SLIDE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MTN DIG SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB MTN QB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MTN QB ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PIN PULL TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT LEAD SWING SPACING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "SHIFT RPO ALERT STICK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT Y TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Bunch X Nasty",
      formationType: "Gun",
      plays: [
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH TRAFFIC X UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN MESH CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RETURN MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RETURN SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RETURN WHIP TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ZONE ALERT FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "X CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CORNER PIVOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT GOALLINE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Deuce",
      formationType: "Gun",
      plays: [
        { playName: "BENCH SWAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SHIFT INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT PA COMEBACKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Doubles Offset Wk",
      formationType: "Gun",
      plays: [
        { playName: "FOUR VERTICALS OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET QB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET QB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RPO READ CNTR SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN RPO READ FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "ORBIT PA X SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK ORBIT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK ORBIT SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO POWER PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Empty Base Trio",
      formationType: "Gun",
      plays: [
        { playName: "ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUBBLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP ATTACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIVIDE DOUBLE IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SLANT STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HOSS JUKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT BUBBLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "SHIFT BUBBLE SPOT DIG", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "SHIFT BUBBLE Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "SHIFT DOUBLE IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT RZ Z UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT SHOCK SLOT OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHOCK SLOT OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLOT FADE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT SHAKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS H OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Empty Chips",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP POST OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "POST CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Empty Chips Tight",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP POST OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE 7 STOP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN MESH Y-CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN OUTS Y-POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SALEM X-SWIRL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "POST CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT MESH OUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT OUTS SLOT POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Normal Y Off",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN ALL CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN PA READ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN Y MIDDLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA BOOT SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT Z CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT Z OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RZ Z SLUGGO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SEAM F ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SNAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTS Y DELAY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Spread Y-Slot",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIGS H OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DOUBLE SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLANKER DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN H OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN WHIP OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA Y OPTION", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RZ CROSS HB RAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WHEELIES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y WHIP OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Tight Open",
      formationType: "Gun",
      plays: [
        { playName: "BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BENCH Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RPO READ FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "ORBIT MESH RAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT WHIP FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST CORNER DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT BENCH HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT MESH DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT RPO ALERT STICK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS HB BURST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trio HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER SIT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "OUTSIDE CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA CROSS SIT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT BUCK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT SHOCK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK IN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips TE",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ORBIT PA HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "ORBIT TE MIDDLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA SLOT CORNER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB STRONG POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RELOAD PA UNDERS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RELOAD RPO ZONE ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RELOAD SHOCK HB CHOICE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SHIFT READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT RPO ALERT Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "TE SWIRL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTS Y DELAY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips TE Offset",
      formationType: "Gun",
      plays: [
        { playName: "BUBBLE FLOOD", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "DBL MTN FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL MTN JET POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DBL MTN JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Trips Y Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA QB CHOICE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT QB COUNTER", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO STICK QB DRAW", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RZ RUB CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT RPO STICK QB DRAW", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT SHOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT VERTS X DRAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WHIP Z POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun U Off Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER SIT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PA U SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET QB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEVELS OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT COUNTER U", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SHIFT PA COUNTER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT RPO PEEK U POP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT SPOT QUADS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRAGON SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN QB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN SWITCH HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT JET POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPOT SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK NOD VERTICAL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Trips",
      formationType: "Gun",
      plays: [
        { playName: "DASH FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD SWING STICK", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLANTS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA X CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST-CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT PA SLOT DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT RPO ALERT ZONE SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT RPO READ SPOT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK N NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK SLOT CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTS Y DELAY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN VERTS Y DELAY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y MIDDLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA DEEP CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT MESH HB SHOOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT MESH Y SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT TE SLIDE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "SHOT Y WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTS Y DELAY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Z DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BOUNCE OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BOUNCE SHALLOW SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BOUNCE Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "COUNTER Y READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DEEP OUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT SHOCK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO X GLANCE BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT ALL INS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT RPO ALERT SHOCK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER G", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STING", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT LT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAIL MARY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
