import { TeamPlaybookSeed } from '../types';

export const CFB27_4_3_MAN_PRESSURE_SEED: TeamPlaybookSeed = {
  team: "4-3 Man Pressure",
  scheme: "4-3 Man Pressure",
  sideOfBall: 'defense',
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/4-3-man-pressure-def/",
    verified: "2026-07-01",
  },
  formations: [
    {
      formation: "4-3 Even 6-1",
      formationType: "4-3",
      plays: [
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 MLB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 BUZZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MIKE WILL BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SAM BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SAM WILL BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "4-3 Over Solid",
      formationType: "4-3",
      plays: [
        { playName: "COVER 1 STING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 INVERT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FS BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAMMER 0 BLAST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SAW 0 BLAST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "4-3 Over Walk",
      formationType: "4-3",
      plays: [
        { playName: "CORNER BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 CONTAIN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 SS BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MIKE WILL BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SAM WILL BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SS BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WILL BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "4-3 Over Wide",
      formationType: "4-3",
      plays: [
        { playName: "COVER 1 CONTAIN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 INVERT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FIRE MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FREE FIRE 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SAM BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "4-3 Under Wide",
      formationType: "4-3",
      plays: [
        { playName: "COVER 1 CONTAIN PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 FS FIRE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 HOLE PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 SLANT CRASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FREE FIRE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FS FIRE 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAMMER 0 BLAST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MIKE SAM CRASH PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SAFETY BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SAM BLITZ 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WILL GO FIRE 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "5-2 Normal",
      formationType: "5-2",
      plays: [
        { playName: "COVER 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DT LOOP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FIRE ZONE 2", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FLASH BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PINCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TRIO SKY ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Nickel 3-3 Cub",
      formationType: "Nickel",
      plays: [
        { playName: "1 SAM SS BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "3 SAM WILL BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 CONTAIN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 BUZZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 SHOW 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MIKE BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OLB BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SS BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Nickel Load Dbl Mug",
      formationType: "Nickel",
      plays: [
        { playName: "1 DT LB LOOP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BLITZ LOOP 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BLITZ LOOP 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 LB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "REDZONE DT DROP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SIDE BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Nickel Load Mug",
      formationType: "Nickel",
      plays: [
        { playName: "BLITZ LOOP 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 LB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LB DE TWIST 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Nickel Over",
      formationType: "Nickel",
      plays: [
        { playName: "1 DOUBLE WR1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COV 2 MAN CONTAIN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 LB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 SS BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6 WILLIE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL SAFETY BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EDGE BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EDGE BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FS WILL BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL 2 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OVER STORM BRAVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OVERLOAD BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOW SS SIM 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Nickel Wide",
      formationType: "Nickel",
      plays: [
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 LB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL SAFETY BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "NICKEL 2 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "NICKEL BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OVER STORM BRAVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SILVER SHOOT PINCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2 CONTAIN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "3-3-5 Penny",
      formationType: "3-3-5",
      plays: [
        { playName: "3 SAM WILL BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER BLITZ 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 BUZZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 MATCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 SKY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER HOLE 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE DOUBLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HOT BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MIKE BLITZ 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MIKE BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SAW BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Dime 3-2",
      formationType: "Dime",
      plays: [
        { playName: "1 DOUBLE WR1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "1 DOUBLE WR2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 CONTAIN SPY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 CLOUD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 3 LOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 DROP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 QUARTERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 6 WILLIE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL SAFETY GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EDGE BLITZ 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EDGE BLITZ 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2 DROP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZERO BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Dime Single Mug",
      formationType: "Dime",
      plays: [
        { playName: "1 LB DOG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BLITZ TEX 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COV 3 BUZZ SHOW 1", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 GAMES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 HOLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 1 ROBBER PRESS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 2 MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COVER 4 PALMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DB BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DB BLITZ TEX 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL SAFETY BLITZ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TAMPA 2", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Prevent 3 Deep",
      formationType: "Prevent",
      plays: [
        { playName: "COVER 3", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MAN 3 DEEP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PREVENT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Goal Line 5-3",
      formationType: "Goal Line",
      plays: [
        { playName: "GAPS AB", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GAPS ALL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GAPS ALL LB", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GAPS B", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GL MAN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MLB GAP A", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Goal Line 6-2",
      formationType: "Goal Line",
      plays: [
        { playName: "60 BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "60 HALF OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "60 OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "60 OUT JACKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "60 PINCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
