import { TeamPlaybookSeed } from '../types';

export const CFB27_SOUTH_ALABAMA_SEED: TeamPlaybookSeed = {
  team: "South Alabama",
  scheme: "Spread",
  sideOfBall: 'offense',
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/south-alabama-off/",
    verified: "2026-06-30",
  },
  formations: [
    {
      formation: "Pistol Bunch",
      formationType: "Pistol",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DASH FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DASH SLOT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DASH WR LEAK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLANKER DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO READ Y SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Deuce Close",
      formationType: "Pistol",
      plays: [
        { playName: "BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA BOOT Y LEAK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Z OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Open Slot Stack",
      formationType: "Pistol",
      plays: [
        { playName: "F LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FLAT COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SPLIT DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA POST CURLS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT SPLIT DIVE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Bunch",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DASH FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "END AROUND", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE REVERSE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FL PIVOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLANKER DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO READ Y SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "REVERSE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT ZONE HITCH", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "VERTS HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZIPPER BENCH SLOT DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZIPPER MESH POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZIPPER SPACING SLOT POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Bunch Wide",
      formationType: "Gun",
      plays: [
        { playName: "CLEAROUT FL IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SEAM DIVIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLANT SPACING DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT HOOK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED DIG OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Deuce",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BENCH SWAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ESCORT INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ESCORT PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ESCORT RPO READ FLAT WHEEL", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN QB ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN TE WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y LEAD READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO READ FLAT WHEEL", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Deuce Close",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BENCH X DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CHIP DIG 7 STOP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CHIP POCO X DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN JAGUARS SPLIT ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA DEEP OVER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RPO ALERT SPLIT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "OUT N UPS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DEEP OUT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DEEP OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POST CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO READ CNTR", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ FLAT WHEEL", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Double Stack",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN GO", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT TRAP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Doubles",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP OUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FADE HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET PASS POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO READ SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA ZONE READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB WRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Doubles HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "BOOMERANG 0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BOOMERANG SLOT SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "BOOMERANG Y DELAY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BUCK SWEEP READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA DEEP POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PIN PULL SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PORTLAND MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUCK BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SAIL DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINT SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TUNNEL HB FLARE", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Z REPLACE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Empty Base Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL HITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER UP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HOSS Y JUKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JAILBREAK SLOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "QB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "REDZONE UP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK N NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TRAIL SHAKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Empty Chips Nasty",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP POST OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIG STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE 7 STOP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SWIRL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUT X DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "POST CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Flex Y Off",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURL OHIO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA JAGUARS FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN WR CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SEAM DIGS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT HB ZONE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "TEXAS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Split Close",
      formationType: "Gun",
      plays: [
        { playName: "CLEAROUT CROSSER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CLOSE FB TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB GUT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA F SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SCAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TRIPLE OPTION LT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "VERTICAL SHOTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Y-Slot",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HITCH SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT RUB OUT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z7 SHALLOW", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Stack Y Off",
      formationType: "Gun",
      plays: [
        { playName: "BENCH HB ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET PASS POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FLOOD DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "LEVELS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Stack Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "BENCH SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN GO", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "LEVELS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RETURN BENCH CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RETURN JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "RETURN RPO ALERT SNAG", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO POWER ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO SPLIT ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO TRAP ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Tight Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "CLEAROUT SIDELINE OUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIG HB OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FLANKER SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA CORNER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PIVOT DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ZONE ALERT GLANCE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE ALERT SNAG", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Trey 4WR",
      formationType: "Gun",
      plays: [
        { playName: "5 6 TRAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DASH FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DASH HB FLAT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SLOW SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SWITCH VERTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "UNDER N GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trey Y-Flex",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE POST OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LEVELS SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "LEVELS Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST Y DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT OMAHA", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE Y PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SCAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOCK HB ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK NOD H-ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WHIPS HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Trips TE Offset Wk",
      formationType: "Gun",
      plays: [
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FLOOD DIVIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MIDDLE SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA VERTS SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ Y CORNER", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PIN ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun U Off Trips Flex",
      formationType: "Gun",
      plays: [
        { playName: "CHINA DOUBLE IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DAGGER H-CHOICE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD Y-DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEVELS Y SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SLOT FADE Y-CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN STICK Y-NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN VERTICALS Y-CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA SCISSORS CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST WHEEL TEXAS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLOT SHOT Y-SWIRL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH Y-SHAKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing",
      formationType: "Gun",
      plays: [
        { playName: "HB ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA FORK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLOT 2 BUC", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE ATTACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y DRIVE CLOWN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing HB Wk Close",
      formationType: "Gun",
      plays: [
        { playName: "BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER U", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Stack",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FADE OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OHIO SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA CURL POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Y LEAD READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Wing Tight Nasty",
      formationType: "Gun",
      plays: [
        { playName: "BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BENCH SWAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB PUNCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Wing Trips",
      formationType: "Gun",
      plays: [
        { playName: "FOUR VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN FOLD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN LEAD OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA Z TUNNEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA X CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RETURN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RETURN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RZ RETURN PA SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINTOUT SLOT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK N NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN STICK N NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y LEAD READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN Y SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO BUBBLE Y POP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO X GLANCE BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Y Off Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN PUMP AND GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN X SLANT SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST N CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT BUBBLE DIVE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHOCK H OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLANT Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "VERTICALS Y OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STING", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAIL MARY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
