import { TeamPlaybookSeed } from '../types';

export const CFB27_WESTERN_MICHIGAN_SEED: TeamPlaybookSeed = {
  team: "Western Michigan",
  scheme: "Spread",
  sideOfBall: 'offense',
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/western-michigan-off/",
    verified: "2026-06-30",
  },
  formations: [
    {
      formation: "Wildcat Unbalanced",
      formationType: "Wildcat",
      plays: [
        { playName: "BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "COUNTER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET REVERSE PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Ace Slot",
      formationType: "Pistol",
      plays: [
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA FL STRETCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPEED OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Bunch",
      formationType: "Pistol",
      plays: [
        { playName: "DASH SLOT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLANKER DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO READ Y SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DEEP IN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SEATTLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLANT SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Deuce Close",
      formationType: "Pistol",
      plays: [
        { playName: "BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Full House",
      formationType: "Pistol",
      plays: [
        { playName: "DEEP CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN FLOOD HB CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RPO COUNTER ALERT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA X POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE READ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Full House Twins Over",
      formationType: "Pistol",
      plays: [
        { playName: "HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "TR OPT SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TRIPLE OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WING LEAD TRIPLE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WING PA CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WING ZONE READ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "ZONE READ", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Strong Slot",
      formationType: "Pistol",
      plays: [
        { playName: "DOUBLE FLARES", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "F LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FADE SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT LT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA LEVELS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TR OPTION LT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WR SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Wing",
      formationType: "Pistol",
      plays: [
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB SPLIT ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA BOOT LT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT LT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT U WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA TE SLIP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPEED OPTION WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TE ATTACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Pistol Y Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DASH FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIY STRETCH REVERSE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB WIDE ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN FAKE SCREEN CROSS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN RPO ZONE ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT RT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA STRETCH SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ZONE ALERT OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun 5WR Trio",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN MESH Y-POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOCK SLOT OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WHIPS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WHIPS CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREENS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Bunch Quads Open",
      formationType: "Gun",
      plays: [
        { playName: "ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUNCH TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "QB BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO Q SCREEN DRAW", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Bunch TE Wk",
      formationType: "Gun",
      plays: [
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MESH MILLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH SLOT DEEP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH X-POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DIVIDE X-UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN ESCORT HB BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN ESCORT INSERT X-OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN ESCORT PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN FLOOD H-SNEAK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SNAG UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA WHEEL 2-CURL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHALLOW H-CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPACING X-WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Deuce Close",
      formationType: "Gun",
      plays: [
        { playName: "HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y LEAK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RETURN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RETURN RPO READ FLAT WHEEL", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RETURN RZ TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO READ FLAT WHEEL", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPACING SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Deuce Twins Over",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO READ U SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHIFT INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT QB ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT RPO READ FLAT WHEEL", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Double Stack",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN GO", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT TRAP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ FL SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Doubles Offset Wk",
      formationType: "Gun",
      plays: [
        { playName: "BUCK SWEEP BEHIND", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FOUR VERTICALS OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ORBIT FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SWEEP FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK BUCK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK ORBIT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK ORBIT SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "STRIKE HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Doubles Y Off",
      formationType: "Gun",
      plays: [
        { playName: "LEAD SWING ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "OVER RPO ALERT ZONE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "OVER RPO PEEK Y POP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "OVER RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHARK HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Doubles Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "H SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN FAKE JET SHOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN JET QB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN LEAD SWING SPOT", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN PA WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN STICK WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTS CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA POWER Y POP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT COUNTER", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPRINT OUT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "SPRINT SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Empty Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FOUR VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET QB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET QB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TE MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RZ DOUBLE UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINT SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Normal Y Off",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL DIG SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL MTN HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DBL MTN HB WRAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL MTN READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET PASS POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SEAM WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA WHEEL SHOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RPO READ Y JAB FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO READ FL SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHOT DEEP POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK SLOT OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Split Twins Offset",
      formationType: "Gun",
      plays: [
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB CROSS BUCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB POWER G", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA Y SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SHOVEL OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN X SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OVER MTN BUCK TRIPLE OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OVER MTN OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OVER MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA F SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA THROWBACK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER G", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TRIPLE OPTION LT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TRIPLE OPTION RT", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Split Z Plus",
      formationType: "Gun",
      plays: [
        { playName: "27 MTN PA HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN ALERT SWING POWER G", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN ALERT SWING ZONE", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN PA WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z MTN ALERT BUCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z MTN ALERT SPLIT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Dbl Flex Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLANKER DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HITCH SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SLANTS MIDDLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERT COMEBACKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Y-Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CAKE READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DOUBLE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "G TRAP READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN DASH OVER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DRIVE CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN RPO ALERT QB DRAW", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN RPO ALERT QB POWER", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT FLAGS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WR UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Tight Slots",
      formationType: "Gun",
      plays: [
        { playName: "CURL OUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FOUR VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN BENCH SWAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA FLOOD UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN SALEM SLOT OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA X CLOWN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA ZONE FK JET", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO READ SLOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR CORNERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Trey 4WR",
      formationType: "Gun",
      plays: [
        { playName: "56 TRAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DASH FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DASH HB FLAT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SLOW SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SWITCH VERTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "UNDER N GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips TE Offset",
      formationType: "Gun",
      plays: [
        { playName: "BUBBLE FLOOD", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "DBL MTN FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL MTN JET POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DBL MTN JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SCAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOCK H OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TE IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FOUR VERTS SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHALLOW MILLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHIFT JET POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTS CHOICE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WHEEL POST DRAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Wing Slot Over",
      formationType: "Gun",
      plays: [
        { playName: "HB STRONG ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RPO ALERT SLANT FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN RPO ALERT WR SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA INVERTED VEER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POST CURL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WHEEL CURLS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT SLANT-HITCH", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RUB Z UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPRINT SWITCH SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINTOUT SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Trips",
      formationType: "Gun",
      plays: [
        { playName: "BUBBLE DOUBLE GO", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "DBL MTN HB POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DBL MTN HB WRAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL MTN POWER G", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DIY REVERSE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA CURLS TE DELAY", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SHAKES", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLANTS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SWITCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA X CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST-CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE POST BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPRINTOUT SLOT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "619 SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "COUNTER BASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DRIVE SLOT WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN TE SLIDE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN VERTS Y DELAY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA DEEP CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STING", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAIL MARY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
