import { TeamPlaybookSeed } from '../types';

export const CFB27_UTAH_STATE_SEED: TeamPlaybookSeed = {
  team: "Utah State",
  scheme: "Run & Shoot",
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/utah-state-off/",
    verified: "2026-06-30",
  },
  formations: [
    {
      formation: "Singleback Deuce Close",
      formationType: "Singleback",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER STOPS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DIY STRETCH REVERSE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FLOOD TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MOTION POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA BOOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DEEP CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA STRETCH SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Z CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SPACING SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE SPLIT WK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Singleback Wing Close",
      formationType: "Singleback",
      plays: [
        { playName: "COUNTER U", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL OUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MID ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB TOSS SPLIT ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FK TOSS FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA TE FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y-DRAG WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PITCH LEAD WR REVERSE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RZ PA CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Deuce",
      formationType: "Pistol",
      plays: [
        { playName: "BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HITCH CORNERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DEEP IN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA TE WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT TE FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT WHEEL", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ TE FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHORT POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Strong",
      formationType: "Pistol",
      plays: [
        { playName: "494 F FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CLOSE HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CLOSE HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CLOSE PA STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB BLAST ALERT X SMOKE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT LT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Wing Close",
      formationType: "Pistol",
      plays: [
        { playName: "FLANKER DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT LT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA STRETCH SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO POWER ALERT OUTS", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "TE ATTACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Y Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DASH FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GT COUNTER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ZONE X GLANCE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRETCH ALERT X LOOKIE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICAL TE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Doubles",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER BASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS HB ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURLS SLOT SHAKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DART READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DEEP IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP OUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIY ZONE REVERSE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DOUBLE SLUGGO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FADE HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO READ SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO READ FL SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SAME SIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SKINNY POSTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLANT FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK SLOT OPT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Doubles HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FOUR VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA Y-CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PIN PULL SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPRINT SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "X DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z REPLACE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Empty Trips Speed",
      formationType: "Gun",
      plays: [
        { playName: "DEEP CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLANKER UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HOSS Y JUKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JAILBREAK SLOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "LEVELS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN FK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN WR ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "QB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "REDZONE UP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOCK WR OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TRAIL SHAKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WHIP UNDERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Slot F Wing",
      formationType: "Gun",
      plays: [
        { playName: "DOUBLE SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TEXAS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WEAK FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Slot Left",
      formationType: "Gun",
      plays: [
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA COMEBACK SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Slot Left Wk",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA CHOICE DEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POST CURLS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO GLANCE POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO SPLIT ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICAL TE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Slot Right",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB ISO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DEEP CHOICE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA MTN SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT SHOCK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Slot Right Wk",
      formationType: "Gun",
      plays: [
        { playName: "CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN CROSS HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN TR OPTLT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN WR SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT SHOCK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHOVEL OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLANT SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICAL TE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Split Close Pro",
      formationType: "Gun",
      plays: [
        { playName: "CHEAT FB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA CHEAT DOUBLE CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CHEAT WHEEL POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA F SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ZONE PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "Y CURL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y-OFF PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y-OFF POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Y-OFF POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Split Pro Far",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB LEAD ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA F SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POST CURLS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO READ F SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO SPLIT ALERT SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "TE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "X DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Split Pro Near",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y LEAK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO READ F SLIDE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Split Pro Offset Wk",
      formationType: "Gun",
      plays: [
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA F SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Dbl Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FL CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIRECT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA DIG", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT Z SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANTS MIDDLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT OUTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Dbl Flex Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER STRIKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "EMPTY MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "EMPTY MTN WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "EMPTY MTN Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLANKER DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HITCH SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN OUT N UP SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA CROSS CHOICE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SLANTS MIDDLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERT COMEBACKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trey 4WR",
      formationType: "Gun",
      plays: [
        { playName: "5 6 TRAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DASH FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DASH HB FLAT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SLOW SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SWITCH VERTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "UNDER N GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "UNDERS SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHORT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trey Open HB Str",
      formationType: "Gun",
      plays: [
        { playName: "FOUR VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H MTN MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H MTN MESH POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "H MTN MESH WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEVELS SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA HB SLIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN WR BASH OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN WR OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA LEAK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT SMOKE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK HITCH", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO QB ALERT DRAW", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SCISSORS Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOCK Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "SLOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Tight Z",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER U", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GOAL LINE FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB PUNCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FLANKER CURL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO GLANCE POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "Z MTN DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Z MTN INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Z MTN PA CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Y Off Trio Wk",
      formationType: "Gun",
      plays: [
        { playName: "BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "COMEBACKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DAGGER X OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE DRAGS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB CIRCLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MILLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA POST DIG SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WR IN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK FORK ZIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QUICK SHORT POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QUICK UNDERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOCK H OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT 2 BUC", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK N UP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICAL TE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Y Off Trips Close",
      formationType: "Gun",
      plays: [
        { playName: "DEEP SLOT CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE INS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH Y OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN CORNERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN EMPTY DBL UNDERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN EMPTY HB SLUGGO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN EMPTY SMASH Y-POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y POCO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA COPO CROSS DIG", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FORK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STUTTER CURL SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE WHIP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WHEEL MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WHIP DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "X CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y-OPTION WHEEL", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Y Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURLS COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DAGGER Y WHIP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIG X COMEBACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE Y SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FORK Y DRAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FOUR VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MID ZONE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB POWER LT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SMASH SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN RPO BASE ALERT SMASH", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN RZ CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SMASH HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN WEAK FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Z CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA POST CROSS SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y-OUT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STING", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAIL MARY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
