import { TeamPlaybookSeed } from '../types';

export const CFB27_PRO_STYLE_SEED: TeamPlaybookSeed = {
  team: "Pro Style",
  scheme: "Pro Style",
  sideOfBall: 'offense',
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/pro-style-off/",
    verified: "2026-07-01",
  },
  formations: [
    {
      formation: "Singleback Ace",
      formationType: "Singleback",
      plays: [
        { playName: "24 ZONE OPEN", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ACE WR STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURL FLAT CHECK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BLUNT DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SKINNY POSTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE SEAMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Singleback Ace Overload",
      formationType: "Singleback",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB BELLY WEAK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB MISDIRECTION", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BELLY SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA LT SNEAK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA MISDIRECTION", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA TE SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
      ],
    },
    {
      formation: "Singleback Bunch",
      formationType: "Singleback",
      plays: [
        { playName: "CRACK TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DIG RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "END AROUND LEAD", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLASH FK END ARND", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CROSS SWITCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA END AROUND SIFT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PITCH WR REVERSE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPACING SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE HOOK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Singleback Deuce Close",
      formationType: "Singleback",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER STOPS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FLOOD TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MOTION POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA MTN SPIDER Y LEAK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA RZ CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA STRETCH SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Z CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SPACING SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE SPLIT WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Singleback Doubles Off Close",
      formationType: "Singleback",
      plays: [
        { playName: "BENCH CORNER STOP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRAGON SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB WHAM", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FLY SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SWITCH X COMEBACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Singleback Toad X Nasty",
      formationType: "Singleback",
      plays: [
        { playName: "DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MID ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER G", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB MISDIRECTION", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SLASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA BOOT RT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA BOOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA SLOT OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POST DIG", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER G BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER G DRIVE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Singleback Wing Pair",
      formationType: "Singleback",
      plays: [
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER G", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET 6 DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA BOOT HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT RT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT TE LEAK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA TE SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE ATTACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TE DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WIDE ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Singleback Wing Slot",
      formationType: "Singleback",
      plays: [
        { playName: "DRAGON SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB ACE POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB ZONE ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA BOOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA Z SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN WIDE ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SAIL X POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA STRETCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA TE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y-DRAG WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Singleback Wing Tight",
      formationType: "Singleback",
      plays: [
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BELLY WEAK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA FL STRETCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA MILLS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA TE CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER ALERT X LOOKIE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QUICK SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Singleback Y Trips",
      formationType: "Singleback",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MID ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER G", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB PUMP DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE WK ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PA SLOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "JET PA SPRINT RT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT RT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CORNER POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DRAW SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA STRETCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y-SEAM CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "I Form Pro",
      formationType: "I Form",
      plays: [
        { playName: "COMEBACKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DUO ALERT X LOOKIE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB LEAD DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH ALERT X LOOKIE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB TOSS CRACK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ISO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA COMEBACK SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA COUNTER BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DRAW SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FL HITCH", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA LEAD DRAW SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y-POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "I Form Slot",
      formationType: "I Form",
      plays: [
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DUO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB LEAD DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET LEAD ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA X DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y THROWBACK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POST WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SAIL Y SHAKE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WEAK FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y COP SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "I Form Tight",
      formationType: "I Form",
      plays: [
        { playName: "GOAL LINE FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "I Form Wing Over",
      formationType: "I Form",
      plays: [
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB LEAD", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT FLOW", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SHIFT HB INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT PA U CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
      ],
    },
    {
      formation: "Strong Slot",
      formationType: "Strong",
      plays: [
        { playName: "BUBBLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "CHINA SPECIAL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MILLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA COUNTER BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POST SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
      ],
    },
    {
      formation: "Weak Pro",
      formationType: "Weak",
      plays: [
        { playName: "94 WILL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER F ALERT X SMOKE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB GUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT LT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA F SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Power I Hulk",
      formationType: "Power I",
      plays: [
        { playName: "DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB LEAD DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA FB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT RT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Power I Strong",
      formationType: "Power I",
      plays: [
        { playName: "AGAP POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DBL LEAD", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MISDIRECTION", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA FB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA LOOCH SPECIAL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT HB BLAST", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHIFT PA FB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "X SLANT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Ace Double Wing",
      formationType: "Pistol",
      plays: [
        { playName: "HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLAM", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CTR WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SPLIT ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WIDE ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Strong I Wing",
      formationType: "Pistol",
      plays: [
        { playName: "HB COUNTER EXTRA", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH ALERT X LOOKIE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB ZONE WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT LT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPACING WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Y Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICAL TE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Bunch",
      formationType: "Gun",
      plays: [
        { playName: "518 HOOK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BENCH PIVOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUNCH TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "COUNTER Y", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CROSS HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP ATTACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIG RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MID ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OUTS TE HOOK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SLOT HOOK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPACING SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "TRAIL Z POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Bunch Spread Nasty",
      formationType: "Gun",
      plays: [
        { playName: "BRANCH RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CORNER DIVIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH TRAFFIC", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN CROSS HB CHOICE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB UNDER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN JET PULL SHALLOW", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SLOT OVER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SPOT Y RETURN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT BUNCH SALEM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT SMASH WHIP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SEAM DIVIDE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOCK HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED DIG OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SWIRL CHOICE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SWIRL IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Doubles Offset",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FL SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HOOK Z POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA COMEBACK SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE ALERT GLANCE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SEAM HB ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLANT FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Empty Base Flex",
      formationType: "Gun",
      plays: [
        { playName: "LEVELS SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MIDDLE HI LO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Y-Flex",
      formationType: "Gun",
      plays: [
        { playName: "DEEP CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SEAMS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA DRAG", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SEAMS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SMASH CORNERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Tight",
      formationType: "Gun",
      plays: [
        { playName: "BENCH SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLANKER DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FRISCO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLOT CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trey Open",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA WR IN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trio Y-Flex",
      formationType: "Gun",
      plays: [
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DASH FLOOD SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH WHIPS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHOCK H OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Y Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURLS COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEVELS SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA POST SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA UNDER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QUICK FORK ZIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QUICK SHORT POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QUICK UNDERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO BASE ALERT LOOKIE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHOCK H OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLOT 2 BUC", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAIL MARY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
