import { TeamPlaybookSeed } from '../types';

export const CFB27_NORTHWESTERN_SEED: TeamPlaybookSeed = {
  team: "Northwestern",
  scheme: "Spread",
  sideOfBall: 'offense',
  gameVersion: 'cfb27',
  source: {
    url: "https://cfb.fan/playbooks/northwestern-off/",
    verified: "2026-06-30",
  },
  formations: [
    {
      formation: "Singleback Bunch TE",
      formationType: "Singleback",
      plays: [
        { playName: "CROSS DRAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB MISDIRECTION LEAD", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRETCH ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Singleback Wing X Off Close",
      formationType: "Singleback",
      plays: [
        { playName: "HB DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET HB DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "JET SPLIT ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA BOOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA Z SLIDE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN WIDE ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT RT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT Y LEAK", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SPLIT ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Pistol Double Stack",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "STACK OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Spread",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS STR", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA WHEELIE CURLS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WHEELIES", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Spread Y Slot",
      formationType: "Pistol",
      plays: [
        { playName: "FADE SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FOUR VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STRETCH", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA SPLIT FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT HITCHES", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT SPLIT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE FIN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Pistol Wing X Off Close",
      formationType: "Pistol",
      plays: [
        { playName: "JET HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA BOOT RT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WIDE ZONE WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun 5WR Flex Trey",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SCREENS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "DOUBLE SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DRIVE SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DUAL MID SCREENS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "EMPTY STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HITCH CORNERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JAILBREAK SLOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "QB ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHARK WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK N NOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR COMEBACKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun 5WR Trio",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLATS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE PIVOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD SWITCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HITCH CORNERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INVERTED MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN MESH Y-POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "QB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOCK SLOT OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WHIPS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WHIPS CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR SCREENS", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Box HB Strong",
      formationType: "Gun",
      plays: [
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH RAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "SIT Z DRAG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WHIP Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Box Offset Wk",
      formationType: "Gun",
      plays: [
        { playName: "HB DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN CURLS HB ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN VERTS HB ANGLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SCAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y CROSS POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Bunch Str Offset",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FK TOSS LEAD SWING DIG", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FK TOSS SLIDE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEAD SWING SPOT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN DEEP POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PIN PULL TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLANT SPACING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y TRAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Double Stack",
      formationType: "Gun",
      plays: [
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT TRAP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ FL SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMASH HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SMOKE N GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Doubles Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FK FL SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FL SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "FLANKER DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "ORBIT PA HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "ORBIT PA Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "ORBIT RPO ALERT SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA CROSS X POCO", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA GO SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "QB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB WRAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPOT DBL SLANTS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z CLOSE MTN CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z CLOSE MTN LEVELS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Z CLOSE MTN MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Doubles Flex Wk",
      formationType: "Gun",
      plays: [
        { playName: "MTN FL SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN HB COUNTER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB CROSS SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "MTN HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN MESH Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA RETURN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA Y MIDDLE READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO ALERT POWER", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN RPO ALERT RETURN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SLOT POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Doubles HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "BASH OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BOOMERANG 0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BOOMERANG SLOT SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BOOMERANG Y DELAY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BUCK SWEEP READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MIDLINE READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA MIDDLE READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA POWER CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA VERTS HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Z POCO", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PIN PULL SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PORTLAND MESH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT BUCK SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT MTN SWING", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUCK BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WIDE ZONE READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Doubles Offset Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA Y CORNER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN PA Z OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN RPO READ FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "ORBIT FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "ORBIT PA X SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DIGS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK BUCK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK ORBIT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "STACK PA Y MIDDLE READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "STACK RPO ALERT ZONE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "STACK RPO READ SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "STRIKE HB SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Normal Y Off Close",
      formationType: "Gun",
      plays: [
        { playName: "HB SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO ALERT ZONE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN SNAG CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN TE MIDDLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA JET SWEEP", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SHOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SNAG", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT OUT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO GLANCE POST", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SPOT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y-SAIL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Spread Y-Flex Wk",
      formationType: "Gun",
      plays: [
        { playName: "DOUBLE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN BENCH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN BENCH CURLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA FLOOD", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO READ FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN SPOT Y SEAM", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN X REPLACE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN Y STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SWITCH SEAM", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO POWER PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "X REPLACE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Spread Y-Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "CAKE READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CNTR READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURL COMBO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "G TRAP READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "H SHALLOW CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SCISSORS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MIDLINE READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA INVERTED VEER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB WRAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "TTRAP READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "VERT COMEBACKS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "X DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Tackle Over Cluster",
      formationType: "Gun",
      plays: [
        { playName: "BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BUCK SWEEP READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ALERT BUCK FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT SPOT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Tackle Over Trips",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "HB POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WHIP MILLS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUCK SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PEEK Y POP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUCK BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ X SMOKE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Trio HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "BUCK SWEEP READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DAGGER SIT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA CROSS SIT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ALERT BUCK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO BUCK PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO PIN ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUCK BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "WIDE ZONE READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Trio Y-Flex",
      formationType: "Gun",
      plays: [
        { playName: "BUCKEYE FLOOD", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH DAGGER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH WHIPS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MILLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN MILLS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN SHOCK SLOT DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHOCK H OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "SLOT OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Trips HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CHOICE ZIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL FLAT CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "CURL SLOT DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DBL COMEBACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DEEP FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "DOUBLE SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "FLOOD SWITCH FADE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MESH WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA QB CHOICE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WR MID SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Trips Y Over",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JAILBREAK SLOT SCREEN", isNewIn26: false, isNewIn27: false, playType: "Screen" },
        { playName: "PA BUCKEYE DAGGER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RETURN SPRINT HB THROWBACK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RETURN SPRINT SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RETURN SPRINT SPOT WHIP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO ZONE ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun U Off Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER SIT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB POWER", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "LEVELS OUT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN FADE SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN VERTICALS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "PA BOOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BOOT CORNER-POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO PEEK CORNER", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPOT QUADS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUCK SWEEP READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB COUNTER U", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MESH HB CORNER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MIDLINE READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN PA CROSS", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA INVERTED VEER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB WRAP", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO PEEK BUCK SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO SWEEP ALERT BUBBLE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SMASH", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "TE LEAD READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Gun Wing Trio",
      formationType: "Gun",
      plays: [
        { playName: "DASH CURL FLAT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "GT READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN DRIVE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN WHIP DEEP FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT MESH HB SWING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ORBIT RPO PEEK Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "PA ALL CURL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SLOT CORNER-POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA X CORNER", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER READ TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "RPO PEEK Y POP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE ALERT SCREEN", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO ZONE PEEK", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RZ ORBIT CROSSERS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "WIDE TRAP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Y FLOOD", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "ALL IN", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "BUCK SWEEP", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "BUCK SWEEP READ OPT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "DIY BUCK SWEEP REVERSE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB BASE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB MID DRAW", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "MTN CROSS Z POCO", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN DASH HITCH OVER", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN HB OFF TACKLE", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "MTN PA WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "MTN RPO READ Y FLAT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "MTN WHEEL SPOT", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA DEEP SAIL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA Y WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "RPO ALERT SLANT", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "RPO BUCK ALERT SMOKE", isNewIn26: false, isNewIn27: false, playType: "RPO" },
        { playName: "SHOT Y WHEEL", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SLOT CROSS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "STICK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "Z DIG", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
    {
      formation: "Gun Wing X Off",
      formationType: "Gun",
      plays: [
        { playName: "JET DUO", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET INSIDE ZONE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "JET PA BOOT HB WHEEL", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "JET PA DOUBLE POST", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "JET TOUCH PASS", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "RPO PEEK JET POP", isNewIn26: false, isNewIn27: false, playType: "RPO" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE WEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB DIVE", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "HB SPLIT 0", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HB STING", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "PA POWER O", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, isNewIn27: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "QB SNEAK", isNewIn26: false, isNewIn27: false, playType: "Run" },
        { playName: "STRONG TOSS", isNewIn26: false, isNewIn27: false, playType: "Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "HAIL MARY", isNewIn26: false, isNewIn27: false, playType: "Pass" },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false, isNewIn27: false, playType: "Pass" },
      ],
    },
  ],
};
