import type { TeamPlaybookSeed } from "../types";

export const GEORGIA_SEED: TeamPlaybookSeed = {
  team: "Georgia",
  scheme: "Pro Style",
  sideOfBall: 'offense',
  source: {
    url: "https://cfb.fan/26/playbooks/georgia-off/",
    verified: "2026-04-16",
  },
  formations: [
    {
      formation: "Singleback Bunch Ace",
      formationType: "Singleback",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "DRIVE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DUO", isNewIn26: false, playType: "Inside Run" },
        { playName: "END AROUND LEAD", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SLAM", isNewIn26: false },
        { playName: "HB SLASH", isNewIn26: false },
        { playName: "HB SLASH FK END ARND", isNewIn26: false },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "OVER HB TOSS", isNewIn26: true, playType: "Outside Run" },
        { playName: "OVER TOSS FK REVERSE", isNewIn26: true, playType: "Outside Run" },
        { playName: "OVER TOSS WR REVERSE", isNewIn26: true, playType: "Outside Run" },
        { playName: "PA BOOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "PA CROSS SWITCH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA END AROUND", isNewIn26: false, playType: "Play Action" },
        { playName: "PA FORK SHOT", isNewIn26: false, playType: "Play Action" },
        { playName: "QUICK PITCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "SPACING SWITCH", isNewIn26: false },
        { playName: "TE ANGLE", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Singleback Deuce Close",
      formationType: "Singleback",
      plays: [
        { playName: "BENCH", isNewIn26: false },
        { playName: "CORNER STOPS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA BOOT CORNER POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "PA DEEP READ", isNewIn26: false, playType: "Deep Pass" },
        { playName: "PA SLIDE YSCREEN", isNewIn26: false, playType: "Play Action" },
        { playName: "PA X DEEP OUT", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SPACING SWITCH", isNewIn26: false },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "ZONE SPLIT WK", isNewIn26: false },
      ],
    },
    {
      formation: "Singleback Y Off Trips",
      formationType: "Singleback",
      plays: [
        { playName: "CHINA UNDER", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "CURLS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "OFF TACKLE", isNewIn26: false },
        { playName: "PA BOOT RT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA BOOT RT PIVOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA BOOT SMASH", isNewIn26: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA SLOT CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA VERTICALS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SE CURL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Pistol Y Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "COUNTER Y", isNewIn26: true },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB POWER G", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SWING", isNewIn26: true, playType: "Screen" },
        { playName: "HB WIDE ZONE WK", isNewIn26: false },
        { playName: "HB ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "LEAD SWING DBL SPOT", isNewIn26: true, playType: "Inside Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "PA DOUBLE POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Bunch",
      formationType: "Gun",
      plays: [
        { playName: "BENCH PIVOT", isNewIn26: false },
        { playName: "BUNCH TRAIL", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DIG RETURN", isNewIn26: false, playType: "Medium Pass" },
        { playName: "FAKE REVERSE", isNewIn26: false },
        { playName: "FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "GL MTN X SLANT", isNewIn26: true, playType: "Quick Pass" },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "HB SWEEP", isNewIn26: false, playType: "Outside Run" },
        { playName: "MESH SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "MTN CROSS SWITCH", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN CURLS", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN PA CROSS SWITCH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN PA SAIL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN RPO ALERT BUBBLE", isNewIn26: false, playType: "Screen" },
        { playName: "PA POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "REVERSE", isNewIn26: false },
        { playName: "SMASH RETURN", isNewIn26: false },
        { playName: "SPACING SWITCH", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "Z SPOT N GO", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Bunch Y-Flex",
      formationType: "Gun",
      plays: [
        { playName: "83 HB CHOICE", isNewIn26: false },
        { playName: "BRANCH RETURN", isNewIn26: false },
        { playName: "CURLS Y SWIRL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DAGGER", isNewIn26: false },
        { playName: "DIG RETURN", isNewIn26: false, playType: "Medium Pass" },
        { playName: "FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET PULL SHALLOW", isNewIn26: false, playType: "Medium Pass" },
        { playName: "RPO ALERT OUT", isNewIn26: false, playType: "RPO" },
        { playName: "SMASH RETURN", isNewIn26: false },
        { playName: "SPACING", isNewIn26: false },
        { playName: "SPEED DIG", isNewIn26: false, playType: "Medium Pass" },
        { playName: "VERTICALS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "Z SPOT", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Cluster HB Str",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, playType: "Quick Pass" },
        { playName: "FLANKER DRIVE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "MESH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN CROSS SWITCH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN SLOT SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "POST DIG", isNewIn26: false, playType: "Medium Pass" },
        { playName: "SPACING", isNewIn26: false },
        { playName: "SPOT LEAD SWING", isNewIn26: false, playType: "Inside Run" },
        { playName: "VERTICALS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "Z SPOT", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Deuce Close",
      formationType: "Gun",
      plays: [
        { playName: "BENCH DIG CURL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "BENCH SWAP", isNewIn26: false },
        { playName: "CORNER N GOS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB SWING", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, playType: "Inside Run" },
        { playName: "MESH DOUBLE WHEEL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MESH SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "PA DEEP OVER", isNewIn26: false, playType: "Deep Pass" },
        { playName: "RPO PEEK STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "RPO READ FLAT WHEEL", isNewIn26: false, playType: "Quick Pass" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SPACING SWITCH", isNewIn26: false },
        { playName: "X SHALLOW CROSS", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Doubles Offset",
      formationType: "Gun",
      plays: [
        { playName: "BUCK SWEEP", isNewIn26: false, playType: "Outside Run" },
        { playName: "COUNTER TREY", isNewIn26: false },
        { playName: "FADE SMASH", isNewIn26: false, playType: "Deep Pass" },
        { playName: "FL SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA COMEBACK SEAM", isNewIn26: false, playType: "Deep Pass" },
        { playName: "PA GO DIG POST", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA GO SLOT CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA JET SWEEP", isNewIn26: false, playType: "Outside Run" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO ZONE X SMOKE", isNewIn26: false, playType: "RPO" },
        { playName: "SHARK HB WHEEL", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "X DAGGER", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Empty Y Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL HITCH", isNewIn26: false, playType: "Quick Pass" },
        { playName: "CORNER STRIKE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CURL FLATS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "DOUBLE UNDERS", isNewIn26: false },
        { playName: "INSIDE CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "ORBIT FK SCREEN WHEEL", isNewIn26: false, playType: "Screen" },
        { playName: "ORBIT SPOT Y CORNER", isNewIn26: false, playType: "Quick Pass" },
        { playName: "ORBIT TE MID SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "ORBIT VERTICALS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "ORBIT WR SWING", isNewIn26: false, playType: "Screen" },
        { playName: "ORBIT Y CORNER", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SLOT DRIVE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "STICK N NOD", isNewIn26: false, playType: "Quick Pass" },
        { playName: "VERTICALS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "WR SCREENS", isNewIn26: false, playType: "Screen" },
        { playName: "Y CORNER", isNewIn26: false, playType: "Deep Pass" },
        { playName: "Y POST WHEEL", isNewIn26: false, playType: "Deep Pass" },
      ],
    },
    {
      formation: "Gun Normal Y Off",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, playType: "Quick Pass" },
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CURL COMBO", isNewIn26: false, playType: "Medium Pass" },
        { playName: "CURLS LEAD SWING", isNewIn26: false, playType: "Inside Run" },
        { playName: "DBL DIG", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MTN CURL N GO", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN CURLS", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN HB OFF TACKLE", isNewIn26: true },
        { playName: "MTN INSIDE ZONE", isNewIn26: true, playType: "Inside Run" },
        { playName: "MTN PA SEAM WHEEL", isNewIn26: false, playType: "Deep Pass" },
        { playName: "MTN PA VERTICALS", isNewIn26: true, playType: "Deep Pass" },
        { playName: "MTN PA WHEEL SHOT", isNewIn26: false },
        { playName: "MTN RPO READ Y FLAT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "MTN SCISSORS", isNewIn26: true },
        { playName: "PA DEEP SAIL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA JET SWEEP", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA SHALLOW CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "Y CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "Z CORNER", isNewIn26: false, playType: "Deep Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Normal Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN HB CROSS SCREEN", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN PA FK SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "MTN RPO ALERT SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "PIVOT IN SEAMS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "RPO GLANCE SLANT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, playType: "Screen" },
        { playName: "RPO SPLIT ALERT BUBBLE", isNewIn26: false, playType: "Screen" },
        { playName: "SHALLOW CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "SLOT HOOKS", isNewIn26: false },
        { playName: "SLUGGO SEAM", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
        { playName: "WR UNDER", isNewIn26: false },
        { playName: "X DAGGER", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Spread Flex Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DIG H SEAM", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DOUBLE POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DOUBLE SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "H MTN FOUR VERTICALS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "H MTN Y STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "H MTN Z SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "H SHALLOW CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN SWING SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "MTN Y SHALLOW CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN Z SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "PA DAGGER", isNewIn26: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SLOT FADES", isNewIn26: false, playType: "Deep Pass" },
      ],
    },
    {
      formation: "Gun Spread Y-Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DOUBLE INS", isNewIn26: false },
        { playName: "DRIVE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, playType: "Deep Pass" },
        { playName: "FAKE JET MESH WHEEL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "H SHALLOW CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB QUICK BASE", isNewIn26: false, playType: "Quick Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MTN FK SCREEN WHEEL", isNewIn26: false, playType: "Screen" },
        { playName: "MTN FL SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "MTN HB CROSS SCREEN", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA SEAMS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "WR SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "Y CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "Y SAIL", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Trey Open HB Str",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DBL INS", isNewIn26: false },
        { playName: "H MTN MESH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "H MTN MESH POST", isNewIn26: false, playType: "Medium Pass" },
        { playName: "H MTN MESH WHEEL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "LEVELS SWITCH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO PEEK BUBBLE", isNewIn26: false, playType: "Screen" },
        { playName: "RPO PEEK HITCH", isNewIn26: false, playType: "Quick Pass" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SCISSORS", isNewIn26: false },
        { playName: "SHOCK Y CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "SHORT CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "SLOT FADE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Trey Open Offset",
      formationType: "Gun",
      plays: [
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "LEVELS SWITCH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, playType: "Screen" },
        { playName: "MTN INSIDE CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN TE MID SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "REDZONE UNDER", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SHOCK H OPTION", isNewIn26: false, playType: "Option" },
        { playName: "STRONG CURL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "TRAIL SHAKE", isNewIn26: false },
        { playName: "VERTS HB ANGLE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "Y CORNER", isNewIn26: false, playType: "Deep Pass" },
        { playName: "Y CROSS FLOOD", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Trio",
      formationType: "Gun",
      plays: [
        { playName: "FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB OFF TACKLE", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "INSIDE SMASH", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET HB OFF TACKLE", isNewIn26: true },
        { playName: "JET PA HB WHEEL", isNewIn26: true },
        { playName: "JET TOUCH PASS", isNewIn26: true },
        { playName: "PA DEEP ATTACK", isNewIn26: false, playType: "Deep Pass" },
        { playName: "PA SLOT CORNER", isNewIn26: false, playType: "Deep Pass" },
        { playName: "PA VERTICALS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, playType: "Screen" },
        { playName: "RPO ALERT WR SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "VERTICALS", isNewIn26: false, playType: "Deep Pass" },
      ],
    },
    {
      formation: "Gun Trips TE Offset Wk",
      formationType: "Gun",
      plays: [
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, playType: "Screen" },
        { playName: "FLOOD DIVIDE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB POWER", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MIDDLE SLANT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "PA FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "READ Y CORNER", isNewIn26: false, playType: "Deep Pass" },
        { playName: "RETURN PA DEEP SAIL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "RETURN POST CURL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "RETURN RPO ALERT SWING", isNewIn26: false, playType: "Screen" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, playType: "Screen" },
        { playName: "RPO READ WR SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "VERTICALS", isNewIn26: false, playType: "Deep Pass" },
      ],
    },
    {
      formation: "Gun Wing Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DOUBLE POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DRIVE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "HB COUNTER U", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MESH HB CORNER", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN FK SCREEN WHEEL", isNewIn26: false, playType: "Screen" },
        { playName: "MTN INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN PA VERTICALS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "MTN READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MTN RPO ALERT SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "MTN RPO BUCK ALERT", isNewIn26: false, playType: "RPO" },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false, playType: "Play Action" },
        { playName: "PA DAGGER", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO ZONE ALERT BUBBLE", isNewIn26: false, playType: "Screen" },
        { playName: "SMASH", isNewIn26: false },
        { playName: "TE LEAD READ OPT", isNewIn26: false, playType: "Inside Run" },
      ],
    },
    {
      formation: "Gun Wing Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "EXIT PA WHEEL CURLS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "EXIT PA WHEEL SHOT", isNewIn26: false },
        { playName: "HB CROSS SCREEN", isNewIn26: false, playType: "Medium Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN HB SLIP SCREEN", isNewIn26: true, playType: "Screen" },
        { playName: "MTN SMASH LEVELS", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN Z UNDER", isNewIn26: true },
        { playName: "PA CROSS SWITCH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "POST-CURL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "RETURN PA FK SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "RETURN PA Y ANGLE", isNewIn26: false },
        { playName: "RETURN RPO ALERT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO ALERT OUT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO BUBBLE Y POP", isNewIn26: false, playType: "Screen" },
        { playName: "RPO READ SNAG", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: true, playType: "Quick Pass" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "STICK N NOD", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Wing Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "ALL IN", isNewIn26: false },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "MTN PA CROSS SWITCH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN PA WHEEL", isNewIn26: false },
        { playName: "MTN RPO ALERT", isNewIn26: false, playType: "RPO" },
        { playName: "MTN RPO READ Y FLAT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "MTN WHEEL SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "PA DEEP SAIL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "PA Y WHEEL", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO ALERT SLANT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "RPO BUCK ALERT SMOKE", isNewIn26: false, playType: "RPO" },
        { playName: "SHOT Y WHEEL", isNewIn26: false },
        { playName: "SLOT CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: true, playType: "Inside Run" },
        { playName: "Z DIG", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "CURLS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "FLOOD HB SWING", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "HB ZONE TOSS", isNewIn26: true, playType: "Outside Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "LEAD SWING ALL CURL", isNewIn26: true, playType: "Inside Run" },
        { playName: "MTN STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "MTN STICK N NOD", isNewIn26: false, playType: "Quick Pass" },
        { playName: "MTN Y SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "PA DOUBLE POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "PA READ SMASH", isNewIn26: false, playType: "Play Action" },
        { playName: "PA Y FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "PA ZONE SHOT", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO GLANCE POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "TE MID SCREEN", isNewIn26: true, playType: "Screen" },
        { playName: "VERTICALS Y OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB COUNTER WK", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SPLIT O", isNewIn26: false },
        { playName: "HB STING", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "PA WAGGLE", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "QB SNEAK", isNewIn26: false, playType: "QB Run" },
        { playName: "STRONG TOSS", isNewIn26: false, playType: "Outside Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HAIL MARY", isNewIn26: false },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false },
      ],
    },
  ],
};
