import type { TeamPlaybookSeed } from "../types";

export const JAMES_MADISON_SEED: TeamPlaybookSeed = {
  team: "James Madison",
  scheme: "Spread",
  sideOfBall: 'offense',
  source: {
    url: "https://cfb.fan/26/playbooks/james-madison-off/",
    verified: "2026-05-02",
  },
  formations: [
    {
      formation: "Tight",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER LEAD", isNewIn26: false },
        { playName: "CURL Y CORNER", isNewIn26: false },
        { playName: "HB SLAM", isNewIn26: false },
        { playName: "HB SWEEP", isNewIn26: false },
        { playName: "PA CTR WAGGLE", isNewIn26: false },
        { playName: "PA DIG WHEELS", isNewIn26: false },
        { playName: "PA POST", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false },
        { playName: "POWER O", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Bunch Open Offset",
      formationType: "Gun",
      plays: [
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "RELOAD INSIDE ZONE", isNewIn26: false },
        { playName: "RELOAD SPACING SWITCH", isNewIn26: false },
        { playName: "RELOAD Z SHALLOW CROSS", isNewIn26: false },
        { playName: "RPO ALERT OUT", isNewIn26: false },
        { playName: "RPO PEEK WR SCREEN", isNewIn26: false },
        { playName: "SPRINT Z SPOT", isNewIn26: false },
        { playName: "Y TRAIL", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Deuce",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false },
        { playName: "ALL GO", isNewIn26: false },
        { playName: "BENCH SWAP", isNewIn26: false },
        { playName: "BOUNCE INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "BOUNCE OUTSIDE ZONE", isNewIn26: false },
        { playName: "BOUNCE PA TE CROSS", isNewIn26: false },
        { playName: "CHIP POCO X DIG", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "DIY TOSS REVERSE", isNewIn26: false },
        { playName: "FK TOSS", isNewIn26: false },
        { playName: "HB TOSS", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "LEAD READ OPTION", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "PA SHALLOW CROSS", isNewIn26: false },
        { playName: "PA SLIDE", isNewIn26: false },
        { playName: "RPO READ FLAT WHEEL", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Double Stack",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "FAKE SCREEN GO", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false },
        { playName: "RPO ALERT SCREEN", isNewIn26: false },
        { playName: "RPO ALERT TRAP", isNewIn26: false },
        { playName: "RPO READ FL SCREEN", isNewIn26: false },
        { playName: "SMOKE N GO", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Doubles HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "DOUBLE POST", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MILLS", isNewIn26: false },
        { playName: "MTN BUCK SWEEP", isNewIn26: false },
        { playName: "MTN DRAG CORNER STRIKE", isNewIn26: false },
        { playName: "MTN HB SLIP SCREEN", isNewIn26: false },
        { playName: "MTN PA CROSS", isNewIn26: false },
        { playName: "MTN PA WHEEL POSTS", isNewIn26: false },
        { playName: "MTN RPO POWER PEEK", isNewIn26: false },
        { playName: "MTN SPRINT SWITCH SAIL", isNewIn26: false },
        { playName: "MTN STICK", isNewIn26: false },
        { playName: "PA CROSS", isNewIn26: false },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false },
        { playName: "PA JAILBREAK SLOT", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO ALERT MTN SWING", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "TUNNEL HB FLARE", isNewIn26: false },
        { playName: "X DAGGER", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Doubles Offset",
      formationType: "Gun",
      plays: [
        { playName: "FADE SMASH", isNewIn26: false },
        { playName: "FAKE JET HB SEAM", isNewIn26: false },
        { playName: "HB PUNCH", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "MTN HB SLIP SCREEN", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA COMEBACK SEAM", isNewIn26: false },
        { playName: "PA GO DIG POST", isNewIn26: false },
        { playName: "PA GO SLOT CROSS", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "SALEM X KITTY", isNewIn26: false },
        { playName: "SHARK HB WHEEL", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "SMASH PIVOT", isNewIn26: false },
        { playName: "SPOT DBL SLANT", isNewIn26: false },
        { playName: "TEXAS DOUBLE POST", isNewIn26: false },
        { playName: "X DAGGER", isNewIn26: false },
        { playName: "Y SHALLOW CROSS", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Doubles Y Off",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "CROSSERS", isNewIn26: false },
        { playName: "CURL OHIO", isNewIn26: false },
        { playName: "FADE STOP", isNewIn26: false },
        { playName: "FAKE JET HB SEAM", isNewIn26: false },
        { playName: "HB MTN FK SCREEN WHEEL", isNewIn26: false },
        { playName: "HB MTN QB BLAST", isNewIn26: false },
        { playName: "HB MTN WR SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MTN HB BASE", isNewIn26: false },
        { playName: "MTN HB SWING", isNewIn26: false },
        { playName: "MTN PA WHEEL", isNewIn26: false },
        { playName: "MTN PA Y SCREEN", isNewIn26: false },
        { playName: "MTN SAIL", isNewIn26: false },
        { playName: "MTN STICK", isNewIn26: false },
        { playName: "PA GO SLOT CROSS", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT WR SCREEN", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "VERT COMEBACKS", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Doubles Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "BOUNCE INSIDE ZONE", isNewIn26: false },
        { playName: "BOUNCE PA DAGGER", isNewIn26: false },
        { playName: "BOUNCE RPO GLANCE DUO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "CURL FLAT", isNewIn26: false },
        { playName: "DOUBLE POST", isNewIn26: false },
        { playName: "DOUBLE SLANTS", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "LEAD READ OPTION", isNewIn26: false },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "MTN PA WHEEL", isNewIn26: false },
        { playName: "MTN RPO READ Y FLAT", isNewIn26: false },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO GLANCE POST", isNewIn26: false },
        { playName: "RPO GLANCE SLANT", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "X DAGGER", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Empty Quads",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "OUT DOUBLE UNDER", isNewIn26: false },
        { playName: "QB BLAST", isNewIn26: false },
        { playName: "QB DRAW", isNewIn26: false },
        { playName: "VERT DOUBLE UNDER", isNewIn26: false },
        { playName: "WR SCREEN", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Empty Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "CURLS Y SHAKE", isNewIn26: false },
        { playName: "DBL SLOT CROSS", isNewIn26: false },
        { playName: "FOUR VERTICALS", isNewIn26: false },
        { playName: "JET QB COUNTER", isNewIn26: false },
        { playName: "JET QB POWER", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "PA JET FLOOD", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
        { playName: "PA JET SWEEP SHOT", isNewIn26: false },
        { playName: "QB ZONE", isNewIn26: false },
        { playName: "RPO ALERT QB COUNTER", isNewIn26: false },
        { playName: "RZ DUSTY", isNewIn26: false },
        { playName: "VERTS SLOT OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Split Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "MTN DOUBLE PASS", isNewIn26: false },
        { playName: "MTN INSIDE ZONE", isNewIn26: false },
        { playName: "MTN PA DOUBLE POSTS", isNewIn26: false },
        { playName: "MTN PA STUTTER GO", isNewIn26: false },
        { playName: "MTN PA Y CROSS", isNewIn26: false },
        { playName: "MTN RPO PEEK SWING", isNewIn26: false },
        { playName: "MTN SPOT", isNewIn26: false },
        { playName: "MTN TRIPLE OPTION RT", isNewIn26: false },
        { playName: "MTN Y CROSS", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Spread Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "DEEP ATTACK", isNewIn26: false },
        { playName: "DEEP CURL", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE CROSS", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA DIG", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "QUICK SLANTS", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "SLOT FLAGS", isNewIn26: false },
        { playName: "SMASH CORNERS", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "WR MID SCREEN", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trio Unbalanced",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false },
        { playName: "HB SWING", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "PA FK BUBBLE WHEEL", isNewIn26: false },
        { playName: "QB ZONE", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ZONE ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO ZONE ALERT SCREEN", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "VERTICALS", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CURLS", isNewIn26: false },
        { playName: "DEEP STICK", isNewIn26: false },
        { playName: "DRIVE", isNewIn26: false },
        { playName: "HB DIRECT", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE SWITCH", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "LEVELS", isNewIn26: false },
        { playName: "MIDDLE SLAM", isNewIn26: false },
        { playName: "OHIO SAIL", isNewIn26: false },
        { playName: "PA WR IN", isNewIn26: false },
        { playName: "QUICK SLANTS", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "SHOCK H OPTION", isNewIn26: false },
        { playName: "WR MID SCREEN", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips Off Over Wk",
      formationType: "Gun",
      plays: [
        { playName: "HB CROSS SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "RPO ALERT BUCK", isNewIn26: false },
        { playName: "RPO ALERT SPLIT BUBBLE", isNewIn26: false },
        { playName: "RPO ALERT SPLIT SCREEN", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "RPO READ Y FLAT", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips TE Flex",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "LEVELS SAIL", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "OVER PIVOT", isNewIn26: false },
        { playName: "PA CROSSERS", isNewIn26: false },
        { playName: "PA FORK", isNewIn26: false },
        { playName: "POST RAIL", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ZONE ALERT OMAHA", isNewIn26: false },
        { playName: "SCAT", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "TE IN", isNewIn26: false },
        { playName: "VERTICALS", isNewIn26: false },
        { playName: "Y CORNER STOP", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips TE Offset",
      formationType: "Gun",
      plays: [
        { playName: "CURL COMBO", isNewIn26: false },
        { playName: "DUKES BUBBLE FLOOD", isNewIn26: false },
        { playName: "FLOOD", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "LEVELS SAIL", isNewIn26: false },
        { playName: "PA CROSSERS", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO TRAP ALERT BUBBLE", isNewIn26: false },
        { playName: "SCAT", isNewIn26: false },
        { playName: "SHOCK H OPTION", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "TE IN", isNewIn26: false },
        { playName: "VERTICALS", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips TE Offset Wk",
      formationType: "Gun",
      plays: [
        { playName: "BUCK SWEEP", isNewIn26: false },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false },
        { playName: "FLOOD DIVIDE", isNewIn26: false },
        { playName: "HB POWER", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MIDDLE SLANT", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA DEEP SAIL", isNewIn26: false },
        { playName: "PA FLOOD", isNewIn26: false },
        { playName: "PA VERTS SHOT", isNewIn26: false },
        { playName: "READ Y CORNER", isNewIn26: false },
        { playName: "RPO BUCK PEEK", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "RPO READ BUBBLE", isNewIn26: false },
        { playName: "RPO READ WR SCREEN", isNewIn26: false },
        { playName: "RPO ZONE PEEK", isNewIn26: false },
        { playName: "VERTICALS", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips Y Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "CURLS", isNewIn26: false },
        { playName: "DEEP FLOOD", isNewIn26: false },
        { playName: "GL RUB RETURN", isNewIn26: false },
        { playName: "HANK", isNewIn26: false },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "HB OFF TACKLE", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MTN HB SWING", isNewIn26: false },
        { playName: "MTN LEAD SWING SPOT", isNewIn26: false },
        { playName: "MTN WHIP SLOT WHEEL", isNewIn26: false },
        { playName: "PA QB CHOICE", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RELOAD DAGGER", isNewIn26: false },
        { playName: "RELOAD HB SCREEN", isNewIn26: false },
        { playName: "RELOAD SLOT OUT", isNewIn26: false },
        { playName: "SHOCK", isNewIn26: false },
        { playName: "SPOT Y DIG", isNewIn26: false },
        { playName: "Y CROSS", isNewIn26: false },
      ],
    },
    {
      formation: "Gun U Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "DEEP POST CORNER", isNewIn26: false },
        { playName: "DUO WRAP", isNewIn26: false },
        { playName: "HB POWER", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "LEAD READ OPTION", isNewIn26: false },
        { playName: "PA POST SHOT", isNewIn26: false },
        { playName: "PA TE OUT", isNewIn26: false },
        { playName: "PA U CORNER FLOOD", isNewIn26: false },
        { playName: "POST WHEEL SHALLOW", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO ALERT X GIFT", isNewIn26: false },
        { playName: "RPO READ FLAT", isNewIn26: false },
        { playName: "SHOCK", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Flex Offset",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false },
        { playName: "ALL GO", isNewIn26: false },
        { playName: "DOUBLE CROSS", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "JAILBREAK SCREEN", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "MTN BENCH SPACING", isNewIn26: false },
        { playName: "MTN CROSS X POST", isNewIn26: false },
        { playName: "MTN DEEP FLOOD", isNewIn26: false },
        { playName: "MTN INSIDE ZONE", isNewIn26: false },
        { playName: "MTN JAILBREAK SCREEN", isNewIn26: false },
        { playName: "MTN RZ X POST", isNewIn26: false },
        { playName: "OHIO SPACING", isNewIn26: false },
        { playName: "PA DOUBLE POST", isNewIn26: false },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false },
        { playName: "PA SLIDE", isNewIn26: false },
        { playName: "POWER O", isNewIn26: false },
        { playName: "SLANTS Y STICK", isNewIn26: false },
        { playName: "STICK NOD VERTICAL", isNewIn26: false },
        { playName: "Y LEAD READ OPT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "DRAGON SPACING", isNewIn26: false },
        { playName: "DRIVE", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA DOUBLE POST", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "PA SLIDE", isNewIn26: false },
        { playName: "POWER O", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "SMASH", isNewIn26: false },
        { playName: "SPOT OPTION", isNewIn26: false },
        { playName: "STICK NOD VERTICAL", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Tight",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false },
        { playName: "ESCORT INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "ESCORT PA SLIDE", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "OHIO SPACING", isNewIn26: false },
        { playName: "PA DOUBLE POST", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RZ ESCORT PA CROSSERS", isNewIn26: false },
        { playName: "SLUGGO SEAM", isNewIn26: false },
        { playName: "STICK NOD VERTICAL", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Tight Z",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false },
        { playName: "DUO", isNewIn26: false },
        { playName: "GOAL LINE FADE", isNewIn26: false },
        { playName: "HB PUNCH", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "MTN INSIDE ZONE", isNewIn26: false },
        { playName: "MTN PA FLOOD", isNewIn26: false },
        { playName: "MTN POWER WK", isNewIn26: false },
        { playName: "PA FLANKER CURL", isNewIn26: false },
        { playName: "RPO GLANCE POST", isNewIn26: false },
        { playName: "ZONE OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "BOUNCE INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "BOUNCE OUTSIDE ZONE", isNewIn26: false },
        { playName: "BOUNCE PA DEEP OUT", isNewIn26: false },
        { playName: "DUO", isNewIn26: false },
        { playName: "HB MTN CROSS", isNewIn26: false },
        { playName: "HB MTN RPO QB ZONE", isNewIn26: false },
        { playName: "HB MTN SCREEN Y STICK", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "MIDDLE DIVIDE", isNewIn26: false },
        { playName: "PA DOUBLE POST", isNewIn26: false },
        { playName: "PA MTN SLIDE", isNewIn26: false },
        { playName: "RPO ALERT WR SCREEN", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "WHIP SMASH", isNewIn26: false },
        { playName: "Y LEAD READ OPT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Y Off Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "22 SHALLOW SAIL", isNewIn26: false },
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CROSS Z POST", isNewIn26: false },
        { playName: "HB POWER O", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "MTN CURLS", isNewIn26: false },
        { playName: "MTN FADE DAGGER", isNewIn26: false },
        { playName: "MTN HB SWING", isNewIn26: false },
        { playName: "MTN MIDDLE DIVIDE", isNewIn26: false },
        { playName: "MTN SLOT WHIP IN", isNewIn26: false },
        { playName: "MTN Z SPOT", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA MIDDLE DIVIDE", isNewIn26: false },
        { playName: "PA SLIDE", isNewIn26: false },
        { playName: "Q2Z IN", isNewIn26: false },
        { playName: "RPO GLANCE BUBBLE", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "STRONG FLOOD", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE", isNewIn26: false },
        { playName: "HB COUNTER WK", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB SPLIT O", isNewIn26: false },
        { playName: "HB STING", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false },
        { playName: "PA SPOT", isNewIn26: false },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false },
        { playName: "PA WAGGLE", isNewIn26: false },
        { playName: "POWER O", isNewIn26: false },
        { playName: "QB SNEAK", isNewIn26: false },
        { playName: "STRONG TOSS", isNewIn26: false },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false },
        { playName: "HAIL MARY", isNewIn26: false },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false },
      ],
    },
  ],
};
