import type { TeamPlaybookSeed } from "../types";

export const KANSAS_SEED: TeamPlaybookSeed = {
  team: "Kansas",
  scheme: "Spread",
  sideOfBall: 'offense',
  source: {
    url: "https://cfb.fan/26/playbooks/kansas-off/",
    verified: "2026-05-02",
  },
  formations: [
    {
      formation: "Wildcat U Off Trips",
      formationType: "Wildcat",
      plays: [
        { playName: "BLAST WK", isNewIn26: false },
        { playName: "DIY REVERSE", isNewIn26: false },
        { playName: "POWER", isNewIn26: false },
        { playName: "POWER EXTRA", isNewIn26: false },
        { playName: "QB WRAP", isNewIn26: false },
      ],
    },
    {
      formation: "Wildcat Wing Slot",
      formationType: "Wildcat",
      plays: [
        { playName: "LEAD", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "POWER G", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "WRAP", isNewIn26: false },
        { playName: "ZONE", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Deuce Close",
      formationType: "Pistol",
      plays: [
        { playName: "BENCH", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "HB SPLIT DIVE", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "PA BOOT Y LEAK", isNewIn26: false },
        { playName: "PA Z OVER", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Full Diamond",
      formationType: "Pistol",
      plays: [
        { playName: "ESCORT INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "ESCORT LEAD READ OPTION", isNewIn26: false },
        { playName: "ESCORT PA OUTS", isNewIn26: false },
        { playName: "HB DOUBLE ISO", isNewIn26: false },
        { playName: "PA Z POST", isNewIn26: false },
        { playName: "READ OPTION WK", isNewIn26: false },
        { playName: "RPO ALERT HITCHES", isNewIn26: false },
        { playName: "RPO READ FLAT WHEEL", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Strong",
      formationType: "Pistol",
      plays: [
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "PA BOOT LT", isNewIn26: false },
        { playName: "PA FLOOD", isNewIn26: false },
        { playName: "POWER OPTION", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "TR OPT SWITCH", isNewIn26: false },
        { playName: "TRIPLE OPTION", isNewIn26: false },
        { playName: "X POST", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Strong Slot Open",
      formationType: "Pistol",
      plays: [
        { playName: "DOUBLE SCREEN", isNewIn26: false },
        { playName: "F LEAD READ OPTION", isNewIn26: false },
        { playName: "FLAT COMBO", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "HB ZONE", isNewIn26: false },
        { playName: "ORBIT HB OFF TACKLE", isNewIn26: false },
        { playName: "ORBIT PA WHEEL", isNewIn26: false },
        { playName: "ORBIT TRIPLE OPTION", isNewIn26: false },
        { playName: "PA SLIDE", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "SHAKES", isNewIn26: false },
        { playName: "TRIPLE OPTION", isNewIn26: false },
        { playName: "UNDER", isNewIn26: false },
        { playName: "Y CROSS", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Wing Slot",
      formationType: "Pistol",
      plays: [
        { playName: "BENCH CORNER STRIKE", isNewIn26: false },
        { playName: "FOUR VERTICALS", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "JET PA HB WHEEL", isNewIn26: false },
        { playName: "JET PA X POST", isNewIn26: false },
        { playName: "JET READ OPTION", isNewIn26: false },
        { playName: "JET SPLIT DIVE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "LEAD OPTION", isNewIn26: false },
        { playName: "MTN HB DIVE", isNewIn26: false },
        { playName: "MTN PAVERTS", isNewIn26: false },
        { playName: "MTN SPEED OPTION WK", isNewIn26: false },
        { playName: "ORBIT PA TE CROSS", isNewIn26: false },
        { playName: "ORBIT RPO READ TE SLIDE", isNewIn26: false },
        { playName: "ORBIT TRIPLE OPTION", isNewIn26: false },
        { playName: "PA BOOT LT", isNewIn26: false },
        { playName: "PA POST CURL", isNewIn26: false },
        { playName: "READ OPTION WK", isNewIn26: false },
        { playName: "SPEED OPTION WK", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Wing Slot Over",
      formationType: "Pistol",
      plays: [
        { playName: "HB POWER G", isNewIn26: false },
        { playName: "MTN PA DAGGER", isNewIn26: false },
        { playName: "MTN SPLIT ZONE", isNewIn26: false },
        { playName: "MTN WIDE ZONE WK", isNewIn26: false },
        { playName: "PA STRETCH SHOT", isNewIn26: false },
        { playName: "ROLLOUT FLOOD", isNewIn26: false },
        { playName: "SPLIT ZONE", isNewIn26: false },
        { playName: "WIDE ZONE", isNewIn26: false },
        { playName: "ZONE ALERT BUBBLE", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Bunch Str Offset",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "DAGGER", isNewIn26: false },
        { playName: "DUO", isNewIn26: false },
        { playName: "FK TOSS SLIDE", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "LEAD SWING SPOT", isNewIn26: false },
        { playName: "MTN DEEP POST", isNewIn26: false },
        { playName: "MTN FK TOSS VERTICALS", isNewIn26: false },
        { playName: "MTN INSIDE ZONE", isNewIn26: false },
        { playName: "MTN LEAD TOSS", isNewIn26: false },
        { playName: "MTN RPO ALERT SWING", isNewIn26: false },
        { playName: "MTN STICK", isNewIn26: false },
        { playName: "PIN PULL TOSS", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT SCREEN", isNewIn26: false },
        { playName: "SLANT SPACING", isNewIn26: false },
        { playName: "Y TRAIL", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Deuce Close",
      formationType: "Gun",
      plays: [
        { playName: "BENCH DIG CURL", isNewIn26: false },
        { playName: "BENCH X DIG", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "LEAD READ OPTION", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "MTN BENCH RETURN", isNewIn26: false },
        { playName: "MTN CURLS CORNER STRIKE", isNewIn26: false },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "MTN PA DEEP OVER", isNewIn26: false },
        { playName: "MTN PA SLIDE", isNewIn26: false },
        { playName: "MTN TE MID SCREEN", isNewIn26: false },
        { playName: "PA POST CROSS", isNewIn26: false },
        { playName: "RETURN PA SLIDE", isNewIn26: false },
        { playName: "RETURN RPO READ FLAT WHEEL", isNewIn26: false },
        { playName: "RETURN RZ TRAIL", isNewIn26: false },
        { playName: "RPO PEEK STICK", isNewIn26: false },
        { playName: "RPO READ FLAT WHEEL", isNewIn26: false },
        { playName: "SPACING SWITCH", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Doubles Y Off",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "CURL COMBO", isNewIn26: false },
        { playName: "FAKE JET HB SEAM", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET HB SWEEP", isNewIn26: false },
        { playName: "JET PA HB SWEEP", isNewIn26: false },
        { playName: "JET POWER O", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MTN HB BASE", isNewIn26: false },
        { playName: "MTN HB SLIP SCREEN", isNewIn26: false },
        { playName: "MTN ORBIT LOAD OPTION", isNewIn26: false },
        { playName: "MTN ORBIT PA SPOT", isNewIn26: false },
        { playName: "MTN ORBIT WR OPTION", isNewIn26: false },
        { playName: "MTN PA WHEEL", isNewIn26: false },
        { playName: "MTN PA Y SCREEN", isNewIn26: false },
        { playName: "MTN SNAG", isNewIn26: false },
        { playName: "MTN X SPOT", isNewIn26: false },
        { playName: "ORBIT ALERT COUNTER", isNewIn26: false },
        { playName: "ORBIT PA HB WHEEL", isNewIn26: false },
        { playName: "ORBIT RPO ALERT", isNewIn26: false },
        { playName: "PA GO SLOT CROSS", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO BUBBLE", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "SLOT FADE", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Doubles Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "H SHALLOW CROSS", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "MTN FAKE JET SHOT", isNewIn26: false },
        { playName: "MTN HB SWING", isNewIn26: false },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "MTN JET QB COUNTER", isNewIn26: false },
        { playName: "MTN JET TOUCH PASS", isNewIn26: false },
        { playName: "MTN LEAD SWING SPOT", isNewIn26: false },
        { playName: "MTN PA WHEEL", isNewIn26: false },
        { playName: "MTN RPO READ Y FLAT", isNewIn26: false },
        { playName: "MTN STICK WHEEL", isNewIn26: false },
        { playName: "OUTS CORNER STRIKE", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "STRIKE HB SEAM", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Empty Base",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "DIG CURL READ", isNewIn26: false },
        { playName: "FK SCREEN SLUGGO", isNewIn26: false },
        { playName: "FK SCREEN VERTS", isNewIn26: false },
        { playName: "INSIDE CROSS", isNewIn26: false },
        { playName: "JET POWER READ", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MTN HB SCREEN", isNewIn26: false },
        { playName: "QB DRAW", isNewIn26: false },
        { playName: "SHOCK", isNewIn26: false },
        { playName: "SLOT DRIVE", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "VERTICALS", isNewIn26: false },
        { playName: "WR MID SCREEN", isNewIn26: false },
        { playName: "WR SCREEN", isNewIn26: false },
        { playName: "Y CORNER", isNewIn26: false },
        { playName: "Y CROSS", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Empty Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "CURLS Y SHAKE", isNewIn26: false },
        { playName: "DBL SLOT CROSS", isNewIn26: false },
        { playName: "FOUR VERTICALS", isNewIn26: false },
        { playName: "JET QB COUNTER", isNewIn26: false },
        { playName: "JET QB POWER", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "MTN DOUBLE SPOT", isNewIn26: false },
        { playName: "MTN LOAD OPTION", isNewIn26: false },
        { playName: "MTN SPOT N GO", isNewIn26: false },
        { playName: "PA JET FLOOD", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
        { playName: "PA JET SWEEP SHOT", isNewIn26: false },
        { playName: "QB POWER", isNewIn26: false },
        { playName: "QB ZONE", isNewIn26: false },
        { playName: "RZ DUSTY", isNewIn26: false },
        { playName: "SPRINT SMASH", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Normal Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "DASH HITCH SLOT OVER", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE CROSS", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MTN HB SLIP SCREEN", isNewIn26: false },
        { playName: "MTN INSIDE ZONE", isNewIn26: false },
        { playName: "MTN PA SPOT", isNewIn26: false },
        { playName: "MTN RPO ALERT SCREEN", isNewIn26: false },
        { playName: "MTN STICK WHEEL", isNewIn26: false },
        { playName: "POWER READ", isNewIn26: false },
        { playName: "RPO GLANCE SLANT", isNewIn26: false },
        { playName: "RPO READ BUBBLE", isNewIn26: false },
        { playName: "SHALLOW CROSS", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "WR UNDER", isNewIn26: false },
        { playName: "X DAGGER", isNewIn26: false },
        { playName: "Y MTN SHOCK", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Split Twins",
      formationType: "Gun",
      plays: [
        { playName: "CORNERS", isNewIn26: false },
        { playName: "HB ANGLE", isNewIn26: false },
        { playName: "HB OFF TACKLE", isNewIn26: false },
        { playName: "HB POWER O", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "ORBIT LEAD TRIPLE OPT", isNewIn26: false },
        { playName: "ORBIT PA HB WHEEL", isNewIn26: false },
        { playName: "ORBIT PA WHEEL SHOT", isNewIn26: false },
        { playName: "PA F SLIDE", isNewIn26: false },
        { playName: "PA Y OUT", isNewIn26: false },
        { playName: "POWER READ", isNewIn26: false },
        { playName: "RPO PEEK POST", isNewIn26: false },
        { playName: "RPO SPLIT ALERT SNAG", isNewIn26: false },
        { playName: "SHOVEL OPTION", isNewIn26: false },
        { playName: "TRIPLE OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Split Twins Offset",
      formationType: "Gun",
      plays: [
        { playName: "FLOOD", isNewIn26: false },
        { playName: "HB CROSS BUCK", isNewIn26: false },
        { playName: "MTN HB POWER G", isNewIn26: false },
        { playName: "MTN HB TOSS", isNewIn26: false },
        { playName: "MTN PA Y SEAM", isNewIn26: false },
        { playName: "MTN X SPOT", isNewIn26: false },
        { playName: "OVER MTN BUCK TRIPLE OPT", isNewIn26: false },
        { playName: "OVER MTN OUTSIDE ZONE", isNewIn26: false },
        { playName: "OVER MTN PA SLIDE", isNewIn26: false },
        { playName: "PA F SLIDE", isNewIn26: false },
        { playName: "PA HB SEAM", isNewIn26: false },
        { playName: "PA THROWBACK SCREEN", isNewIn26: false },
        { playName: "POWER G", isNewIn26: false },
        { playName: "RPO ALERT SWING", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "TRIPLE OPTION LT", isNewIn26: false },
        { playName: "TRIPLE OPTION RT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Split Twins Y Off",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER BASH", isNewIn26: false },
        { playName: "LEAD SPLIT ZONE", isNewIn26: false },
        { playName: "MTN CNTR BASH", isNewIn26: false },
        { playName: "MTN HB CROSS SCREEN", isNewIn26: false },
        { playName: "MTN HB SWEEP WK", isNewIn26: false },
        { playName: "MTN LEAD SWING SPOT", isNewIn26: false },
        { playName: "MTN PA HB SEAM", isNewIn26: false },
        { playName: "MTN POWER READ TOSS", isNewIn26: false },
        { playName: "MTN RPO ALERT SPLIT", isNewIn26: false },
        { playName: "MTN RPO READ SLIDE", isNewIn26: false },
        { playName: "MTN RPO READ Y SLIDE", isNewIn26: false },
        { playName: "PA HB CORNER", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Spread Y-Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "DRIVE HB WHEEL", isNewIn26: false },
        { playName: "FL SCREEN", isNewIn26: false },
        { playName: "GL SLOT OUT", isNewIn26: false },
        { playName: "H SHALLOW CROSS", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MTN FK SWING WHEEL", isNewIn26: false },
        { playName: "MTN HB SWING", isNewIn26: false },
        { playName: "MTN LEAD SWING SPOT", isNewIn26: false },
        { playName: "MTN MESH SPOT", isNewIn26: false },
        { playName: "MTN OUT H ANGLE", isNewIn26: false },
        { playName: "MTN SHALLOW HB ANGLE", isNewIn26: false },
        { playName: "POWER READ", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT QB DRAW", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "Y CROSS", isNewIn26: false },
        { playName: "Y SAIL", isNewIn26: false },
        { playName: "Y SHALLOW CROSS", isNewIn26: false },
        { playName: "Y STICK", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips Off Over Wk",
      formationType: "Gun",
      plays: [
        { playName: "DASH SLOT OVER", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "ORBIT COUNTER BASH", isNewIn26: false },
        { playName: "ORBIT HB OFF TACKLE", isNewIn26: false },
        { playName: "ORBIT WR OPTION", isNewIn26: false },
        { playName: "RPO ALERT SPLIT BUBBLE", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "RPO READ Y FLAT", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips Y Slot Str",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER", isNewIn26: false },
        { playName: "FOUR VERTICALS", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SWEEP", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "PA Y CROSS", isNewIn26: false },
        { playName: "QUICK SLANTS", isNewIn26: false },
        { playName: "RPO ALERT SHOCK", isNewIn26: false },
        { playName: "SHOCK", isNewIn26: false },
        { playName: "SLOT 2 BUC", isNewIn26: false },
        { playName: "SPRINT RIGHT SMASH", isNewIn26: false },
        { playName: "SPRINT SLOT CORNER", isNewIn26: false },
        { playName: "Y MTN HB DRAW", isNewIn26: false },
        { playName: "Y MTN HB SLIP SCREEN", isNewIn26: false },
        { playName: "Y MTN WHEELIES", isNewIn26: false },
      ],
    },
    {
      formation: "Gun U Off Over",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "LEAD READ OPTION", isNewIn26: false },
        { playName: "ORBIT HB CROSS SCREEN", isNewIn26: false },
        { playName: "ORBIT LEAD SLOT OPTION", isNewIn26: false },
        { playName: "ORBIT RPO ALERT SPLIT SLANT", isNewIn26: false },
        { playName: "OUTSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "PA SPLIT Z TUNNEL", isNewIn26: false },
        { playName: "PA SWITCH", isNewIn26: false },
        { playName: "PA SWITCH CURLS", isNewIn26: false },
        { playName: "RPO ALERT SPLIT HITCHES", isNewIn26: false },
      ],
    },
    {
      formation: "Gun U Off Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER SIT", isNewIn26: false },
        { playName: "EXIT PA FK SCREEN", isNewIn26: false },
        { playName: "EXIT RPO ALERT SCREEN", isNewIn26: false },
        { playName: "EXIT RPO BUCK ALERT", isNewIn26: false },
        { playName: "FK JET TOSS PASS", isNewIn26: false },
        { playName: "HB POWER", isNewIn26: false },
        { playName: "HB TOSS FK JET", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET PASS FK TOSS", isNewIn26: false },
        { playName: "LEVELS OUT", isNewIn26: false },
        { playName: "PA CROSSERS", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "DRAGON SPACING", isNewIn26: false },
        { playName: "FAKE JET HB WHEEL", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET POWER READ", isNewIn26: false },
        { playName: "JET QB COUNTER", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "MTN HB SWING", isNewIn26: false },
        { playName: "MTN INSIDE ZONE", isNewIn26: false },
        { playName: "MTN PA VERTICALS", isNewIn26: false },
        { playName: "MTN PA Z SLIDE", isNewIn26: false },
        { playName: "MTN QB SWEEP", isNewIn26: false },
        { playName: "PA DOUBLE POST", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RZ MTN WR ANGLE", isNewIn26: false },
        { playName: "SCISSORS SMASH", isNewIn26: false },
        { playName: "SHALLOW MILLS", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Trio",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MTN HB SCREEN", isNewIn26: false },
        { playName: "MTN MESH POCO", isNewIn26: false },
        { playName: "MTN MESH SPOT", isNewIn26: false },
        { playName: "MTN PA CROSS", isNewIn26: false },
        { playName: "MTN PA SHOT CROSS", isNewIn26: false },
        { playName: "MTN READ OPTION", isNewIn26: false },
        { playName: "MTN RPO ALERT SWING", isNewIn26: false },
        { playName: "MTN RPO GLANCE POST", isNewIn26: false },
        { playName: "MTN RPO READ SWING", isNewIn26: false },
        { playName: "ORBIT MESH HB SWING", isNewIn26: false },
        { playName: "ORBIT RPO PEEK Y FLAT", isNewIn26: false },
        { playName: "PA ALL CURL", isNewIn26: false },
        { playName: "POWER READ TOSS", isNewIn26: false },
        { playName: "RPO PEEK Y POP", isNewIn26: false },
        { playName: "RPO ZONE ALERT SCREEN", isNewIn26: false },
        { playName: "RPO ZONE PEEK", isNewIn26: false },
        { playName: "RZ ORBIT CROSSERS", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "Y FLOOD", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "MTN CROSS Z POCO", isNewIn26: false },
        { playName: "MTN DASH HITCH OVER", isNewIn26: false },
        { playName: "MTN HB OFF TACKLE", isNewIn26: false },
        { playName: "MTN HB SLIP SCREEN", isNewIn26: false },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "MTN OUTSIDE ZONE", isNewIn26: false },
        { playName: "MTN PA SPLIT", isNewIn26: false },
        { playName: "MTN PA WHEEL", isNewIn26: false },
        { playName: "MTN RPO ALERT", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "PA Y WHEEL", isNewIn26: false },
        { playName: "QUADS DRIVE", isNewIn26: false },
        { playName: "QUADS SHALLOW Y HOOK", isNewIn26: false },
        { playName: "QUADS SPRINT SPOT", isNewIn26: false },
        { playName: "SLOT CROSS", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "SWITCH COMEBACK", isNewIn26: false },
        { playName: "SWITCH Z CURL", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Y Off Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "BOUNCE INSIDE ZONE", isNewIn26: false },
        { playName: "BOUNCE PA POST CURLS", isNewIn26: false },
        { playName: "BOUNCE SLOT CROSS", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "HI LO DIG", isNewIn26: false },
        { playName: "MTN CURLS", isNewIn26: false },
        { playName: "MTN FADE DAGGER", isNewIn26: false },
        { playName: "MTN SLOT WHIP IN", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA SLIDE", isNewIn26: false },
        { playName: "POST N CROSS", isNewIn26: false },
        { playName: "RPO ALERT SHOCK", isNewIn26: false },
        { playName: "RPO GLANCE BUBBLE", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "STRONG FLOOD", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE", isNewIn26: false },
        { playName: "HB COUNTER WK", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB SPLIT O", isNewIn26: false },
        { playName: "HB STING", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false },
        { playName: "PA SPOT", isNewIn26: false },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false },
        { playName: "PA WAGGLE", isNewIn26: false },
        { playName: "POWER O", isNewIn26: false },
        { playName: "QB SNEAK", isNewIn26: false },
        { playName: "STRONG TOSS", isNewIn26: false },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false },
        { playName: "HAIL MARY", isNewIn26: false },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false },
      ],
    },
  ],
};
