import type { TeamPlaybookSeed } from "../types";

export const KENTUCKY_SEED: TeamPlaybookSeed = {
  team: "Kentucky",
  scheme: "Pro Style",
  source: {
    url: "https://cfb.fan/26/playbooks/kentucky-off/",
    verified: "2026-05-02",
  },
  formations: [
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE", isNewIn26: false },
        { playName: "HB COUNTER WK", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB SPLIT O", isNewIn26: false },
        { playName: "HB STING", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false },
        { playName: "PA SPOT", isNewIn26: false },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false },
        { playName: "PA WAGGLE", isNewIn26: false },
        { playName: "POWER O", isNewIn26: false },
        { playName: "QB SNEAK", isNewIn26: false },
        { playName: "STRONG TOSS", isNewIn26: false },
      ],
    },
    {
      formation: "Gun 5WR Flex Trey",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CURL FLATS", isNewIn26: false },
        { playName: "DRIVE SMASH", isNewIn26: false },
        { playName: "EMPTY STICK", isNewIn26: false },
        { playName: "HITCH CORNERS", isNewIn26: false },
        { playName: "JAILBREAK SLOT SCREEN", isNewIn26: false },
        { playName: "MIDDLE SLANT", isNewIn26: false },
        { playName: "SHALLOW CROSS", isNewIn26: false },
        { playName: "SLOT CORNER", isNewIn26: false },
        { playName: "STICK N NOD", isNewIn26: false },
        { playName: "STRONG FLOOD", isNewIn26: false },
        { playName: "VERTICALS Y-SHAKE", isNewIn26: false },
        { playName: "WILDCATS DOUBLE SCREEN", isNewIn26: false },
        { playName: "WR COMEBACKS", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: true },
      ],
    },
    {
      formation: "Gun Bunch Open Offset",
      formationType: "Gun",
      plays: [
        { playName: "DIG RETURN", isNewIn26: false },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false },
        { playName: "FLOOD", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "RELOAD INSIDE ZONE", isNewIn26: true },
        { playName: "RELOAD SPACING SWITCH", isNewIn26: true },
        { playName: "RELOAD Z SHALLOW CROSS", isNewIn26: true },
        { playName: "RPO PEEK WR SCREEN", isNewIn26: false },
        { playName: "SPRINT Z SPOT", isNewIn26: false },
        { playName: "WHEEL MILLS", isNewIn26: true },
        { playName: "Y TRAIL", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Bunch Spread Nasty",
      formationType: "Gun",
      plays: [
        { playName: "BRANCH RETURN", isNewIn26: true },
        { playName: "CORNER DIVIDE", isNewIn26: true },
        { playName: "DRIVE Y CORNER", isNewIn26: true },
        { playName: "HB SLIP SCREEN", isNewIn26: true },
        { playName: "INSIDE ZONE", isNewIn26: true },
        { playName: "MESH SLOT OUT", isNewIn26: true },
        { playName: "ORBIT BUNCH SALEM", isNewIn26: true },
        { playName: "ORBIT SHALLOW CROSS", isNewIn26: true },
        { playName: "ORBIT SMASH WHIP", isNewIn26: true },
        { playName: "OUTSIDE ZONE", isNewIn26: true },
        { playName: "PA POST", isNewIn26: true },
        { playName: "SEAM DIVIDE", isNewIn26: true },
        { playName: "WILDCATS MESH TRAFFIC", isNewIn26: false },
        { playName: "Z SWIRL CHOICE", isNewIn26: true },
        { playName: "ZSWIRLIN", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Bunch Str Offset",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "DAGGER", isNewIn26: false },
        { playName: "DUO", isNewIn26: false },
        { playName: "FK TOSS SLIDE", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "LEAD SWING SPOT", isNewIn26: true },
        { playName: "MTN DEEP POST", isNewIn26: false },
        { playName: "MTN HB BASE", isNewIn26: true },
        { playName: "MTN INSIDE ZONE", isNewIn26: false },
        { playName: "MTN PA WHEEL CROSS", isNewIn26: true },
        { playName: "MTN PA Y SCREEN", isNewIn26: true },
        { playName: "MTN STICK", isNewIn26: false },
        { playName: "PIN PULL TOSS", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT SCREEN", isNewIn26: false },
        { playName: "SLANT SPACING", isNewIn26: false },
        { playName: "Y TRAIL", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Doubles Y Off",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "CURL COMBO", isNewIn26: false },
        { playName: "FAKE JET HB SEAM", isNewIn26: false },
        { playName: "FAKE JET PASS POWER", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET COUNTER Y", isNewIn26: true },
        { playName: "JET HB ANGLE", isNewIn26: true },
        { playName: "JET HB CROSS SCREEN", isNewIn26: true },
        { playName: "JET HB SPLIT ZONE", isNewIn26: true },
        { playName: "JET HB SWEEP", isNewIn26: false },
        { playName: "JET HB TRAP", isNewIn26: true },
        { playName: "JET INSIDE ZONE", isNewIn26: false },
        { playName: "JET PA COMEBACKS", isNewIn26: true },
        { playName: "JET PA HB SWEEP", isNewIn26: false },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "JET POWER READ", isNewIn26: true },
        { playName: "JET RPO GLANCE", isNewIn26: true },
        { playName: "JET TE MID SCREEN", isNewIn26: true },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "PA GO SLOT CROSS", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
        { playName: "RPO BUBBLE", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Flex Y Off",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "DOUBLE SLANTS", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MTN INSIDE ZONE", isNewIn26: true },
        { playName: "MTN PA FLOOD", isNewIn26: true },
        { playName: "MTN WR CROSS", isNewIn26: true },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false },
        { playName: "PA SEAM DIGS", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT HB ZONE", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Spread Offset",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false },
        { playName: "ALL GO", isNewIn26: false },
        { playName: "FAKE BUBBLE SLANT", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "QUICK SLANTS", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT ZONE BUBBLE", isNewIn26: true },
        { playName: "SMASH BULLSEYE", isNewIn26: false },
        { playName: "SMASH CROSS", isNewIn26: false },
        { playName: "SMASH VERTICALS", isNewIn26: false },
        { playName: "Y CROSS", isNewIn26: false },
        { playName: "Y SHALLOW CROSS", isNewIn26: false },
        { playName: "ZONE SPEED OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Stack HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "BENCH SWITCH", isNewIn26: false },
        { playName: "CURL FLAT", isNewIn26: false },
        { playName: "CURL SWITCH", isNewIn26: false },
        { playName: "DIY TOSS REVERSE", isNewIn26: false },
        { playName: "DOUBLE CORNER", isNewIn26: false },
        { playName: "FADE OUT", isNewIn26: false },
        { playName: "FK TOSS CROSS", isNewIn26: false },
        { playName: "FK TOSS POST SIT", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false },
        { playName: "RPO ALERT SCREEN", isNewIn26: false },
        { playName: "TOSS WK", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Stack Y Off",
      formationType: "Gun",
      plays: [
        { playName: "BENCH HB ANGLE", isNewIn26: false },
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "FAKE JET HB SEAM", isNewIn26: false },
        { playName: "FAKE JET PASS POWER", isNewIn26: false },
        { playName: "FLOOD DRIVE", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET QB COUNTER", isNewIn26: true },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "LEVELS", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
        { playName: "REDZONE SCISSORS", isNewIn26: false },
        { playName: "RPO ALERT OUT", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Stack Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "BENCH SWITCH", isNewIn26: false },
        { playName: "CURL FLATS", isNewIn26: false },
        { playName: "CURL SWITCH", isNewIn26: false },
        { playName: "DOUBLE CORNER", isNewIn26: false },
        { playName: "FAKE SCREEN GO", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "LEVELS", isNewIn26: false },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false },
        { playName: "RPO POWER ALERT SCREEN", isNewIn26: false },
        { playName: "RPO SPLIT ALERT SCREEN", isNewIn26: false },
        { playName: "RPO TRAP ALERT SCREEN", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trio Rt Open",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: true },
        { playName: "CROSS Z CURL", isNewIn26: true },
        { playName: "DOUBLE POST", isNewIn26: true },
        { playName: "DRIVE", isNewIn26: true },
        { playName: "FOUR VERTICALS", isNewIn26: true },
        { playName: "HB DRAW", isNewIn26: true },
        { playName: "INSIDE ZONE", isNewIn26: true },
        { playName: "PA READ", isNewIn26: true },
        { playName: "READ OPTION", isNewIn26: true },
        { playName: "RPO ALERT BUBBLE", isNewIn26: true },
        { playName: "RPO ALERT QB DRAW", isNewIn26: true },
        { playName: "SPEED OPTION", isNewIn26: true },
        { playName: "STICK", isNewIn26: true },
        { playName: "WR MID SCREEN", isNewIn26: true },
        { playName: "Z UNDER", isNewIn26: true },
      ],
    },
    {
      formation: "Gun Trio Unbalanced",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false },
        { playName: "HB SWING", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "PA FK BUBBLE WHEEL", isNewIn26: false },
        { playName: "RPO ZONE ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO ZONE ALERT SCREEN", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "VERTICALS", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips TE Offset",
      formationType: "Gun",
      plays: [
        { playName: "FLOOD", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "LEVELS SAIL", isNewIn26: false },
        { playName: "PA CROSSERS", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: true },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "SHOCK H OPTION", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "VERTICALS", isNewIn26: false },
        { playName: "X UNDER", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips Y Over",
      formationType: "Gun",
      plays: [
        { playName: "FAKE BUBBLE WHEEL", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: true },
        { playName: "JAILBREAK SLOT SCREEN", isNewIn26: true },
        { playName: "PA SMASH RETURN", isNewIn26: true },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO PEEK SLANTS", isNewIn26: true },
        { playName: "RPO READ BUBBLE", isNewIn26: false },
        { playName: "RPO ZONE ALERT SHOCK", isNewIn26: false },
        { playName: "RZ PA Z BANG", isNewIn26: false },
        { playName: "SPRINT CORNER", isNewIn26: false },
        { playName: "VERTICALS", isNewIn26: false },
      ],
    },
    {
      formation: "Gun U Off Over",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: true },
        { playName: "DBL MTN COUNTER Y", isNewIn26: true },
        { playName: "DBL MTN INSIDE ZONE SPLIT", isNewIn26: true },
        { playName: "DBL MTN PA SLIDE", isNewIn26: true },
        { playName: "INSIDE ZONE", isNewIn26: true },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: true },
        { playName: "LEAD READ OPTION", isNewIn26: true },
        { playName: "OUTSIDE ZONE SPLIT", isNewIn26: true },
        { playName: "PA SPLIT Z TUNNEL", isNewIn26: true },
        { playName: "PA SWITCH", isNewIn26: true },
        { playName: "PA SWITCH CURLS", isNewIn26: true },
        { playName: "RPO ALERT SPLIT HITCHES", isNewIn26: true },
      ],
    },
    {
      formation: "Gun Wing Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "BUCK SWEEP READ OPT", isNewIn26: false },
        { playName: "CROSS CORNER STRIKE", isNewIn26: false },
        { playName: "DRIVE", isNewIn26: false },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "HB COUNTER U", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MESH HB CORNER", isNewIn26: false },
        { playName: "MIDLINE READ OPTION", isNewIn26: false },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false },
        { playName: "PA DAGGER", isNewIn26: false },
        { playName: "PA INVERTED VEER", isNewIn26: false },
        { playName: "POWER READ", isNewIn26: false },
        { playName: "QB WRAP", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO GLANCE POST", isNewIn26: false },
        { playName: "RPO PEEK POST", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL CURL", isNewIn26: true },
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "DEEP OUTS", isNewIn26: true },
        { playName: "DUO", isNewIn26: false },
        { playName: "FLOOD HB SWING", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "HB SWING", isNewIn26: true },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: true },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA DOUBLE POST", isNewIn26: false },
        { playName: "PA READ SMASH", isNewIn26: false },
        { playName: "PA Y FLOOD", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "SPRINT FLOOD", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Y Off Trips Nasty",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "DAGGER WHIP", isNewIn26: false },
        { playName: "DOUBLE CROSS", isNewIn26: false },
        { playName: "FLOOD HB SWING", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "PA DOUBLE POST", isNewIn26: false },
        { playName: "RPO READ Y FLAT", isNewIn26: false },
        { playName: "SLOT 2 BUC", isNewIn26: false },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false },
        { playName: "HAIL MARY", isNewIn26: false },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Bunch",
      formationType: "Pistol",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "CURL FLAT", isNewIn26: false },
        { playName: "DBL MTN DUO WRAP", isNewIn26: true },
        { playName: "DBL MTN HB STRETCH", isNewIn26: true },
        { playName: "DBL MTN PA STRETCH", isNewIn26: true },
        { playName: "FLANKER DRIVE", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: true },
        { playName: "HB DUO", isNewIn26: true },
        { playName: "HB SLAM", isNewIn26: false },
        { playName: "HB ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "PA BOOT SLIDE", isNewIn26: false },
        { playName: "PA CROSS", isNewIn26: true },
        { playName: "PA PIN DEEP", isNewIn26: false },
        { playName: "READ OPTION WK", isNewIn26: false },
        { playName: "SPACING", isNewIn26: false },
        { playName: "TE ANGLE", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Doubles Y Off Stack",
      formationType: "Pistol",
      plays: [
        { playName: "FOUR VERTICALS", isNewIn26: false },
        { playName: "HB SPLIT DIVE", isNewIn26: false },
        { playName: "HB ZONE", isNewIn26: false },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "JET HB SPLIT DIVE", isNewIn26: false },
        { playName: "JET PA CROSS", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "PA CROSS", isNewIn26: false },
        { playName: "PA POST SHOT", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT SPLIT DIVE", isNewIn26: false },
        { playName: "WIDE ZONE", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Wing Flex Close",
      formationType: "Pistol",
      plays: [
        { playName: "COUNTER U", isNewIn26: false },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "PA BOOT LT", isNewIn26: false },
        { playName: "PA BOOT Y SAIL", isNewIn26: false },
        { playName: "PA DEEP CROSS", isNewIn26: false },
        { playName: "RPO READ JET SLIDE", isNewIn26: false },
        { playName: "SPACING", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "WIDE ZONE", isNewIn26: false },
        { playName: "WR UNDER", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Wing Slot Over",
      formationType: "Pistol",
      plays: [
        { playName: "DBL MTN HB ZONE", isNewIn26: true },
        { playName: "DBL MTN HB ZONE WK", isNewIn26: true },
        { playName: "DBL MTN PA VERTICALS", isNewIn26: true },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "PA STRETCH SHOT", isNewIn26: false },
        { playName: "POWER O", isNewIn26: false },
        { playName: "ROLLOUT FLOOD", isNewIn26: false },
        { playName: "SPLIT ZONE", isNewIn26: false },
        { playName: "WIDE ZONE", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Y Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "HB SPLIT DIVE", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "HB ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "MTN HB WIDE ZONE WK", isNewIn26: true },
        { playName: "MTN PA BOOT RT", isNewIn26: true },
        { playName: "MTN PA BOOT SLIDE", isNewIn26: true },
        { playName: "MTN RPO READ Y SLIDE", isNewIn26: true },
        { playName: "MTN WIDE ZONE", isNewIn26: true },
        { playName: "MTN ZONE SPLIT", isNewIn26: true },
        { playName: "PA BOOT SLIDE", isNewIn26: false },
        { playName: "PA SCISSORS", isNewIn26: false },
        { playName: "PA STRETCH SHOT", isNewIn26: false },
        { playName: "RPO READ Y SLIDE", isNewIn26: false },
        { playName: "RPO ZONE X GLANCE", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "VERTICAL TE CROSS", isNewIn26: false },
        { playName: "WIDE ZONE", isNewIn26: false },
        { playName: "WILDCATS WHEEL", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Singleback Ace Close",
      formationType: "Singleback",
      plays: [
        { playName: "BENCH", isNewIn26: false },
        { playName: "CLOSE PA CROSS", isNewIn26: false },
        { playName: "CLOSE Y SEAM", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "HB TOSS", isNewIn26: false },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "JET SWEEP", isNewIn26: false },
        { playName: "PA HB WHEEL", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
        { playName: "PIVOT SEAM", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "TIGHT SLOTS BENCH", isNewIn26: false },
        { playName: "TIGHT SLOTS CNTR WK", isNewIn26: false },
        { playName: "TIGHT SLOTS HB WHAM", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Singleback Doubles North",
      formationType: "Singleback",
      plays: [
        { playName: "HB BLUNT DIVE", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "HB TOSS", isNewIn26: false },
        { playName: "JET SWEEP", isNewIn26: false },
        { playName: "PA CROSS", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
        { playName: "PA ROLLOUT", isNewIn26: false },
        { playName: "SLOT CORNER", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "WR CORNER", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Singleback Doubles Y Off",
      formationType: "Singleback",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "INS LEFT", isNewIn26: false },
        { playName: "JET PA BOOT", isNewIn26: false },
        { playName: "JET PA BOOT SCREEN", isNewIn26: false },
        { playName: "JET PA Y SCREEN", isNewIn26: false },
        { playName: "JET SPLIT ZONE", isNewIn26: false },
        { playName: "JET SWEEP", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
        { playName: "PA JET SWEEP SCISSORS", isNewIn26: false },
        { playName: "PA JET SWEEP X OUT", isNewIn26: false },
        { playName: "WR DEEP HOOK", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Singleback Tight Slots",
      formationType: "Singleback",
      plays: [
        { playName: "DIY STRETCH REVERSE", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "HB WHEEL", isNewIn26: false },
        { playName: "JET SWEEP", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
        { playName: "PA STRETCH SHOT", isNewIn26: false },
        { playName: "SLOT CROSS", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Singleback Wing Slot",
      formationType: "Singleback",
      plays: [
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "HB ZONE ALERT BUBBLE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "JET HB POWER", isNewIn26: false },
        { playName: "JET HB SLASH", isNewIn26: false },
        { playName: "JET PA BOOT", isNewIn26: false },
        { playName: "JET PA BOOT SLIDE", isNewIn26: false },
        { playName: "JET PA POWER", isNewIn26: false },
        { playName: "JET SPLIT ZONE", isNewIn26: false },
        { playName: "JET SWEEP", isNewIn26: false },
        { playName: "MTN PA BOOT SCREEN", isNewIn26: true },
        { playName: "MTN PA Z SLIDE", isNewIn26: true },
        { playName: "MTN WIDE ZONE WK", isNewIn26: true },
        { playName: "PA BOOT SLIDE", isNewIn26: false },
        { playName: "PA JET SWEEP SHOT", isNewIn26: false },
        { playName: "PA SAIL X POST", isNewIn26: false },
        { playName: "PA STRETCH", isNewIn26: false },
        { playName: "PA Y SCREEN", isNewIn26: false },
        { playName: "PA Y-DRAG WHEEL", isNewIn26: false },
        { playName: "SMASH", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
  ],
};
