import type { TeamPlaybookSeed } from "../types";

export const MINNESOTA_SEED: TeamPlaybookSeed = {
  team: "Minnesota",
  scheme: "Multiple",
  source: {
    url: "https://cfb.fan/26/playbooks/minnesota-off/",
    verified: "2026-05-02",
  },
  formations: [
    {
      formation: "Singleback Bunch X Nasty",
      formationType: "Singleback",
      plays: [
        { playName: "CHEAT HB SLASH", isNewIn26: false },
        { playName: "CHEAT HB ZONE WK", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "CRACK TOSS", isNewIn26: false },
        { playName: "END AROUND POWER", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB POWER O", isNewIn26: false },
        { playName: "HB SLAM", isNewIn26: false },
        { playName: "HB SLASH", isNewIn26: false },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "PA BOOT", isNewIn26: false },
        { playName: "PA BOOT CORNER POST", isNewIn26: false },
        { playName: "PA BOOT SLIDE", isNewIn26: false },
        { playName: "PA CHEAT DEEP CORNER", isNewIn26: false },
        { playName: "PA COUNTER HB LEAK", isNewIn26: false },
        { playName: "PA CROSS", isNewIn26: false },
        { playName: "PA DEEP CROSS GO", isNewIn26: false },
        { playName: "PA DEEP OUT", isNewIn26: false },
        { playName: "PA POST CURL SHOT", isNewIn26: false },
        { playName: "PITCH WR REVERSE", isNewIn26: false },
        { playName: "SPACING", isNewIn26: false },
        { playName: "VERTICALS", isNewIn26: false },
        { playName: "WIDE ZONE WK", isNewIn26: false },
      ],
    },
    {
      formation: "Singleback Doubles Y Off",
      formationType: "Singleback",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB POWER O", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INS LEFT", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false },
        { playName: "WR DEEP HOOK", isNewIn26: false },
      ],
    },
    {
      formation: "Singleback Tight Flex",
      formationType: "Singleback",
      plays: [
        { playName: "BENCH", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLAM", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "MESH", isNewIn26: false },
        { playName: "OFF TACKLE", isNewIn26: false },
        { playName: "OUTN UPS", isNewIn26: false },
        { playName: "PA DRAW CROSS", isNewIn26: false },
      ],
    },
    {
      formation: "Singleback U Off Trips",
      formationType: "Singleback",
      plays: [
        { playName: "HB COUNTER STR", isNewIn26: false },
        { playName: "HB MISDIRECTION", isNewIn26: false },
        { playName: "HB SLAM", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "PA BOOT SLIDE", isNewIn26: false },
        { playName: "PA DAGGER U CROSS", isNewIn26: false },
        { playName: "PA FLOOD", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
      ],
    },
    {
      formation: "Singleback Wing",
      formationType: "Singleback",
      plays: [
        { playName: "CLOSE PA CROSS", isNewIn26: false },
        { playName: "CLOSE PA SAIL", isNewIn26: false },
        { playName: "CLOSE ZONE STRG", isNewIn26: false },
        { playName: "DRIVE", isNewIn26: false },
        { playName: "HB POWER O", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "HB SMASH", isNewIn26: false },
        { playName: "HB ZONE TOSS", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "PA BOOT", isNewIn26: false },
        { playName: "PA BOOT LT", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false },
        { playName: "TE ATTACK", isNewIn26: false },
        { playName: "WIDE ZONE", isNewIn26: false },
        { playName: "Y STICK", isNewIn26: false },
      ],
    },
    {
      formation: "Singleback Wing Tight Z",
      formationType: "Singleback",
      plays: [
        { playName: "26 DUO", isNewIn26: false },
        { playName: "DAGGER", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB POWER O", isNewIn26: false },
        { playName: "HB SMASH", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "PA BOOT LT", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false },
        { playName: "PA Y CORNER", isNewIn26: false },
        { playName: "PA Y DRAG WHEEL", isNewIn26: false },
        { playName: "Y STICK", isNewIn26: false },
      ],
    },
    {
      formation: "Singleback Y Off Trips",
      formationType: "Singleback",
      plays: [
        { playName: "CHINA UNDER", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "CURLS", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB INSIDE ZONE", isNewIn26: false },
        { playName: "HB POWER O", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "OFF TACKLE", isNewIn26: false },
        { playName: "PA BOOT RT", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false },
        { playName: "PA SLOT CROSS", isNewIn26: false },
        { playName: "PA VERTICALS", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
      ],
    },
    {
      formation: "Wildcat Wing Slot",
      formationType: "Wildcat",
      plays: [
        { playName: "LEAD", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "POWER G", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "WRAP", isNewIn26: false },
        { playName: "ZONE", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Doubles Offset",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CURL COMBO", isNewIn26: false },
        { playName: "DAGGER", isNewIn26: false },
        { playName: "DOUBLE SLANTS", isNewIn26: false },
        { playName: "FADE SMASH", isNewIn26: false },
        { playName: "FLANKER DRIVE", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "PA GO DIG POST", isNewIn26: false },
        { playName: "PA GO SLOT CROSS", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "RPO ZONE ALERT GLANCE", isNewIn26: false },
        { playName: "SALEM X KITTY", isNewIn26: false },
        { playName: "SHALLOW CROSS", isNewIn26: false },
        { playName: "SHARK HB WHEEL", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "TEXAS DOUBLE POST", isNewIn26: false },
        { playName: "Y SAIL", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Doubles Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "CURL FLAT", isNewIn26: false },
        { playName: "DOUBLE POST", isNewIn26: false },
        { playName: "DOUBLE SLANTS", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "LEAD READ OPTION", isNewIn26: false },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "PA SLIDE", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO GLANCE POST", isNewIn26: false },
        { playName: "RPO GLANCE SLANT", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "X DAGGER", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Empty Trey Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CURL COMBO", isNewIn26: false },
        { playName: "DBL SLOT CROSS", isNewIn26: false },
        { playName: "HI LO READ", isNewIn26: false },
        { playName: "LEVELS SWITCH", isNewIn26: false },
        { playName: "MTN ALL GO", isNewIn26: false },
        { playName: "MTN JAILBREAK SCREEN", isNewIn26: false },
        { playName: "MTN SLOT OUT", isNewIn26: false },
        { playName: "QB DRAW", isNewIn26: false },
        { playName: "SMASH", isNewIn26: false },
        { playName: "VERTICALS Y SHAKE", isNewIn26: false },
        { playName: "WDT POST", isNewIn26: false },
        { playName: "WR SCREEN", isNewIn26: false },
        { playName: "Y CORNER", isNewIn26: false },
        { playName: "Y STICK", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Normal Y Off",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false },
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MTN HB OFF TACKLE", isNewIn26: false },
        { playName: "MTN INSIDE ZONE", isNewIn26: false },
        { playName: "MTN PA SEAM WHEEL", isNewIn26: false },
        { playName: "MTN PA VERTICALS", isNewIn26: false },
        { playName: "MTN PA WHEEL SHOT", isNewIn26: false },
        { playName: "MTN RPO READ Y FLAT", isNewIn26: false },
        { playName: "PA DEEP SAIL", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
        { playName: "PA QB CHOICE", isNewIn26: false },
        { playName: "REDZONE SCISSORS", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "SCISSORS Z CURL", isNewIn26: false },
        { playName: "SEAM F ANGLE", isNewIn26: false },
        { playName: "STICK SLOT OPTION", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Normal Y Off Close",
      formationType: "Gun",
      plays: [
        { playName: "ESCAPE", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "REDZONE SCISSORS", isNewIn26: false },
        { playName: "RPO ALERT OUT", isNewIn26: false },
        { playName: "RPO GLANCE POST", isNewIn26: false },
        { playName: "WHEEL SWITCH", isNewIn26: false },
        { playName: "Y SAIL", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Spread HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CAKE READ OPTION", isNewIn26: false },
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "FLANKER DIG", isNewIn26: false },
        { playName: "H SHALLOW CROSS", isNewIn26: false },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "HITCH SEAM", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false },
        { playName: "PA DAGGER", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "QUICK SLANTS", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "RPO READ BUBBLE", isNewIn26: false },
        { playName: "RPO READ WR SCREEN", isNewIn26: false },
        { playName: "SMASH CORNERS", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Tight Off Wk 2TE",
      formationType: "Gun",
      plays: [
        { playName: "7 DAGGER", isNewIn26: false },
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "CURLS", isNewIn26: false },
        { playName: "FLANKER SPOT", isNewIn26: false },
        { playName: "HB POWER O", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "RPO ZONE ALERT GLANCE", isNewIn26: false },
        { playName: "RPO ZONE ALERT SNAG", isNewIn26: false },
        { playName: "SHALLOW CROSS", isNewIn26: false },
        { playName: "SLOT CROSS", isNewIn26: false },
        { playName: "SMASH DAGGER", isNewIn26: false },
        { playName: "WR UNDER", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CURLS", isNewIn26: false },
        { playName: "DEEP STICK", isNewIn26: false },
        { playName: "DRAGON STICK", isNewIn26: false },
        { playName: "DRIVE", isNewIn26: false },
        { playName: "HB DIRECT", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE SWITCH", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MIDDLE SLAM", isNewIn26: false },
        { playName: "OHIO SAIL", isNewIn26: false },
        { playName: "PA WR IN", isNewIn26: false },
        { playName: "QUICK SLANTS", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "SHOCK H OPTION", isNewIn26: false },
        { playName: "SMASH", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "WR MID SCREEN", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips TE Y Slot",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false },
        { playName: "CHEAT CLEAROUT SEAM", isNewIn26: false },
        { playName: "CHEAT FLOOD DIVIDE", isNewIn26: false },
        { playName: "CHEAT INSIDE ZONE", isNewIn26: false },
        { playName: "CHINA Y POST", isNewIn26: false },
        { playName: "CURL FLAT", isNewIn26: false },
        { playName: "CURLS X GO", isNewIn26: false },
        { playName: "DEEP IN", isNewIn26: false },
        { playName: "DRIVE POST", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "PA COUNTER GO", isNewIn26: false },
        { playName: "PA SLOT CORNER", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "SLOT SWING", isNewIn26: false },
        { playName: "TE CORNER", isNewIn26: false },
        { playName: "TE MIDDLE SCREEN", isNewIn26: false },
        { playName: "TE SWIRL", isNewIn26: false },
        { playName: "VERTICALS", isNewIn26: false },
        { playName: "WR SHORT POST", isNewIn26: false },
        { playName: "X SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing",
      formationType: "Gun",
      plays: [
        { playName: "HB ANGLE", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "PA FORK", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "SLOT 2 BUC", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "TE ATTACK", isNewIn26: false },
        { playName: "Y DRIVE CLOWN", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing HB Wk Close",
      formationType: "Gun",
      plays: [
        { playName: "BUCK SWEEP", isNewIn26: false },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "HB COUNTER U", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA CROSS", isNewIn26: false },
        { playName: "PA Y OVER", isNewIn26: false },
        { playName: "SPACING", isNewIn26: false },
        { playName: "Y STICK", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "DRIVE", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "MTN HB JAILBREAK SCREEN", isNewIn26: false },
        { playName: "MTN OHIO TE ATTACK", isNewIn26: false },
        { playName: "MTN POST DAGGER WHEEL", isNewIn26: false },
        { playName: "OHIO SPACING", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA DOUBLE POST", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "POWER O", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO ZONE ALERT HITCHES", isNewIn26: false },
        { playName: "SMASH", isNewIn26: false },
        { playName: "SPOT SLANTS", isNewIn26: false },
        { playName: "VERTS CHOICE", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "BUCK SWEEP READ OPT", isNewIn26: false },
        { playName: "DRIVE", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MESH HB CORNER", isNewIn26: false },
        { playName: "PA DAGGER", isNewIn26: false },
        { playName: "POWER ALERT BUBBLE", isNewIn26: false },
        { playName: "POWER ALERT GLANCE", isNewIn26: false },
        { playName: "QB WRAP", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO PEEK POST", isNewIn26: false },
        { playName: "RPO POWER PEEK SLANT", isNewIn26: false },
        { playName: "RPO READ BUBBLE", isNewIn26: false },
        { playName: "RPO SWEEP PEEK", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "SMASH", isNewIn26: false },
        { playName: "TE LEAD READ OPT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "BUCK SWEEP", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "MTN HB SLIP SCREEN", isNewIn26: false },
        { playName: "MTN PA CROSS SWITCH", isNewIn26: false },
        { playName: "MTN PA WHEEL", isNewIn26: false },
        { playName: "MTN RPO ALERT", isNewIn26: false },
        { playName: "MTN RPO READ Y FLAT", isNewIn26: false },
        { playName: "MTN WHEEL SPOT", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "PA Y WHEEL", isNewIn26: false },
        { playName: "REVERSE", isNewIn26: false },
        { playName: "RPO ALERT SLANT", isNewIn26: false },
        { playName: "RZ SLOT OUT", isNewIn26: false },
        { playName: "SHOT Y WHEEL", isNewIn26: false },
        { playName: "SLOT CROSS", isNewIn26: false },
        { playName: "SLOT SCREEN", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "CURLS", isNewIn26: false },
        { playName: "FLOOD HB SWING", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA DOUBLE POST", isNewIn26: false },
        { playName: "PA MTN SLIDE", isNewIn26: false },
        { playName: "PA Y FLOOD", isNewIn26: false },
        { playName: "PA ZONE SHOT", isNewIn26: false },
        { playName: "RPO ALERT SHOCK", isNewIn26: false },
        { playName: "RPO BUBBLE Y POP", isNewIn26: false },
        { playName: "RPO READ Y FLAT", isNewIn26: false },
        { playName: "RPO X GLANCE BUBBLE", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "VERTICALS Y OPTION", isNewIn26: false },
        { playName: "Y LEAD READ OPT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Y Off Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "CURLS", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "HI LO DIG", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MTN HB SWING", isNewIn26: false },
        { playName: "MTN PUMP AND GO", isNewIn26: false },
        { playName: "MTN Z SPOT", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA SLIDE", isNewIn26: false },
        { playName: "POST N CROSS", isNewIn26: false },
        { playName: "RPO ALERT SHOCK", isNewIn26: false },
        { playName: "RPO GLANCE BUBBLE", isNewIn26: false },
        { playName: "SHOCK H OPTION", isNewIn26: false },
        { playName: "SLOT FADE", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "STRONG FLOOD", isNewIn26: false },
        { playName: "TE SCREEN", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Y Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "POWER READ", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO READ Y POP", isNewIn26: false },
        { playName: "SLOT DRIVE", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "STICK N NOD", isNewIn26: false },
        { playName: "Y CORNER", isNewIn26: false },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE", isNewIn26: false },
        { playName: "HB COUNTER WK", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB SPLIT O", isNewIn26: false },
        { playName: "HB STING", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false },
        { playName: "PA SPOT", isNewIn26: false },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false },
        { playName: "PA WAGGLE", isNewIn26: false },
        { playName: "POWER O", isNewIn26: false },
        { playName: "QB SNEAK", isNewIn26: false },
        { playName: "STRONG TOSS", isNewIn26: false },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false },
        { playName: "HAIL MARY", isNewIn26: false },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false },
      ],
    },
  ],
};
