import type { TeamPlaybookSeed } from "../types";

export const MISSOURI_SEED: TeamPlaybookSeed = {
  team: "Missouri",
  scheme: "Pistol",
  sideOfBall: 'offense',
  source: {
    url: "https://cfb.fan/26/playbooks/missouri-off/",
    verified: "2026-05-02",
  },
  formations: [
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE", isNewIn26: false },
        { playName: "HB COUNTER WK", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB SPLIT O", isNewIn26: false },
        { playName: "HB STING", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false },
        { playName: "PA SPOT", isNewIn26: false },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false },
        { playName: "PA WAGGLE", isNewIn26: false },
        { playName: "POWER O", isNewIn26: false },
        { playName: "QB SNEAK", isNewIn26: false },
        { playName: "STRONG TOSS", isNewIn26: false },
      ],
    },
    {
      formation: "Gun 5WR Trio",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CURL FLATS", isNewIn26: false },
        { playName: "DOUBLE PIVOT", isNewIn26: false },
        { playName: "FLOOD SWITCH", isNewIn26: false },
        { playName: "HITCH CORNERS", isNewIn26: false },
        { playName: "JET SWEEP", isNewIn26: false },
        { playName: "MTN MESH Y-POST", isNewIn26: false },
        { playName: "QB DRAW", isNewIn26: false },
        { playName: "SHALLOW CROSS", isNewIn26: false },
        { playName: "SHOCK SLOT OPTION", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "SPACING", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "STRONG FLOOD", isNewIn26: false },
        { playName: "WR SCREENS", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Double Stack",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "FAKE SCREEN GO", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false },
        { playName: "RPO ALERT SCREEN", isNewIn26: false },
        { playName: "RPO ALERT TRAP", isNewIn26: false },
        { playName: "RPO READ FL SCREEN", isNewIn26: false },
        { playName: "SMASH", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Doubles HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CURL COMBO", isNewIn26: false },
        { playName: "DOUBLE CROSS", isNewIn26: false },
        { playName: "DOUBLE POST", isNewIn26: false },
        { playName: "DOUBLE SLANTS", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "PA CROSS", isNewIn26: false },
        { playName: "PA DEEP POST", isNewIn26: false },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "PA SEAMS", isNewIn26: false },
        { playName: "POST WHEELS", isNewIn26: false },
        { playName: "POWER ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "RPO READ BUBBLE", isNewIn26: false },
        { playName: "SLOT POST", isNewIn26: false },
        { playName: "SLOT WHEEL", isNewIn26: false },
        { playName: "WIDE ZONE", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Empty Bunch Wide",
      formationType: "Gun",
      plays: [
        { playName: "DRAG CURL", isNewIn26: false },
        { playName: "DRIVE WHEEL", isNewIn26: false },
        { playName: "DRIVE Y CORNER", isNewIn26: false },
        { playName: "JAILBREAK SCREEN", isNewIn26: false },
        { playName: "POST CORNER READ", isNewIn26: false },
        { playName: "QB DRAW", isNewIn26: false },
        { playName: "SPACING SWITCH", isNewIn26: false },
        { playName: "Z SPOT N GO", isNewIn26: false },
        { playName: "Z SPOT SMASH", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Normal Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CURL COMBO", isNewIn26: false },
        { playName: "DOUBLE SLANTS", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "HOOK Z POST", isNewIn26: false },
        { playName: "INSIDE CROSS", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "POWER READ", isNewIn26: false },
        { playName: "RPO READ BUBBLE", isNewIn26: false },
        { playName: "SHALLOW CROSS", isNewIn26: false },
        { playName: "SLUGGO SEAM", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "WR UNDER", isNewIn26: false },
        { playName: "X DAGGER", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Stack Y-Flex",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "CURL COMBO", isNewIn26: false },
        { playName: "DOUBLE CORNER", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB QUICK BASE", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "LEVELS", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false },
        { playName: "SALEM PIVOT", isNewIn26: false },
        { playName: "Y-SAIL", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Stack Y Off",
      formationType: "Gun",
      plays: [
        { playName: "BENCH HB ANGLE", isNewIn26: false },
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "CURL FLATS", isNewIn26: false },
        { playName: "FAKE JET HB SEAM", isNewIn26: false },
        { playName: "FAKE JET PASS POWER", isNewIn26: false },
        { playName: "FLOOD DRIVE", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "LEVELS", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
        { playName: "REDZONE SCISSORS", isNewIn26: false },
        { playName: "RPO ALERT OUT", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trio 4WR Str",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CHINA N GO", isNewIn26: false },
        { playName: "DAGGER", isNewIn26: false },
        { playName: "DBL CORNER SWITCH", isNewIn26: false },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false },
        { playName: "FLOOD DELAY", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT SCREEN", isNewIn26: false },
        { playName: "RPO READ BUBBLE", isNewIn26: false },
        { playName: "SHORT POSTS", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "SPRINT Z SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips",
      formationType: "Gun",
      plays: [
        { playName: "CROSS FLOOD", isNewIn26: false },
        { playName: "DOUBLE PASS RAIL", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "LEVELS", isNewIn26: false },
        { playName: "LEVELS SWITCH", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "PA WR IN", isNewIn26: false },
        { playName: "QB SLOT OPTION", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO READ SCREEN", isNewIn26: false },
        { playName: "SLOT DRIVE", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "STRONG FLOOD", isNewIn26: false },
        { playName: "WR MID SCREEN", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips Offset",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "SLOT DRIVE", isNewIn26: false },
        { playName: "SMASH", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "VERTICALS", isNewIn26: false },
        { playName: "WR MID SCREEN", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
        { playName: "ZONE SPEED OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips X Nasty",
      formationType: "Gun",
      plays: [
        { playName: "GL FORK ZIG", isNewIn26: false },
        { playName: "GL SHORT POST", isNewIn26: false },
        { playName: "GL UNDERS", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB OFF TACKLE", isNewIn26: false },
        { playName: "HI LO CROSS", isNewIn26: false },
        { playName: "HI LO DIG", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "PA X CROSS SHOT", isNewIn26: false },
        { playName: "SLOT FADE H WHEEL", isNewIn26: false },
        { playName: "VERTICALS X SHALLOW", isNewIn26: false },
        { playName: "WR SMASH", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips Y Slot",
      formationType: "Gun",
      plays: [
        { playName: "5 6 TRAP", isNewIn26: false },
        { playName: "ALL GO", isNewIn26: false },
        { playName: "DIG", isNewIn26: false },
        { playName: "GO DBL POST", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "HI LO DIG", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "PA SWITCH DIG", isNewIn26: false },
        { playName: "PA WR IN", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "SLOT 2 BUC", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "STICK N NOD", isNewIn26: false },
        { playName: "STRONG FLOOD", isNewIn26: false },
        { playName: "VERTICALS X SHALLOW", isNewIn26: false },
        { playName: "WR FORK", isNewIn26: false },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false },
        { playName: "HAIL MARY", isNewIn26: false },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false },
      ],
    },
    {
      formation: "I Form Tight",
      formationType: "I Form",
      plays: [
        { playName: "26 DUO", isNewIn26: false },
        { playName: "95 MIKE", isNewIn26: false },
        { playName: "FB DIVE", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB LEAD", isNewIn26: false },
        { playName: "HB LEAD TOSS", isNewIn26: false },
        { playName: "HB OFF TACKLE", isNewIn26: false },
        { playName: "HB POWER O", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "PA BOOT", isNewIn26: false },
        { playName: "PA CTR SHOT", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false },
        { playName: "PA TE CORNER", isNewIn26: false },
        { playName: "Y-DIG", isNewIn26: false },
        { playName: "Z SLANT", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Bunch Open",
      formationType: "Pistol",
      plays: [
        { playName: "DIG RETURN", isNewIn26: false },
        { playName: "FAKE SCREEN VERTICALS", isNewIn26: false },
        { playName: "FLOOD Z WHIP", isNewIn26: false },
        { playName: "FOUR VERTICALS", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "PA Z COMEBACK", isNewIn26: false },
        { playName: "RPO ALERT WR SCREEN", isNewIn26: false },
        { playName: "Y TRAIL", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Bunch X Nasty",
      formationType: "Pistol",
      plays: [
        { playName: "CORNER OUT DIG", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB ZONE", isNewIn26: false },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "SLANT SPACING", isNewIn26: false },
        { playName: "SMASH RETURN", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Doubles Y Off",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "FADE SMASH", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "HB ZONE", isNewIn26: false },
        { playName: "JET HB SPLIT DIVE", isNewIn26: false },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "PA CROSS", isNewIn26: false },
        { playName: "PA DEEP IN", isNewIn26: false },
        { playName: "PA OUT N UPS", isNewIn26: false },
        { playName: "PA POST SHOT", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
        { playName: "ZONE SPLIT", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Strong Slot Open",
      formationType: "Pistol",
      plays: [
        { playName: "F LEAD READ OPTION", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "MID SLANTS", isNewIn26: false },
        { playName: "PA FLOOD", isNewIn26: false },
        { playName: "PA SLIDE", isNewIn26: false },
        { playName: "SHAKES", isNewIn26: false },
        { playName: "STRETCH ALERT X LOOKIE", isNewIn26: false },
        { playName: "Y CORNER", isNewIn26: false },
        { playName: "Y CROSS", isNewIn26: false },
        { playName: "ZONE ALERT BUBBLE", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Tight Y Off Flex",
      formationType: "Pistol",
      plays: [
        { playName: "BENCH SWITCH", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "HB ZONE", isNewIn26: false },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "WHEEL SWITCH", isNewIn26: false },
        { playName: "WR STICK N OUT", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Trips",
      formationType: "Pistol",
      plays: [
        { playName: "FK WR SCREEN", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB SLAM", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "PA BOOT", isNewIn26: false },
        { playName: "PA BOOT LT", isNewIn26: false },
        { playName: "PA CTR WAGGLE", isNewIn26: false },
        { playName: "PA X DAGGER", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "SMASH", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "STRONG POWER", isNewIn26: false },
        { playName: "VERTICALS", isNewIn26: false },
        { playName: "WR SCREEN", isNewIn26: false },
        { playName: "X SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol U Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "DBL POST", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB SLAM", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "PA BOOT", isNewIn26: false },
        { playName: "PA BOOT OVER", isNewIn26: false },
        { playName: "PA CORNER DIG", isNewIn26: false },
        { playName: "PA FL CLOWN", isNewIn26: false },
        { playName: "QUICK SLANTS", isNewIn26: false },
        { playName: "RPO ALERT TE FLAT", isNewIn26: false },
        { playName: "SHOCK", isNewIn26: false },
        { playName: "TE CROSS", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Weak Slot Open",
      formationType: "Pistol",
      plays: [
        { playName: "COUNTER ALERT SMOKE", isNewIn26: false },
        { playName: "DEEP CURLS", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "LEAD READ OPTION", isNewIn26: false },
        { playName: "MTN FLOOD", isNewIn26: false },
        { playName: "MTN Y STICK", isNewIn26: false },
        { playName: "MTN Z UNDER", isNewIn26: false },
        { playName: "PA BOOT SLIDE", isNewIn26: false },
        { playName: "PA SHORT POST", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "Y CROSS", isNewIn26: false },
        { playName: "Z UNDER", isNewIn26: false },
        { playName: "ZONE ALERT BUBBLE", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Y Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: true },
        { playName: "CURLS", isNewIn26: false },
        { playName: "DASH FLOOD", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB POWER O", isNewIn26: false },
        { playName: "HB SLAM", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "HB WIDE ZONE WK", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "PA BOOT SLIDE", isNewIn26: false },
        { playName: "PA DOUBLE POST", isNewIn26: false },
        { playName: "PA SCISSORS", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "STRONG FLOOD", isNewIn26: false },
        { playName: "WIDE ZONE", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Y Trips",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "FLANKER UNDER", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB SLAM", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "HB ZONE", isNewIn26: false },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "INSIDE UNDER", isNewIn26: false },
        { playName: "MIDDLE READ", isNewIn26: false },
        { playName: "MTN CORNER STRIKE", isNewIn26: true },
        { playName: "MTN HB DRAW", isNewIn26: true },
        { playName: "MTN HB SLIP SCREEN", isNewIn26: true },
        { playName: "PA COMEBACKS", isNewIn26: false },
        { playName: "PA CTR WAGGLE", isNewIn26: false },
        { playName: "PA DEEP IN", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "PIN PULL SWEEP", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "READ OPTION WK", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "SMASH", isNewIn26: false },
        { playName: "STRONG POWER", isNewIn26: false },
        { playName: "WR SCREEN", isNewIn26: false },
        { playName: "Y STICK", isNewIn26: false },
        { playName: "Y TRAIL", isNewIn26: false },
      ],
    },
  ],
};
