import type { TeamPlaybookSeed } from "../types";

export const NOTRE_DAME_SEED: TeamPlaybookSeed = {
  team: "Notre Dame",
  scheme: "Power Spread",
  source: {
    url: "https://cfb.fan/26/playbooks/notre-dame-off/",
    verified: "2026-04-16",
  },
  formations: [
    {
      formation: "Wildcat Unbalanced",
      formationType: "Wildcat",
      plays: [
        { playName: "BLAST", isNewIn26: false, playType: "Inside Run" },
        { playName: "COUNTER", isNewIn26: false, playType: "Medium Pass" },
        { playName: "JET REVERSE PASS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "JET SWEEP", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA JET SWEEP", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER", isNewIn26: false, playType: "Inside Run" },
      ],
    },
    {
      formation: "Pistol U Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA BOOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA CORNER DIG", isNewIn26: false, playType: "Play Action" },
        { playName: "PA WHEEL SHOT", isNewIn26: true, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO ALERT TE FLAT", isNewIn26: false, playType: "RPO" },
        { playName: "SHOCK", isNewIn26: false, playType: "Medium Pass" },
        { playName: "TE CROSS", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Pistol Wing",
      formationType: "Pistol",
      plays: [
        { playName: "CURL COMBO", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB COUNTER", isNewIn26: true, playType: "Outside Run" },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB ZONE WK", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN HB DUO", isNewIn26: true, playType: "Inside Run" },
        { playName: "MTN HB SPLIT ZONE", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN PA BOOT LT", isNewIn26: true, playType: "Play Action" },
        { playName: "PA BOOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA BOOT LT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA TE SLIP", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "READ OPTION WK", isNewIn26: false, playType: "Option" },
        { playName: "STRONG POWER", isNewIn26: false, playType: "Inside Run" },
        { playName: "TE ATTACK", isNewIn26: false, playType: "Medium Pass" },
        { playName: "TE STICK", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Pistol Y Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "COUNTER Y", isNewIn26: true, playType: "Outside Run" },
        { playName: "DASH FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "GT COUNTER", isNewIn26: true, playType: "Medium Pass" },
        { playName: "HB SPLIT DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB SWING", isNewIn26: true, playType: "Screen" },
        { playName: "HB ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB ZONE WK", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA BOOT RT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "PA DOUBLE POST", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SCISSORS", isNewIn26: false, playType: "Play Action" },
        { playName: "PA STRETCH SHOT", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO ZONE ALERT OUT", isNewIn26: true, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Gun Bunch Str Offset",
      formationType: "Gun",
      plays: [
        { playName: "CRACK TOSS", isNewIn26: false, playType: "Outside Run" },
        { playName: "DAGGER", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DUO", isNewIn26: false, playType: "Inside Run" },
        { playName: "FK TOSS SLIDE", isNewIn26: false, playType: "Outside Run" },
        { playName: "FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB MTN QB SWEEP", isNewIn26: true, playType: "Outside Run" },
        { playName: "HB MTN QB ZONE", isNewIn26: true, playType: "Medium Pass" },
        { playName: "HB MTN TRAIL DBL POST", isNewIn26: true, playType: "Deep Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN DEEP POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "MTN INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "PIN PULL TOSS", isNewIn26: false, playType: "Outside Run" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO READ Z SPOT", isNewIn26: true, playType: "RPO" },
        { playName: "SLANT SPACING", isNewIn26: false, playType: "Quick Pass" },
        { playName: "Y TRAIL", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Bunch Str Wide",
      formationType: "Gun",
      plays: [
        { playName: "CLEAROUT FL IN", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DIG RETURN", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN BENCH", isNewIn26: true, playType: "Quick Pass" },
        { playName: "MTN BENCH CURLS", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN DAGGER", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN HB SWING", isNewIn26: true, playType: "Screen" },
        { playName: "MTN WR MID SCREEN", isNewIn26: true, playType: "Screen" },
        { playName: "MTN X REPLACE", isNewIn26: true, playType: "Medium Pass" },
        { playName: "ORBIT HB ANGLE", isNewIn26: true, playType: "Medium Pass" },
        { playName: "ORBIT LEAD SWING SPOT", isNewIn26: true, playType: "Screen" },
        { playName: "ORBIT WR SWING", isNewIn26: true, playType: "Screen" },
        { playName: "RPO PEEK POST", isNewIn26: false, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Gun Cluster",
      formationType: "Gun",
      plays: [
        { playName: "CLUSTER BUNCH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB MID DRAW", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB OFF TACKLE", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "IRISH MESH WHIP", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MESH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MESH POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "SPACING", isNewIn26: false, playType: "Medium Pass" },
        { playName: "VERTICALS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "Z SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "Z SPOT SHAKE", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Deuce",
      formationType: "Gun",
      plays: [
        { playName: "BENCH SWAP", isNewIn26: false, playType: "Medium Pass" },
        { playName: "BOUNCE INSIDE ZONE SPLIT", isNewIn26: true, playType: "Inside Run" },
        { playName: "BOUNCE OUTSIDE ZONE", isNewIn26: true, playType: "Outside Run" },
        { playName: "BOUNCE PA TE CROSS", isNewIn26: true, playType: "Medium Pass" },
        { playName: "ESCORT INSIDE ZONE SPLIT", isNewIn26: true, playType: "Inside Run" },
        { playName: "ESCORT PA SLIDE", isNewIn26: true, playType: "Medium Pass" },
        { playName: "ESCORT RPO READ FLAT WHEEL", isNewIn26: true, playType: "RPO" },
        { playName: "FK TOSS", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB TOSS", isNewIn26: false, playType: "Outside Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MESH SPOT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN HB TOSS", isNewIn26: true, playType: "Outside Run" },
        { playName: "MTN QB ZONE", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN TE WHEEL", isNewIn26: true, playType: "Medium Pass" },
        { playName: "PA SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "QB ZONE", isNewIn26: true, playType: "QB Run" },
        { playName: "RPO READ FLAT WHEEL", isNewIn26: false, playType: "RPO" },
        { playName: "SHALLOW CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Deuce Close",
      formationType: "Gun",
      plays: [
        { playName: "BENCH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "BENCH X DIG", isNewIn26: false, playType: "Medium Pass" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MESH SPOT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA DEEP OVER", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "POST WHEEL", isNewIn26: false, playType: "Deep Pass" },
        { playName: "RPO PEEK STICK", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ FLAT WHEEL", isNewIn26: false, playType: "RPO" },
        { playName: "SPACING SWITCH", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Doubles",
      formationType: "Gun",
      plays: [
        { playName: "DOUBLE SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "DRAG UNDER", isNewIn26: false, playType: "Medium Pass" },
        { playName: "FADE HB WHEEL", isNewIn26: false, playType: "Deep Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, playType: "Screen" },
        { playName: "ORBIT QB POWER RPO", isNewIn26: true, playType: "RPO" },
        { playName: "ORBIT Y SAIL", isNewIn26: true, playType: "Medium Pass" },
        { playName: "ORBIT Y STICK", isNewIn26: true, playType: "Quick Pass" },
        { playName: "PA JET SWEEP", isNewIn26: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SHOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA ZONE READ", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "REDZONE SCISSORS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SPOT DBL SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, playType: "Outside Run" },
      ],
    },
    {
      formation: "Gun Empty Trio",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CURL FLATS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DOUBLE PIVOT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HITCH CORNERS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HOSS JUKE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "JET TOUCH PASS", isNewIn26: false, playType: "Screen" },
        { playName: "MTN MESH Y-POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "ORBIT DRIVE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "ORBIT WR MID SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "RPO ORBIT QB DRAW SCREEN", isNewIn26: false, playType: "RPO" },
        { playName: "RPO SCREEN QB DRAW", isNewIn26: false, playType: "RPO" },
        { playName: "RPO SHOCK QB DRAW", isNewIn26: false, playType: "RPO" },
        { playName: "SHALLOW CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "SHOCK CORNER STRIKE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SHOCK N NOD", isNewIn26: false, playType: "Medium Pass" },
        { playName: "SHOCK SLOT OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SHOCK Y OPTION", isNewIn26: false, playType: "Option" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "WR OPTION", isNewIn26: false, playType: "Option" },
        { playName: "WR SCREENS", isNewIn26: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Flex Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "FLANKER SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN BENCH", isNewIn26: true, playType: "Quick Pass" },
        { playName: "MTN MESH Y SPOT", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN RPO ZONE SCREEN", isNewIn26: true, playType: "RPO" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA GO SLOT CROSS", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "SMASH", isNewIn26: false, playType: "Quick Pass" },
        { playName: "X DAGGER", isNewIn26: false, playType: "Medium Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Gun Normal Y Off",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "BENCH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "COUNTER Y", isNewIn26: false, playType: "Outside Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN ALL CURLS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN HB OFF TACKLE", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, playType: "Screen" },
        { playName: "MTN INSIDE ZONE", isNewIn26: true, playType: "Inside Run" },
        { playName: "MTN PA VERTICALS", isNewIn26: true, playType: "Deep Pass" },
        { playName: "MTN SPOT WHEEL", isNewIn26: false, playType: "Quick Pass" },
        { playName: "PA BOOT SHOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA BOOT Z CROSS", isNewIn26: false, playType: "Play Action" },
        { playName: "PA CROSS", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RETURN INSIDE ZONE SPLIT", isNewIn26: true, playType: "Inside Run" },
        { playName: "RETURN PA SLIDE", isNewIn26: true, playType: "Medium Pass" },
        { playName: "RPO ALERT QB POWER", isNewIn26: true, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO RETURN READ Y FLAT", isNewIn26: true, playType: "RPO" },
        { playName: "SCISSORS Z CURL", isNewIn26: true, playType: "Medium Pass" },
        { playName: "SEAM F ANGLE", isNewIn26: false, playType: "Deep Pass" },
      ],
    },
    {
      formation: "Gun Normal Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CURL COMBO", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DOUBLE SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "ESCORT CURL COMBO", isNewIn26: true, playType: "Medium Pass" },
        { playName: "ESCORT QB BLAST", isNewIn26: true, playType: "Inside Run" },
        { playName: "ESCORT SPEED OPTION", isNewIn26: true, playType: "Option" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA SLIDE", isNewIn26: true, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, playType: "Inside Run" },
        { playName: "QB G DOWN", isNewIn26: true, playType: "QB Run" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "RPO SPLIT ALERT BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "SLOT FADE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
        { playName: "WR UNDER", isNewIn26: false, playType: "Quick Pass" },
        { playName: "X DAGGER", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Spread HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DOUBLE POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "G TRAP READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "GT COUNTER BASH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "H SHALLOW CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB BASE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN DASH OVER", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN G DOWN", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN RPO ALERT QB POWER", isNewIn26: false, playType: "RPO" },
        { playName: "PA DAGGER", isNewIn26: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Gun Tight Open",
      formationType: "Gun",
      plays: [
        { playName: "BENCH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "BENCH Z SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "HB DRAW", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MESH SPOT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN SPACING HB FLAT", isNewIn26: true, playType: "Quick Pass" },
        { playName: "MTN SPOT N GO", isNewIn26: true, playType: "Deep Pass" },
        { playName: "MTN Z SPOT", isNewIn26: true, playType: "Quick Pass" },
        { playName: "PA SCISSORS", isNewIn26: true, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SLOT POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "VERTICALS HB BURST", isNewIn26: false, playType: "Deep Pass" },
      ],
    },
    {
      formation: "Gun Tight Y Off Flex",
      formationType: "Gun",
      plays: [
        { playName: "FLOOD LEVELS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: true, playType: "Inside Run" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "Y CROSS", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Trio HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER SIT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "FLOOD HB FLAT", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "IRISH CROSS SLOT SEAM", isNewIn26: false, playType: "Deep Pass" },
        { playName: "JET CHIP WASP", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA CROSS SIT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA Y CROSS", isNewIn26: false, playType: "Play Action" },
        { playName: "QB BLAST", isNewIn26: true, playType: "QB Run" },
        { playName: "QB G DOWN", isNewIn26: true, playType: "QB Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "RPO ALERT OUT", isNewIn26: false, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SPRINT RUB FLAT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SPRINT SMASH", isNewIn26: true, playType: "Quick Pass" },
        { playName: "STICKS", isNewIn26: true, playType: "Quick Pass" },
        { playName: "VERTICALS", isNewIn26: false, playType: "Deep Pass" },
      ],
    },
    {
      formation: "Gun Trips Y Over",
      formationType: "Gun",
      plays: [
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO COUNTER ALERT SHOCK", isNewIn26: false, playType: "RPO" },
        { playName: "RPO ZONE ALERT BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "RPO ZONE ALERT SHOCK", isNewIn26: false, playType: "RPO" },
        { playName: "SLOT FADE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SPRINT CORNER", isNewIn26: false, playType: "Deep Pass" },
        { playName: "VERTICALS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "Z SPOT", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Trips Y Slot Str",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER", isNewIn26: false, playType: "Medium Pass" },
        { playName: "FOUR VERTICALS", isNewIn26: true, playType: "Deep Pass" },
        { playName: "HB SWEEP", isNewIn26: false, playType: "Outside Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN CURL X POST", isNewIn26: true, playType: "Deep Pass" },
        { playName: "MTN SHOCK", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN WR MID SCREEN", isNewIn26: true, playType: "Screen" },
        { playName: "READ OPTION", isNewIn26: true, playType: "Option" },
        { playName: "RPO ALERT QB POWER WK", isNewIn26: true, playType: "RPO" },
        { playName: "RPO ALERT SHOCK", isNewIn26: false, playType: "RPO" },
        { playName: "RPO SCREEN QB DRAW", isNewIn26: true, playType: "RPO" },
        { playName: "SHOCK", isNewIn26: false, playType: "Medium Pass" },
        { playName: "SHOCK HB FLAT", isNewIn26: true, playType: "Quick Pass" },
        { playName: "SPRINT RIGHT SMASH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "SPRINT SLOT CORNER", isNewIn26: true, playType: "Deep Pass" },
      ],
    },
    {
      formation: "Gun Trips Y Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL CURL", isNewIn26: true, playType: "Medium Pass" },
        { playName: "CURLS", isNewIn26: true, playType: "Medium Pass" },
        { playName: "DEEP FLOOD", isNewIn26: true, playType: "Deep Pass" },
        { playName: "DEEP STICK", isNewIn26: true, playType: "Deep Pass" },
        { playName: "GL RUB RETURN", isNewIn26: true, playType: "Quick Pass" },
        { playName: "HB OFF TACKLE", isNewIn26: true, playType: "Outside Run" },
        { playName: "INSIDE ZONE", isNewIn26: true, playType: "Inside Run" },
        { playName: "MTN HB COUNTER", isNewIn26: true, playType: "Outside Run" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: true, playType: "Inside Run" },
        { playName: "MTN PA FLOOD", isNewIn26: true, playType: "Deep Pass" },
        { playName: "PA QB CHOICE", isNewIn26: true, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: true, playType: "Option" },
        { playName: "RPO ALERT QB COUNTER", isNewIn26: true, playType: "RPO" },
        { playName: "RPO STICK QB DRAW", isNewIn26: true, playType: "RPO" },
        { playName: "SHOCK", isNewIn26: true, playType: "Medium Pass" },
        { playName: "TRIPLE SLANT", isNewIn26: true, playType: "Option" },
        { playName: "WHIP Z POST", isNewIn26: true, playType: "Deep Pass" },
        { playName: "Y CROSS", isNewIn26: true, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Wing",
      formationType: "Gun",
      plays: [
        { playName: "DIY REVERSE", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB ANGLE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN QB G DOWN", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN QB ZONE", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN REDZONE HB SCISSORS", isNewIn26: true, playType: "Medium Pass" },
        { playName: "PA BOOT", isNewIn26: false, playType: "Play Action" },
        { playName: "QB POWER", isNewIn26: true, playType: "QB Run" },
        { playName: "QB ZONE", isNewIn26: false, playType: "QB Run" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SPOTTE SEAM", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SPRINTOUT SMASH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "TE ATTACK", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Wing Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DRIVE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET HB DUO", isNewIn26: true, playType: "Inside Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, playType: "Screen" },
        { playName: "JET POWER READ", isNewIn26: true, playType: "Inside Run" },
        { playName: "JET QB COUNTER", isNewIn26: true, playType: "Outside Run" },
        { playName: "JET SPRINT HB SLIDE", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MESH SPOT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA DOUBLE POST", isNewIn26: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "SMASH", isNewIn26: false, playType: "Quick Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false, playType: "Outside Run" },
      ],
    },
    {
      formation: "Gun Wing Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "BUCK SWEEP READ OPT", isNewIn26: false, playType: "Outside Run" },
        { playName: "DOUBLE POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DRIVE WHIP SMASH", isNewIn26: true, playType: "Medium Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MESH HB CORNER", isNewIn26: false, playType: "Deep Pass" },
        { playName: "MTN BUCK SWEEP", isNewIn26: true, playType: "Outside Run" },
        { playName: "MTN HB BASE", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN MESH TRAFFIC", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN PA CROSS", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN QB G DOWN", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN QB LEAD", isNewIn26: true, playType: "Inside Run" },
        { playName: "PA DAGGER", isNewIn26: false, playType: "Play Action" },
        { playName: "QB WRAP", isNewIn26: false, playType: "QB Run" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "RPO PEEK POST", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: true, playType: "RPO" },
        { playName: "RPO SWEEP PEEK", isNewIn26: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "TE LEAD READ OPT", isNewIn26: false, playType: "Inside Run" },
      ],
    },
    {
      formation: "Gun Wing Tight Z",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, playType: "Inside Run" },
        { playName: "DUO", isNewIn26: false, playType: "Inside Run" },
        { playName: "GOAL LINE FADE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB PUNCH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MESH SPOT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA FLANKER CURL", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO GLANCE POST", isNewIn26: false, playType: "RPO" },
        { playName: "Z MTN DUO", isNewIn26: false, playType: "Inside Run" },
        { playName: "Z MTN INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "Z MTN PA CROSSERS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "ZONE OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Gun Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "BOUNCE INSIDE ZONE SPLIT", isNewIn26: true, playType: "Inside Run" },
        { playName: "BOUNCE OUTSIDE ZONE", isNewIn26: true, playType: "Outside Run" },
        { playName: "BOUNCE PA DEEP OUT", isNewIn26: true, playType: "Deep Pass" },
        { playName: "COUNTER Y", isNewIn26: false, playType: "Outside Run" },
        { playName: "COUNTER Y READ OPTION", isNewIn26: true, playType: "Option" },
        { playName: "CURLS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "FLOOD HB SWING", isNewIn26: false, playType: "Screen" },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA DOUBLE POST", isNewIn26: false, playType: "Play Action" },
        { playName: "PA Y FLOOD", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO X CLOSE DUO BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "SHOT SLOT POCO", isNewIn26: false, playType: "Medium Pass" },
        { playName: "X CLOSE HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "X CLOSE PA SLANTS", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Y Off Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DIG CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "HI LO DIG", isNewIn26: false, playType: "Medium Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN HB SWING", isNewIn26: false, playType: "Screen" },
        { playName: "MTN PUMP AND GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "MTN Z SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO ALERT COUNTER HITCH", isNewIn26: true, playType: "RPO" },
        { playName: "RPO ALERT HITCHES", isNewIn26: false, playType: "RPO" },
        { playName: "SLOT FADE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Gun Y Trips Offset",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false, playType: "Inside Run" },
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "COMEBACKS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "COUNTER TREY", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "LEVELS SWITCH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "PA READ SMASH", isNewIn26: false, playType: "Play Action" },
        { playName: "PA ZONE SHOT", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO BUBBLE Y POP", isNewIn26: false, playType: "RPO" },
        { playName: "RPO GLANCE POST", isNewIn26: false, playType: "RPO" },
        { playName: "RPO POWER ALERT HITCHES", isNewIn26: true, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, playType: "RPO" },
        { playName: "SLOT DRIVE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "SPRINTOUT SMASH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "Y CORNER", isNewIn26: false, playType: "Deep Pass" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SPLIT O", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB STING", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA POWER O", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "QB SNEAK", isNewIn26: false, playType: "QB Run" },
        { playName: "STRONG TOSS", isNewIn26: false, playType: "Outside Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HAIL MARY", isNewIn26: false, playType: "Medium Pass" },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
  ],
};
