import type { TeamPlaybookSeed } from "../types";

export const OHIO_SEED: TeamPlaybookSeed = {
  team: "Ohio",
  scheme: "Pistol",
  sideOfBall: 'offense',
  source: {
    url: "https://cfb.fan/26/playbooks/ohio-off/",
    verified: "2026-04-21",
  },
  formations: [
    {
      formation: "Pistol Ace",
      formationType: "Pistol",
      plays: [
        { playName: "FL CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "PA BOOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA CTR WAGGLE", isNewIn26: false, playType: "Play Action" },
        { playName: "PA DEEP IN", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Pistol Full House Tight",
      formationType: "Pistol",
      plays: [
        { playName: "COUNTER LEAD", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN DUO", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA CROSSERS", isNewIn26: false, playType: "Play Action" },
        { playName: "PA FLOOD FB SLIP", isNewIn26: false, playType: "Play Action" },
        { playName: "PA TE CORNER", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Pistol Wing",
      formationType: "Pistol",
      plays: [
        { playName: "HB COUNTER", isNewIn26: true },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "MTN HB ZONE", isNewIn26: true },
        { playName: "MTN PA CROSS", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN POWER O", isNewIn26: true, playType: "Inside Run" },
        { playName: "PA BOOT HB WHEEL", isNewIn26: true, playType: "Play Action" },
        { playName: "PA BOOT LT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA COUNTER Y SCREEN", isNewIn26: true, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "READ OPTION WK", isNewIn26: false, playType: "Option" },
        { playName: "TE ATTACK", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Wing Slot",
      formationType: "Pistol",
      plays: [
        { playName: "DAGGER", isNewIn26: false },
        { playName: "FOUR VERTICALS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "PA BOOT LT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA DEEP OUT", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION WK", isNewIn26: false, playType: "Option" },
        { playName: "Y STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Y Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "COUNTER Y", isNewIn26: true },
        { playName: "CURLS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DASH FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "PA DOUBLE POST", isNewIn26: false, playType: "Play Action" },
        { playName: "PA STRETCH SHOT", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO ZONE X GLANCE", isNewIn26: false, playType: "RPO" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "WIDE ZONE", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Gun Deuce",
      formationType: "Gun",
      plays: [
        { playName: "01 TRAP", isNewIn26: false },
        { playName: "BENCH SWAP", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "FK TOSS", isNewIn26: false, playType: "Outside Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MESH SPOT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA SHALLOW CROSS", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "ZONE TOSS", isNewIn26: false, playType: "Outside Run" },
      ],
    },
    {
      formation: "Gun Doubles Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CURL FLAT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "RPO ALERT HITCHES", isNewIn26: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, playType: "RPO" },
        { playName: "SLOT FADE", isNewIn26: false, playType: "Deep Pass" },
      ],
    },
    {
      formation: "Gun Normal Y Off Close",
      formationType: "Gun",
      plays: [
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, playType: "Screen" },
        { playName: "PA JET SWEEP", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO ALERT OUT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO GLANCE POST", isNewIn26: false, playType: "RPO" },
        { playName: "Y-SAIL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, playType: "Quick Pass" },
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "BUBBLE SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "CURLS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA MIDDLE", isNewIn26: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "SLANT SPACING", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Gun Trips TE Offset Wk",
      formationType: "Gun",
      plays: [
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, playType: "Screen" },
        { playName: "HB POWER", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MIDDLE SLANT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA FLOOD", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "VERTICALS", isNewIn26: false, playType: "Deep Pass" },
      ],
    },
    {
      formation: "Gun Wing Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "01 TRAP", isNewIn26: false },
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DRIVE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Tight Z",
      formationType: "Gun",
      plays: [
        { playName: "01 TRAP", isNewIn26: false },
        { playName: "DUO", isNewIn26: false, playType: "Inside Run" },
        { playName: "GOAL LINE FADE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB PUNCH", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MESH SPOT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA FLANKER CURL", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO GLANCE POST", isNewIn26: false, playType: "RPO" },
        { playName: "ZONE OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB COUNTER WK", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SPLIT O", isNewIn26: false },
        { playName: "HB STING", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "QB SNEAK", isNewIn26: false, playType: "QB Run" },
        { playName: "STRONG TOSS", isNewIn26: false, playType: "Outside Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HAIL MARY", isNewIn26: false },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false },
      ],
    },
  ],
};
