import type { TeamPlaybookSeed } from "../types";

export const OKLAHOMA_STATE_SEED: TeamPlaybookSeed = {
  team: "Oklahoma State",
  scheme: "Power Spread",
  source: {
    url: "https://cfb.fan/26/playbooks/oklahoma-state-off/",
    verified: "2026-05-02",
  },
  formations: [
    {
      formation: "Singleback Y Trips X Off",
      formationType: "Singleback",
      plays: [
        { playName: "JET HB COUNTER", isNewIn26: false },
        { playName: "JET HB POWER", isNewIn26: false },
        { playName: "JET PA CROSS", isNewIn26: false },
        { playName: "JET PA POWER", isNewIn26: false },
        { playName: "JET SWEEP", isNewIn26: false },
        { playName: "JET WIDE ZONE WK", isNewIn26: false },
        { playName: "MTN ROLLOUT SPOT", isNewIn26: false },
        { playName: "MTN SPEED OPTION", isNewIn26: false },
        { playName: "MTN THROWBACK SCREEN", isNewIn26: false },
      ],
    },
    {
      formation: "I Form Tight",
      formationType: "I Form",
      plays: [
        { playName: "26 DUO", isNewIn26: false },
        { playName: "FB DIVE", isNewIn26: false },
        { playName: "FB FAKE HB TOSS", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB LEAD", isNewIn26: false },
        { playName: "HB POWER O", isNewIn26: false },
        { playName: "HB STRETCH ALERT U POP", isNewIn26: false },
        { playName: "PA CTR SHOT", isNewIn26: false },
        { playName: "PA HB WHEEL", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false },
        { playName: "Y-DIG", isNewIn26: false },
        { playName: "Z SLANT", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Deuce",
      formationType: "Pistol",
      plays: [
        { playName: "BENCH", isNewIn26: false },
        { playName: "CORNER POST", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "HITCH CORNERS", isNewIn26: false },
        { playName: "INSIDE CROSS", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "PA DEEP IN", isNewIn26: false },
        { playName: "RPO ALERT WHEEL", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Doubles Y Off",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "HB SPLIT DIVE", isNewIn26: false },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "JET HB SPLIT DIVE", isNewIn26: false },
        { playName: "JET PA CROSS", isNewIn26: false },
        { playName: "JET PA X POCO", isNewIn26: false },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "PA CROSS", isNewIn26: false },
        { playName: "PA OUT N UPS", isNewIn26: false },
        { playName: "PA SLOT CROSS", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO ALERT JET SLANT", isNewIn26: false },
        { playName: "RPO ALERT POWER", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
        { playName: "ZONE SPLIT", isNewIn26: false },
        { playName: "ZOUT", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Full Diamond",
      formationType: "Pistol",
      plays: [
        { playName: "CURL FLAT", isNewIn26: false },
        { playName: "HB DOUBLE ISO", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "MTN HB SPLIT DIVE", isNewIn26: false },
        { playName: "MTN HB STRETCH", isNewIn26: false },
        { playName: "MTN PA BOOT", isNewIn26: false },
        { playName: "MTN PA WHEEL", isNewIn26: false },
        { playName: "MTN READ OPTION", isNewIn26: false },
        { playName: "PA FLOOD", isNewIn26: false },
        { playName: "PA Z POST", isNewIn26: false },
        { playName: "RPO ALERT HITCHES", isNewIn26: false },
        { playName: "RPO ALERT MTN SLANT", isNewIn26: false },
        { playName: "RPO GLANCE CURL", isNewIn26: false },
        { playName: "RPO GLANCE DOUBLE GO", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Full House TE",
      formationType: "Pistol",
      plays: [
        { playName: "COUNTER LEAD", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "MTN O 1 TRAP", isNewIn26: false },
        { playName: "MTN PA POWER CROSS", isNewIn26: false },
        { playName: "MTN POWER O", isNewIn26: false },
        { playName: "PA COMEBACK", isNewIn26: false },
        { playName: "PA TE CORNER", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "X SLANT", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Open Flex",
      formationType: "Pistol",
      plays: [
        { playName: "COUNTER F", isNewIn26: false },
        { playName: "F LEAD READ OPTION", isNewIn26: false },
        { playName: "FL SCREEN", isNewIn26: false },
        { playName: "GT COUNTER", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "PA BOOT", isNewIn26: false },
        { playName: "PA BOOT RT", isNewIn26: false },
        { playName: "PA DOUBLE POST", isNewIn26: false },
        { playName: "PA X SLANT", isNewIn26: false },
        { playName: "VERTICALS", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Spread Y Slot",
      formationType: "Pistol",
      plays: [
        { playName: "FADE SMASH", isNewIn26: false },
        { playName: "FOUR VERTICALS", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLAM", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "JET PA BOOT", isNewIn26: false },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "MTN PA BOOT", isNewIn26: false },
        { playName: "MTN SPLIT DIVE", isNewIn26: false },
        { playName: "MTN ZONE SPLIT", isNewIn26: false },
        { playName: "PA CORNER SPOT", isNewIn26: false },
        { playName: "RPO ALERT HITCHES", isNewIn26: false },
        { playName: "SLOT OUTSIDE", isNewIn26: false },
        { playName: "Y CROSS", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Strong Slot Open",
      formationType: "Pistol",
      plays: [
        { playName: "F LEAD READ OPTION", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "MESH", isNewIn26: false },
        { playName: "MESH DIG", isNewIn26: false },
        { playName: "MID SLANTS", isNewIn26: false },
        { playName: "PA SLIDE", isNewIn26: false },
        { playName: "SCAT", isNewIn26: false },
        { playName: "SHAKES", isNewIn26: false },
        { playName: "STRETCH ALERT X LOOKIE", isNewIn26: false },
        { playName: "Y CORNER", isNewIn26: false },
        { playName: "Y CROSS", isNewIn26: false },
        { playName: "ZONE ALERT BUBBLE", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Weak Slot Open",
      formationType: "Pistol",
      plays: [
        { playName: "DEEP CURLS", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "LEAD READ OPTION", isNewIn26: false },
        { playName: "MTN FLOOD", isNewIn26: false },
        { playName: "MTN Y STICK", isNewIn26: false },
        { playName: "MTN Z UNDER", isNewIn26: false },
        { playName: "PA BOOT SLIDE", isNewIn26: false },
        { playName: "PA SHORT POST", isNewIn26: false },
        { playName: "PA SLOT POST", isNewIn26: false },
        { playName: "SHALLOW CROSS", isNewIn26: false },
        { playName: "Y CROSS", isNewIn26: false },
        { playName: "Z UNDER", isNewIn26: false },
        { playName: "ZONE ALERT SMOKE", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Y Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB POWER O", isNewIn26: false },
        { playName: "HB SPLIT DIVE", isNewIn26: false },
        { playName: "HB WIDE ZONE WK", isNewIn26: false },
        { playName: "HB ZONE", isNewIn26: false },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "PA SCISSORS", isNewIn26: false },
        { playName: "PA SLOT POST-CORNER", isNewIn26: false },
        { playName: "PA SLOT SEAM", isNewIn26: false },
        { playName: "PA STRETCH SHOT", isNewIn26: false },
        { playName: "ROLLOUT FLOOD", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO ALERT SLANT", isNewIn26: false },
        { playName: "RPO GLANCE POST BUBBLE", isNewIn26: false },
        { playName: "RPO READ Y SLIDE", isNewIn26: false },
        { playName: "STRONG FLOOD", isNewIn26: false },
        { playName: "WIDE ZONE", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Gun 5WR",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CROSS Z DIG", isNewIn26: false },
        { playName: "DEEP DIVIDE", isNewIn26: false },
        { playName: "DOUBLE PIVOT", isNewIn26: false },
        { playName: "QB DRAW", isNewIn26: false },
        { playName: "QUICK SLANTS", isNewIn26: false },
        { playName: "SCISSORS", isNewIn26: false },
        { playName: "SHALLOW CROSS", isNewIn26: false },
        { playName: "SLOT SCREEN", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "WR SCREENS", isNewIn26: false },
        { playName: "Z SCREEN", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Bunch HB Str",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "CURL FLAT", isNewIn26: false },
        { playName: "DRIVE", isNewIn26: false },
        { playName: "DURHAM", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MESH FLAT SPOT", isNewIn26: false },
        { playName: "PA BUNCH SHOT", isNewIn26: false },
        { playName: "PA WR IN", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "SEATTLE", isNewIn26: false },
        { playName: "SPACING", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Bunch Trio Open",
      formationType: "Gun",
      plays: [
        { playName: "FAKE SCREEN VERTICALS", isNewIn26: false },
        { playName: "FOUR VERTICALS", isNewIn26: false },
        { playName: "HB CROSS SCREEN", isNewIn26: false },
        { playName: "RPO ALERT WR SCREEN", isNewIn26: false },
        { playName: "RPO READ WR SCREEN", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Deuce",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false },
        { playName: "BENCH SWAP", isNewIn26: false },
        { playName: "CORNER GOS FLAT", isNewIn26: false },
        { playName: "DOUBLE GO", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "LEAD READ OPTION", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "PA SHALLOW CROSS", isNewIn26: false },
        { playName: "PA SLIDE", isNewIn26: false },
        { playName: "SHALLOW CROSS", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Deuce Close",
      formationType: "Gun",
      plays: [
        { playName: "BENCH", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "LEAD READ OPTION", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA DEEP CROSS", isNewIn26: false },
        { playName: "PA DEEP OVER", isNewIn26: false },
        { playName: "PA SLIDE", isNewIn26: false },
        { playName: "POST WHEEL", isNewIn26: false },
        { playName: "SPACING SWITCH", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Doubles Flex Wk",
      formationType: "Gun",
      plays: [
        { playName: "MTN HB SWEEP", isNewIn26: false },
        { playName: "MTN PA RETURN", isNewIn26: false },
        { playName: "MTN SLOT CORNER", isNewIn26: false },
        { playName: "MTN SLOT CROSS", isNewIn26: false },
        { playName: "MTN SLOT OUT", isNewIn26: false },
        { playName: "RPO ALERT POWER", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Empty Quads",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CROSS Z POST", isNewIn26: false },
        { playName: "CURL PIVOT DIG", isNewIn26: false },
        { playName: "OUT DOUBLE UNDER", isNewIn26: false },
        { playName: "QB DRAW", isNewIn26: false },
        { playName: "WR SCREEN", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Normal Y Off",
      formationType: "Gun",
      plays: [
        { playName: "BENCH", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "DEEP CROSS SHOT", isNewIn26: false },
        { playName: "FAKE JET HB SEAM", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET COUNTER Y", isNewIn26: false },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "PA DEEP CROSS", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
        { playName: "PA SHALLOW CROSS", isNewIn26: false },
        { playName: "PA SLOT POST", isNewIn26: false },
        { playName: "Y CROSS", isNewIn26: false },
        { playName: "Y DEEP CROSS", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Slot Left Wk",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "CURLS", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "PA POST CURLS", isNewIn26: false },
        { playName: "PA SLIDE", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO GLANCE POST", isNewIn26: false },
        { playName: "RPO PEEK POST", isNewIn26: false },
        { playName: "RPO READ BUBBLE", isNewIn26: false },
        { playName: "RPO SPLIT ALERT BUBBLE", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "VERTICAL TE CROSS", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Split Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER TREY", isNewIn26: false },
        { playName: "FLOOD", isNewIn26: false },
        { playName: "HB CROSS BUCK", isNewIn26: false },
        { playName: "HB OFF TACKLE", isNewIn26: false },
        { playName: "HB SLIP SCREEN STR", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "MTN DOUBLE PASS", isNewIn26: false },
        { playName: "MTN FB CROSS SCREEN", isNewIn26: false },
        { playName: "MTN LEAD SWING SPOT", isNewIn26: false },
        { playName: "MTN PA HB SWING", isNewIn26: false },
        { playName: "MTN RPO PEEK SWING", isNewIn26: false },
        { playName: "MTN RPO SWING QB DRAW", isNewIn26: false },
        { playName: "MTN SPOT", isNewIn26: false },
        { playName: "MTN TRIPLE OPTION RT", isNewIn26: false },
        { playName: "MTN Y CROSS", isNewIn26: false },
        { playName: "PA HB SEAM", isNewIn26: false },
        { playName: "RPO SPLIT ALERT SCREEN", isNewIn26: false },
        { playName: "SHAKES", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Spread",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false },
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CROSS Z DIG", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MESH", isNewIn26: false },
        { playName: "OUTSIDE COMEBACKS", isNewIn26: false },
        { playName: "PA COMEBACKS", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO ALERT WR SCREENS", isNewIn26: false },
        { playName: "SMASH", isNewIn26: false },
        { playName: "WR SCREEN", isNewIn26: false },
        { playName: "Y CROSS", isNewIn26: false },
        { playName: "Y SHALLOW CROSS", isNewIn26: false },
        { playName: "Y STICK", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Spread Y-Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "CURL COMBO", isNewIn26: false },
        { playName: "DAGGER", isNewIn26: false },
        { playName: "DOUBLE SLANTS", isNewIn26: false },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "HITCH DIG", isNewIn26: false },
        { playName: "INSIDE CROSS", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MTN HB COUNTER", isNewIn26: false },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "MTN PA CROSS", isNewIn26: false },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO ALERT DRAW STICK", isNewIn26: false },
        { playName: "RPO READ BUBBLE", isNewIn26: false },
        { playName: "SLOT FLAGS", isNewIn26: false },
        { playName: "SLOT OUTS", isNewIn26: false },
        { playName: "WR UNDER", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trey Open Offset",
      formationType: "Gun",
      plays: [
        { playName: "AIR RAID STICK", isNewIn26: false },
        { playName: "CROSS Z CURL", isNewIn26: false },
        { playName: "HB OFF TACKLE", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE SEAM", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MESH", isNewIn26: false },
        { playName: "MESH WHEEL", isNewIn26: false },
        { playName: "MTN HB SWING", isNewIn26: false },
        { playName: "MTN INSIDE CROSS", isNewIn26: false },
        { playName: "MTN SPOT Y CORNER", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT X OUT", isNewIn26: false },
        { playName: "SHOCK H OPTION", isNewIn26: false },
        { playName: "WR MID SCREEN", isNewIn26: false },
        { playName: "Y CORNER", isNewIn26: false },
        { playName: "Y CROSS FLOOD", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false },
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CURL POST WHEEL", isNewIn26: false },
        { playName: "FK SLOT SCREEN WHEEL", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "HB SWEEP", isNewIn26: false },
        { playName: "HB SWING", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "RPO ALERT SLOT SCREEN", isNewIn26: false },
        { playName: "RPO GLANCE BUBBLE", isNewIn26: false },
        { playName: "SLOT DRIVE", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "STRONG FLOOD", isNewIn26: false },
        { playName: "SWITCH VERTS", isNewIn26: false },
        { playName: "TRIPS CROSS", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
        { playName: "Z UNDER", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "DRAGON STICK", isNewIn26: false },
        { playName: "DRIVE", isNewIn26: false },
        { playName: "HB DIRECT", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB OFF TACKLE", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE SWITCH", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "LEVELS", isNewIn26: false },
        { playName: "LEVELS SWITCH", isNewIn26: false },
        { playName: "MESH", isNewIn26: false },
        { playName: "MESH WHEEL", isNewIn26: false },
        { playName: "PA WR IN", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "SHALLOW CROSS SCREEN", isNewIn26: false },
        { playName: "SMASH", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "TRIPS CROSS", isNewIn26: false },
        { playName: "WR MID SCREEN", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips TE",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false },
        { playName: "DRIVE POST", isNewIn26: false },
        { playName: "FLOOD", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MTN BENCH", isNewIn26: false },
        { playName: "MTN RETURN LEVELS", isNewIn26: false },
        { playName: "MTN Z SPOT", isNewIn26: false },
        { playName: "RPO ALERT CNTR FLAT", isNewIn26: false },
        { playName: "TEXAS", isNewIn26: false },
        { playName: "VERTICALS", isNewIn26: false },
        { playName: "WR SCREEN", isNewIn26: false },
        { playName: "X SPOT", isNewIn26: false },
        { playName: "Y SHALLOW CROSS", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CURLS", isNewIn26: false },
        { playName: "HB SWING", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "POST-CURL", isNewIn26: false },
        { playName: "RPO ALERT OUT", isNewIn26: false },
        { playName: "RPO ALERT POST", isNewIn26: false },
        { playName: "RPO BUBBLE Y POP", isNewIn26: false },
        { playName: "RPO READ Y FLAT", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "STICK N NOD", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "619 SAIL", isNewIn26: false },
        { playName: "ALL GO", isNewIn26: false },
        { playName: "BUCK SWEEP", isNewIn26: false },
        { playName: "DASH FLOOD", isNewIn26: false },
        { playName: "DASH SWITCH", isNewIn26: false },
        { playName: "DASH SWITCH CURLS", isNewIn26: false },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "PA SLOT SEAM", isNewIn26: false },
        { playName: "RPO ALERT OUT", isNewIn26: false },
        { playName: "RPO ALERT SLANT", isNewIn26: false },
        { playName: "SLOT CROSS", isNewIn26: false },
        { playName: "SLOT SCREEN", isNewIn26: false },
        { playName: "SLOT WHEEL", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "SWITCH COMEBACK", isNewIn26: false },
        { playName: "WR MID SCREEN", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
        { playName: "Z DIG", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE", isNewIn26: false },
        { playName: "HB COUNTER WK", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB SPLIT O", isNewIn26: false },
        { playName: "HB STING", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false },
        { playName: "PA SPOT", isNewIn26: false },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false },
        { playName: "PA WAGGLE", isNewIn26: false },
        { playName: "POWER O", isNewIn26: false },
        { playName: "QB SNEAK", isNewIn26: false },
        { playName: "STRONG TOSS", isNewIn26: false },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false },
        { playName: "HAIL MARY", isNewIn26: false },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false },
      ],
    },
  ],
};
