import type { TeamPlaybookSeed } from "../types";

export const OREGON_STATE_SEED: TeamPlaybookSeed = {
  team: "Oregon State",
  scheme: "Power Spread",
  source: {
    url: "https://cfb.fan/26/playbooks/oregon-state-off/",
    verified: "2026-04-21",
  },
  formations: [
    {
      formation: "I Form Tight",
      formationType: "I Form",
      plays: [
        { playName: "26 DUO", isNewIn26: false, playType: "Inside Run" },
        { playName: "FB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB ISO", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB LEAD TOSS", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA BOOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, playType: "Play Action" },
        { playName: "PA TE CORNER", isNewIn26: false, playType: "Play Action" },
        { playName: "Z SLANT", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Pistol Ace",
      formationType: "Pistol",
      plays: [
        { playName: "FL CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "PA BOOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA CTR WAGGLE", isNewIn26: false, playType: "Play Action" },
        { playName: "PA DEEP IN", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Pistol Wing Slot",
      formationType: "Pistol",
      plays: [
        { playName: "DAGGER", isNewIn26: false },
        { playName: "FOUR VERTICALS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "PA BOOT LT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA DEEP OUT", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION WK", isNewIn26: false, playType: "Option" },
        { playName: "Y STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Y Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CURLS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DASH FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "PA DOUBLE POST", isNewIn26: false, playType: "Play Action" },
        { playName: "PA STRETCH SHOT", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO ZONE X GLANCE", isNewIn26: false, playType: "RPO" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "WIDE ZONE", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Gun Bunch Open Offset",
      formationType: "Gun",
      plays: [
        { playName: "FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "LEAD SWING SPOT", isNewIn26: true, playType: "Screen" },
        { playName: "MESH CORNER", isNewIn26: false, playType: "Deep Pass" },
        { playName: "RPO ALERT OUT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO ALERT SCREEN", isNewIn26: false, playType: "RPO" },
        { playName: "RPO PEEK WR SCREEN", isNewIn26: false, playType: "RPO" },
        { playName: "Z SPOT", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Deuce",
      formationType: "Gun",
      plays: [
        { playName: "01 TRAP", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "FK TOSS", isNewIn26: false, playType: "Outside Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MESH SPOT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA SHALLOW CROSS", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "ZONE TOSS", isNewIn26: false, playType: "Outside Run" },
      ],
    },
    {
      formation: "Gun Normal Y Off Close",
      formationType: "Gun",
      plays: [
        { playName: "CHEAT INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "CHEAT SLOT FADE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN HB SWING", isNewIn26: false, playType: "Screen" },
        { playName: "PA JET SWEEP", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO ALERT OUT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO GLANCE POST", isNewIn26: false, playType: "RPO" },
        { playName: "Y-SAIL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "BUBBLE SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "DEEP STICK", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA QB CHOICE", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SHOCK H OPTION", isNewIn26: false, playType: "Option" },
        { playName: "TRIPS DASH FLOOD", isNewIn26: false, playType: "Deep Pass" },
      ],
    },
    {
      formation: "Gun Trips TE Offset Wk",
      formationType: "Gun",
      plays: [
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, playType: "Screen" },
        { playName: "HB POWER", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MIDDLE SLANT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA FLOOD", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ WR SCREEN", isNewIn26: false, playType: "RPO" },
        { playName: "VERTICALS", isNewIn26: false, playType: "Deep Pass" },
      ],
    },
    {
      formation: "Gun Wing Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "01 TRAP", isNewIn26: false },
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DRIVE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "BUCK SWEEP", isNewIn26: false, playType: "Outside Run" },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA DEEP CROSS", isNewIn26: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO ALERT SLANT", isNewIn26: false, playType: "RPO" },
        { playName: "SHOT Y WHEEL", isNewIn26: false },
        { playName: "SLOT CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: true, playType: "Option" },
        { playName: "Z DIG", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB COUNTER WK", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SPLIT O", isNewIn26: false },
        { playName: "HB STING", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "QB SNEAK", isNewIn26: false, playType: "QB Run" },
        { playName: "STRONG TOSS", isNewIn26: false, playType: "Outside Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HAIL MARY", isNewIn26: false },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false },
      ],
    },
  ],
};
