import type { TeamPlaybookSeed } from "../types";

export const PENN_STATE_SEED: TeamPlaybookSeed = {
  team: "Penn State",
  scheme: "Power Spread",
  sideOfBall: 'offense',
  source: {
    url: "https://cfb.fan/26/playbooks/penn-state-off/",
    verified: "2026-04-16",
  },
  formations: [
    {
      formation: "Wildcat Trips TE",
      formationType: "Wildcat",
      plays: [
        { playName: "FOLLOW", isNewIn26: true, playType: "Medium Pass" },
        { playName: "PA DOUBLE POST", isNewIn26: true, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: true, playType: "Play Action" },
        { playName: "PA Y SCREEN", isNewIn26: true, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: true, playType: "Inside Run" },
        { playName: "QB POWER", isNewIn26: true, playType: "QB Run" },
        { playName: "QB SWEEP", isNewIn26: true, playType: "QB Run" },
        { playName: "QB WRAP", isNewIn26: true, playType: "QB Run" },
        { playName: "QB ZONE", isNewIn26: true, playType: "QB Run" },
        { playName: "READ OPTION", isNewIn26: true, playType: "Option" },
        { playName: "RPO ALERT Y FLAT", isNewIn26: true, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: true, playType: "Option" },
      ],
    },
    {
      formation: "Wildcat Wing Flex",
      formationType: "Wildcat",
      plays: [
        { playName: "BLAST", isNewIn26: true, playType: "Inside Run" },
        { playName: "HB DIRECT SNAP", isNewIn26: true, playType: "Inside Run" },
        { playName: "POWER", isNewIn26: true, playType: "Inside Run" },
        { playName: "POWER G", isNewIn26: true, playType: "Inside Run" },
        { playName: "RPO COUNTER TE FLAT", isNewIn26: true, playType: "RPO" },
        { playName: "RPO POWER HB SWING", isNewIn26: true, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: true, playType: "Option" },
        { playName: "SPOT", isNewIn26: true, playType: "Quick Pass" },
        { playName: "STICK", isNewIn26: true, playType: "Quick Pass" },
        { playName: "SWEEP", isNewIn26: true, playType: "Outside Run" },
        { playName: "VERTICALS", isNewIn26: true, playType: "Deep Pass" },
        { playName: "ZONE", isNewIn26: true, playType: "Inside Run" },
      ],
    },
    {
      formation: "Wildcat Wing Trips Wk",
      formationType: "Wildcat",
      plays: [
        { playName: "BUCK SWEEP", isNewIn26: true, playType: "Outside Run" },
        { playName: "BUCK SWEEP READ OPT", isNewIn26: true, playType: "Outside Run" },
        { playName: "COUNTER WRAP", isNewIn26: true, playType: "Medium Pass" },
        { playName: "FOLLOW", isNewIn26: true, playType: "Medium Pass" },
        { playName: "GT WRAP", isNewIn26: true, playType: "Medium Pass" },
        { playName: "HB BASE", isNewIn26: true, playType: "Inside Run" },
        { playName: "HB STRETCH", isNewIn26: true, playType: "Outside Run" },
        { playName: "PA INVERTED VEER", isNewIn26: true, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: true, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: true, playType: "Inside Run" },
        { playName: "READ OPTION", isNewIn26: true, playType: "Option" },
        { playName: "Y LEAD READ OPTION", isNewIn26: true, playType: "Option" },
      ],
    },
    {
      formation: "Pistol Doubles Y Off",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB ZONE WK", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET PA CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "JET PA HB SCREEN", isNewIn26: true, playType: "Screen" },
        { playName: "JET PA SLOT SCREEN", isNewIn26: true, playType: "Screen" },
        { playName: "JET PASS FK ZONE", isNewIn26: false, playType: "Screen" },
        { playName: "PA BOOT HB WHEEL", isNewIn26: true, playType: "Play Action" },
        { playName: "PA CROSS", isNewIn26: false, playType: "Play Action" },
        { playName: "PA X DEEP IN", isNewIn26: true, playType: "Play Action" },
        { playName: "RPO ALERT JET SLANT", isNewIn26: false, playType: "RPO" },
        { playName: "ZONE FAKE JET", isNewIn26: false, playType: "Outside Run" },
      ],
    },
    {
      formation: "Pistol Full Diamond",
      formationType: "Pistol",
      plays: [
        { playName: "CURL FLAT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DBL MTN PA Z COMEBACK", isNewIn26: true, playType: "Medium Pass" },
        { playName: "DBL MTN RPO SPLIT FLAT", isNewIn26: true, playType: "RPO" },
        { playName: "DBL MTN RPO SPLIT SLANT", isNewIn26: true, playType: "RPO" },
        { playName: "HB DOUBLE ISO", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA FLOOD", isNewIn26: false, playType: "Play Action" },
        { playName: "PA Z POST", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO ALERT HITCHES", isNewIn26: false, playType: "RPO" },
        { playName: "RPO GLANCE CURL", isNewIn26: false, playType: "RPO" },
        { playName: "RPO PEEK SPLIT FLAT", isNewIn26: true, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Pistol U Off Twins Over",
      formationType: "Pistol",
      plays: [
        { playName: "HB SPLIT DIVE", isNewIn26: true, playType: "Inside Run" },
        { playName: "LEAD RD TRIPLE OPTN", isNewIn26: true, playType: "Option" },
        { playName: "LEAD READ OPTION", isNewIn26: true, playType: "Option" },
        { playName: "MTN HB DUO", isNewIn26: true, playType: "Inside Run" },
        { playName: "MTN HB POWER", isNewIn26: true, playType: "Inside Run" },
        { playName: "MTN PA Y CORNER", isNewIn26: true, playType: "Deep Pass" },
        { playName: "PA BOOT", isNewIn26: true, playType: "Play Action" },
        { playName: "PA TE SLIP", isNewIn26: true, playType: "Play Action" },
        { playName: "PA Z SPOT", isNewIn26: true, playType: "Play Action" },
        { playName: "READ OPTION WK", isNewIn26: true, playType: "Option" },
        { playName: "RPO READ TE SLIDE", isNewIn26: true, playType: "RPO" },
        { playName: "SPLIT ZONE WK", isNewIn26: true, playType: "Inside Run" },
      ],
    },
    {
      formation: "Pistol Wing Slot Over",
      formationType: "Pistol",
      plays: [
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA DOUBLE POST", isNewIn26: false, playType: "Play Action" },
        { playName: "PA STRETCH SHOT", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "READ OPTION WK", isNewIn26: false, playType: "Option" },
        { playName: "ROLLOUT FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "RPO ALERT DIVE FLAT", isNewIn26: true, playType: "RPO" },
        { playName: "SPLIT ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "WIDE ZONE", isNewIn26: false, playType: "Outside Run" },
      ],
    },
    {
      formation: "Pistol Y Off Trips Heavy",
      formationType: "Pistol",
      plays: [
        { playName: "ESCORT HB SPLIT ZONE", isNewIn26: true, playType: "Medium Pass" },
        { playName: "ESCORT LEAD READ OPTN", isNewIn26: true, playType: "Inside Run" },
        { playName: "ESCORT PA BOOT RT", isNewIn26: true, playType: "Play Action" },
        { playName: "ESCORT PA Y CORNER", isNewIn26: true, playType: "Deep Pass" },
        { playName: "ESCORT PA Y CROSS", isNewIn26: true, playType: "Medium Pass" },
        { playName: "ESCORT SPLIT DIVE", isNewIn26: true, playType: "Inside Run" },
      ],
    },
    {
      formation: "Gun Bunch Quads Open",
      formationType: "Gun",
      plays: [
        { playName: "ALL CURL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "BUNCH TRAIL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "QB BLAST", isNewIn26: false, playType: "QB Run" },
        { playName: "RPO Q SCREEN DRAW", isNewIn26: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Bunch Str Wide",
      formationType: "Gun",
      plays: [
        { playName: "CLEAROUT FL IN", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DIG RETURN", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB CROSS SCREEN", isNewIn26: true, playType: "Screen" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "LEAD SWING Z CORNER", isNewIn26: true, playType: "Screen" },
        { playName: "MTN BENCH", isNewIn26: true, playType: "Quick Pass" },
        { playName: "MTN BENCH RETURN", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN X REPLACE", isNewIn26: true, playType: "Medium Pass" },
        { playName: "RETURN HB SWING", isNewIn26: true, playType: "Screen" },
        { playName: "RETURN LEAD SWING", isNewIn26: true, playType: "Screen" },
        { playName: "RETURN WR MID SCREEN", isNewIn26: true, playType: "Screen" },
        { playName: "RPO ALERT SCREEN", isNewIn26: true, playType: "RPO" },
        { playName: "RPO PEEK POST", isNewIn26: false, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Gun Bunch Wide",
      formationType: "Gun",
      plays: [
        { playName: "BUBBLE SCREEN", isNewIn26: true, playType: "Screen" },
        { playName: "CHEAT FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CHEAT SLOT CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "CHEAT WR MID SCREEN", isNewIn26: true, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MESH DAGGER", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MESH SPOT", isNewIn26: true, playType: "Medium Pass" },
        { playName: "QB WRAP", isNewIn26: true, playType: "QB Run" },
        { playName: "RZ RUB UNDER", isNewIn26: true, playType: "Medium Pass" },
        { playName: "SCISSORS", isNewIn26: true, playType: "Medium Pass" },
        { playName: "Y CROSS", isNewIn26: true, playType: "Medium Pass" },
        { playName: "Z SHIELD SCREEN", isNewIn26: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Doubles Y Off",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "ANGLE CURLS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "CURL COMBO", isNewIn26: false, playType: "Medium Pass" },
        { playName: "FADE STOP", isNewIn26: false, playType: "Deep Pass" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, playType: "Deep Pass" },
        { playName: "FK TOSS TE WHEEL", isNewIn26: true, playType: "Outside Run" },
        { playName: "FK TOSS WR MID SCREEN", isNewIn26: true, playType: "Screen" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "HB TOSS", isNewIn26: true, playType: "Outside Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, playType: "Screen" },
        { playName: "MTN SNAG", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN SPOT N GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "MTN X SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "PA SCISSORS", isNewIn26: true, playType: "Play Action" },
        { playName: "RPO BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "RPO" },
        { playName: "ZONE FAKE JET", isNewIn26: false, playType: "Outside Run" },
      ],
    },
    {
      formation: "Gun Empty Lion",
      formationType: "Gun",
      plays: [
        { playName: "JET POWER READ", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET QB COUNTER", isNewIn26: false, playType: "Outside Run" },
        { playName: "JET QB POWER", isNewIn26: false, playType: "QB Run" },
        { playName: "JET TE MID SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "JET TOUCH PASS", isNewIn26: false, playType: "Screen" },
        { playName: "PA JET SWEEP", isNewIn26: false, playType: "Play Action" },
      ],
    },
    {
      formation: "Gun Empty Spread",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "BUBBLE SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "DOUBLE PIVOT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "FLOOD SWITCH", isNewIn26: false, playType: "Deep Pass" },
        { playName: "INSIDE SMASH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MOTION ANGLE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MOTION DRIVE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MOTION HB OPTION", isNewIn26: false, playType: "Option" },
        { playName: "QB BLAST", isNewIn26: false, playType: "QB Run" },
        { playName: "SLOT CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "STICK N NOD", isNewIn26: false, playType: "Quick Pass" },
        { playName: "VERTICAL LOOKS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "WR DBL SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "WR MID SCREEN", isNewIn26: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Flex Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "7 DAGGER", isNewIn26: false, playType: "Medium Pass" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN MESH Y SPOT", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN SPRINT BENCH", isNewIn26: true, playType: "Quick Pass" },
        { playName: "MTN SPRINT TE SCREEN", isNewIn26: true, playType: "Screen" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA GO SLOT CROSS", isNewIn26: false, playType: "Play Action" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO READ Y FLAT", isNewIn26: true, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Gate",
      formationType: "Gun",
      plays: [
        { playName: "FAKE JET VERTS", isNewIn26: true, playType: "Deep Pass" },
        { playName: "FAKE SCREEN GO", isNewIn26: true, playType: "Screen" },
        { playName: "JET TOUCH PASS", isNewIn26: false, playType: "Screen" },
        { playName: "JET WR MID SCREEN", isNewIn26: true, playType: "Screen" },
        { playName: "SCREEN SLANT", isNewIn26: false, playType: "Screen" },
        { playName: "SPRINT SMASH", isNewIn26: true, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Normal Y Off",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CURL COMBO", isNewIn26: false, playType: "Medium Pass" },
        { playName: "CURLS LEAD SWING", isNewIn26: false, playType: "Screen" },
        { playName: "DBL DIG", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DBL MTN HB SWEEP", isNewIn26: true, playType: "Outside Run" },
        { playName: "DBL MTN HB WRAP", isNewIn26: true, playType: "Medium Pass" },
        { playName: "DBL MTN READ OPTION", isNewIn26: true, playType: "Option" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, playType: "Deep Pass" },
        { playName: "FAKE JET LEAD SWING", isNewIn26: true, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false, playType: "Screen" },
        { playName: "MTN PA SEAM WHEEL", isNewIn26: false, playType: "Deep Pass" },
        { playName: "MTN PA WHEEL SHOT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN RPO READ Y FLAT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Normal Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN INSIDE ZONE", isNewIn26: true, playType: "Inside Run" },
        { playName: "MTN PA SPOT", isNewIn26: true, playType: "Quick Pass" },
        { playName: "MTN RPO READ Y FLAT", isNewIn26: true, playType: "RPO" },
        { playName: "ORBIT PA SLIDE", isNewIn26: true, playType: "Medium Pass" },
        { playName: "ORBIT Y LEAD READ OPTION", isNewIn26: true, playType: "Option" },
        { playName: "ORBIT Z UNDER", isNewIn26: true, playType: "Medium Pass" },
        { playName: "PA SLOT CROSS", isNewIn26: true, playType: "Play Action" },
        { playName: "PIVOT IN SEAMS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "POWER READ", isNewIn26: false, playType: "Inside Run" },
        { playName: "QB G DOWN", isNewIn26: true, playType: "QB Run" },
        { playName: "RPO ALERT SNAG", isNewIn26: true, playType: "RPO" },
        { playName: "RPO GLANCE SLANT", isNewIn26: false, playType: "RPO" },
        { playName: "X DAGGER", isNewIn26: false, playType: "Medium Pass" },
        { playName: "Z UNDER SEAMS", isNewIn26: true, playType: "Deep Pass" },
      ],
    },
    {
      formation: "Gun Split Y Off",
      formationType: "Gun",
      plays: [
        { playName: "BACKS CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "CORNER STRIKE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "H CHOICE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN PA HB SEAM", isNewIn26: true, playType: "Deep Pass" },
        { playName: "MTN SPLIT LEAD ZONE", isNewIn26: true, playType: "Inside Run" },
        { playName: "MTN TRIPLE OPTION LT", isNewIn26: true, playType: "Option" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA SLANT FLAT", isNewIn26: true, playType: "Play Action" },
        { playName: "PA SNAG HB WHEEL", isNewIn26: true, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO ZONE PEEK", isNewIn26: true, playType: "RPO" },
        { playName: "WHEEL TRAIL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "Y CURL", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Spread Y-Slot",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CROSS SLOT WHEEL", isNewIn26: true, playType: "Medium Pass" },
        { playName: "HB DRAW", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB FLAT SCREEN", isNewIn26: true, playType: "Screen" },
        { playName: "HB QUICK BASE", isNewIn26: false, playType: "Quick Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN CURL FLAT CORNER", isNewIn26: true, playType: "Deep Pass" },
        { playName: "MTN CURLS TEXAS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN DAGGER", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN LIONS OUT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN MESH DIG", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN PA WR POWER READ", isNewIn26: true, playType: "Inside Run" },
        { playName: "MTN WR OFF TACKLE", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN WR POWER READ", isNewIn26: true, playType: "Inside Run" },
        { playName: "MTN X POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "PA TE WHEEL", isNewIn26: false, playType: "Play Action" },
        { playName: "RETURN INSIDE ZONE SPLIT", isNewIn26: true, playType: "Inside Run" },
        { playName: "RETURN PA POST CURLS", isNewIn26: true, playType: "Deep Pass" },
        { playName: "RETURN RPO READ Y FLAT", isNewIn26: true, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "RPO" },
        { playName: "SMASH HB SEAM", isNewIn26: true, playType: "Deep Pass" },
        { playName: "WHEEL HB FLAT", isNewIn26: true, playType: "Quick Pass" },
        { playName: "Y STICK", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Trio HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER SIT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "OUTSIDE CURL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA Y CROSS", isNewIn26: false, playType: "Play Action" },
        { playName: "RELOAD INSIDE ZONE", isNewIn26: true, playType: "Option" },
        { playName: "RELOAD PA FLOOD", isNewIn26: true, playType: "Option" },
        { playName: "RELOAD RPO ALERT BUCK", isNewIn26: true, playType: "RPO" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "RPO BUCK PEEK", isNewIn26: true, playType: "RPO" },
        { playName: "SPRINT SPOT", isNewIn26: true, playType: "Quick Pass" },
        { playName: "VERTICALS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "WIDE ZONE", isNewIn26: false, playType: "Outside Run" },
      ],
    },
    {
      formation: "Gun Trips Y Slot Str",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER", isNewIn26: false, playType: "Medium Pass" },
        { playName: "FOUR VERTICALS", isNewIn26: true, playType: "Deep Pass" },
        { playName: "HB MID DRAW", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SWEEP", isNewIn26: false, playType: "Outside Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN CURL X POST", isNewIn26: true, playType: "Deep Pass" },
        { playName: "MTN SHOCK", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN WR MID SCREEN", isNewIn26: true, playType: "Screen" },
        { playName: "PA Y CROSS", isNewIn26: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "RPO ALERT SHOCK", isNewIn26: false, playType: "RPO" },
        { playName: "RPO PEEK Y POST", isNewIn26: true, playType: "RPO" },
        { playName: "SPRINT RIGHT SMASH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "SPRINT SLOT CORNER", isNewIn26: true, playType: "Deep Pass" },
        { playName: "Y OUT", isNewIn26: true, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Trips Y Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "DAGGER", isNewIn26: true, playType: "Medium Pass" },
        { playName: "DEEP FLOOD", isNewIn26: true, playType: "Deep Pass" },
        { playName: "HANK", isNewIn26: true, playType: "Medium Pass" },
        { playName: "HB OFF TACKLE", isNewIn26: true, playType: "Outside Run" },
        { playName: "INSIDE ZONE", isNewIn26: true, playType: "Inside Run" },
        { playName: "LIONS OUT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN HB COUNTER", isNewIn26: true, playType: "Outside Run" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: true, playType: "Inside Run" },
        { playName: "MTN PA FLOOD", isNewIn26: true, playType: "Deep Pass" },
        { playName: "PA QB CHOICE", isNewIn26: true, playType: "Play Action" },
        { playName: "RELOAD DAGGER", isNewIn26: true, playType: "Option" },
        { playName: "RELOAD HB SCREEN", isNewIn26: true, playType: "Option" },
        { playName: "RELOAD LIONS OUT", isNewIn26: false, playType: "Option" },
        { playName: "RPO STICK QB DRAW", isNewIn26: true, playType: "RPO" },
        { playName: "SHOCK", isNewIn26: true, playType: "Medium Pass" },
        { playName: "SLOT RUB RETURN", isNewIn26: true, playType: "Medium Pass" },
        { playName: "SWITCH Z CURL", isNewIn26: true, playType: "Medium Pass" },
        { playName: "Y CROSS", isNewIn26: true, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Wing Off 3TE",
      formationType: "Gun",
      plays: [
        { playName: "ESCORT HB POWER", isNewIn26: false, playType: "Inside Run" },
        { playName: "ESCORT HB SPLIT ZONE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "ESCORT PA DOUBLE POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "ESCORT PA FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "ESCORT PA SLANT FLAT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "ESCORT ZONE TOSS", isNewIn26: false, playType: "Outside Run" },
      ],
    },
    {
      formation: "Gun Wing Trio Wk",
      formationType: "Gun",
      plays: [
        { playName: "BUCK SWEEP", isNewIn26: true, playType: "Outside Run" },
        { playName: "MESH DAGGER", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MESH SPOT", isNewIn26: true, playType: "Medium Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: true, playType: "Outside Run" },
        { playName: "RPO ALERT SLANT", isNewIn26: true, playType: "RPO" },
        { playName: "RZ WHIP FLOOD", isNewIn26: true, playType: "Deep Pass" },
        { playName: "SHOCK", isNewIn26: true, playType: "Medium Pass" },
        { playName: "Z MIDDLE UP", isNewIn26: true, playType: "Medium Pass" },
        { playName: "Z UNDER", isNewIn26: true, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Wing Trips",
      formationType: "Gun",
      plays: [
        { playName: "DBL MTN HB POWER READ", isNewIn26: true, playType: "Inside Run" },
        { playName: "DBL MTN HB WRAP", isNewIn26: true, playType: "Medium Pass" },
        { playName: "DBL MTN PA TE LEAK", isNewIn26: true, playType: "Medium Pass" },
        { playName: "DBL MTN POWER G", isNewIn26: true, playType: "Inside Run" },
        { playName: "DBL MTN RPO ALERT SLANT", isNewIn26: true, playType: "RPO" },
        { playName: "DBL MTN RPO PEEK POP", isNewIn26: true, playType: "RPO" },
        { playName: "HB SWING PSU", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN DBL SMASH SEAM", isNewIn26: true, playType: "Deep Pass" },
        { playName: "MTN SCISSORS", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MTN SLOT SCREEN", isNewIn26: true, playType: "Screen" },
        { playName: "PA X CROSS", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: true, playType: "Inside Run" },
        { playName: "RPO PEEK POP SMASH", isNewIn26: true, playType: "RPO" },
        { playName: "SHOT HB WHEEL", isNewIn26: true, playType: "Medium Pass" },
        { playName: "SHOT Y WHEEL", isNewIn26: true, playType: "Medium Pass" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SWING HB CROSS SCREEN", isNewIn26: true, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Wing Trips Over Lion",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false, playType: "Outside Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "ORBIT HB OFF TACKLE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "ORBIT PA HB SEAM", isNewIn26: false, playType: "Deep Pass" },
        { playName: "ORBIT WR OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO QB COUNTER ALERT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO QB COUNTER ALERT SWING", isNewIn26: false, playType: "RPO" },
        { playName: "RPO QB DRAW PEEK POP", isNewIn26: false, playType: "RPO" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Gun Wing Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "BUCK SWEEP", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB BASE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "MESH Y SPOT", isNewIn26: true, playType: "Medium Pass" },
        { playName: "MESH Y WHEEL", isNewIn26: true, playType: "Medium Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: true, playType: "Outside Run" },
        { playName: "PA POWER Y POP", isNewIn26: true, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "PA Y WHEEL", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, playType: "Inside Run" },
        { playName: "RPO ZONE ALERT SLANT", isNewIn26: true, playType: "RPO" },
        { playName: "RZ SLOT OUT", isNewIn26: true, playType: "Medium Pass" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SWITCH Z CURL", isNewIn26: true, playType: "Medium Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: true, playType: "Option" },
        { playName: "Z DIG", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "COUNTER Y", isNewIn26: false, playType: "Outside Run" },
        { playName: "FK TOSS LIONS WHEEL", isNewIn26: false, playType: "Outside Run" },
        { playName: "FK TOSS WR MID SCREEN", isNewIn26: true, playType: "Screen" },
        { playName: "FLOOD HB SWING", isNewIn26: false, playType: "Screen" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "HB ZONE TOSS", isNewIn26: true, playType: "Outside Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA DOUBLE POST", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO ALERT SHOCK", isNewIn26: false, playType: "RPO" },
        { playName: "RPO BUBBLE Y POP", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO X GLANCE BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "VERTICALS Y OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB COUNTER WK", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SPLIT O", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB STING", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA POWER O", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "QB SNEAK", isNewIn26: false, playType: "QB Run" },
        { playName: "STRONG TOSS", isNewIn26: false, playType: "Outside Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HAIL MARY", isNewIn26: false, playType: "Medium Pass" },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
  ],
};
