import type { TeamPlaybookSeed } from "../types";

export const RICE_SEED: TeamPlaybookSeed = {
  team: "Rice",
  scheme: "Spread Option",
  source: {
    url: "https://cfb.fan/26/playbooks/rice-off/",
    verified: "2026-04-16",
  },
  formations: [
    {
      formation: "Pistol Full House",
      formationType: "Pistol",
      plays: [
        { playName: "COUNTER LEAD", isNewIn26: false, playType: "Inside Run" },
        { playName: "DEEP CURL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB OFF TACKLE", isNewIn26: false },
        { playName: "HB SLAM", isNewIn26: false },
        { playName: "LEAD TRIPLE OPTION", isNewIn26: false, playType: "Option" },
        { playName: "PA BOOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA COMEBACKS", isNewIn26: false, playType: "Play Action" },
        { playName: "PA FLOOD COMEBACK", isNewIn26: false, playType: "Play Action" },
        { playName: "PA FLOOD FB SLIP", isNewIn26: false, playType: "Play Action" },
        { playName: "PA HB WHEEL", isNewIn26: false, playType: "Play Action" },
        { playName: "PA X POST", isNewIn26: false, playType: "Play Action" },
        { playName: "SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "TR OPT SWITCH", isNewIn26: false },
        { playName: "TRIPLE OPTION", isNewIn26: false, playType: "Option" },
        { playName: "ZONE READ", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Spread",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "JET INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET SPEED OPTION", isNewIn26: false, playType: "Option" },
        { playName: "JET TOUCH PASS STR", isNewIn26: false },
        { playName: "PA DEEP IN", isNewIn26: false, playType: "Play Action" },
        { playName: "PA WHEELIE CURLS", isNewIn26: false, playType: "Play Action" },
        { playName: "PA WHEELIES", isNewIn26: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "QUICK SLOT OUT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO ALERT DIVE HITCHES", isNewIn26: false, playType: "RPO" },
        { playName: "SLANT BUBBLE", isNewIn26: false, playType: "Screen" },
        { playName: "SLOT OUTSIDE", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
        { playName: "Y CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "ZONE ALERT BUBBLE", isNewIn26: false, playType: "Screen" },
        { playName: "ZONE ALERT X SMOKE", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Wingback",
      formationType: "Pistol",
      plays: [
        { playName: "ALL CURL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "ARC TRIPLE OPTION WK", isNewIn26: false, playType: "Option" },
        { playName: "BENCH", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MTN HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN LOAD OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MTN PA SWITCH", isNewIn26: false },
        { playName: "MTN PA VERTICALS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "MTN TRIPLE OPTION STR", isNewIn26: false, playType: "Option" },
        { playName: "MTN TRIPLE OPTION WK", isNewIn26: false, playType: "Option" },
        { playName: "PA FLOOD WK", isNewIn26: false, playType: "Play Action" },
        { playName: "PA VERTICALS", isNewIn26: false, playType: "Play Action" },
        { playName: "PA WHEELIES", isNewIn26: false, playType: "Play Action" },
        { playName: "SHOVEL OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SLANT FLAT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SPLIT DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "TRIPLE OPTION STRONG", isNewIn26: false, playType: "Option" },
        { playName: "TRIPLE OPTION WK", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Pistol Wingback Dbl Tight",
      formationType: "Pistol",
      plays: [
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "MESH SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "MTN DUO", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "MTN LOAD OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MTN PA SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "MTN TRIPLE OPTION STR", isNewIn26: false, playType: "Option" },
        { playName: "MTN TRIPLE OPTION WK", isNewIn26: false, playType: "Option" },
        { playName: "MTN WIDE ZONE WK", isNewIn26: false },
        { playName: "PA BOOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA CTR WAGGLE", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "READ OPTION WK", isNewIn26: false, playType: "Option" },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SPLIT ZONE", isNewIn26: false },
        { playName: "TRIPLE OPTION WK", isNewIn26: false, playType: "Option" },
        { playName: "WIDE ZONE WK", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Wingback Slot",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "F LEAD READ OPTION", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SHOVEL OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "TRIPLE OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Pistol Wingback Tight",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "ALL HITCH", isNewIn26: false, playType: "Quick Pass" },
        { playName: "CURL FLAT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MTN HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN HB POWER", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN LEVELS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN LOAD OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MTN PA COMEBACK", isNewIn26: false },
        { playName: "MTN PA CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN TRIPLE OPTION STR", isNewIn26: false, playType: "Option" },
        { playName: "MTN TRIPLE OPTION WK", isNewIn26: false, playType: "Option" },
        { playName: "MTN WIDE ZONE WK", isNewIn26: false },
        { playName: "PA CROSSERS", isNewIn26: false, playType: "Play Action" },
        { playName: "SHOVEL OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SPLIT DIVE WK", isNewIn26: false, playType: "Inside Run" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "TRIPLE OPTION STRONG", isNewIn26: false, playType: "Option" },
        { playName: "TRIPLE OPTION WK", isNewIn26: false, playType: "Option" },
        { playName: "WINGBACK SCREEN", isNewIn26: false, playType: "Screen" },
      ],
    },
    {
      formation: "Pistol Wingback Trips",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "F LEAD READ OPTION", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SMASH", isNewIn26: false },
        { playName: "TRIPLE OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Gun 5WR Trey",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CURL FLATS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "EMPTY STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "FK SCREEN SLUGGO", isNewIn26: false, playType: "Screen" },
        { playName: "FK SCREEN VERTS", isNewIn26: false, playType: "Screen" },
        { playName: "JET SWEEP", isNewIn26: false, playType: "Outside Run" },
        { playName: "MTN HB SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "QB DRAW", isNewIn26: false, playType: "QB Run" },
        { playName: "SHALLOW CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "SPACING", isNewIn26: false },
        { playName: "WR MID SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "WR SCREEN", isNewIn26: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Doubles",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "ANGLE SMASH", isNewIn26: false },
        { playName: "DART READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, playType: "Deep Pass" },
        { playName: "FAKE JET PASS POWER", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MIDLINE READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MTN HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "PA JET SWEEP", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SHOT", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SHARK HB WHEEL", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SPOT N GO", isNewIn26: false, playType: "Quick Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "Y-SAIL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "Z SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Doubles Z Close",
      formationType: "Gun",
      plays: [
        { playName: "DOUBLE SLANT SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "ESCAPE", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "RPO GLANCE POST", isNewIn26: false, playType: "RPO" },
        { playName: "Y-SAIL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "Z CROSS OUT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "Z CROSSER", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Empty Bunch Wide",
      formationType: "Gun",
      plays: [
        { playName: "DRAG CURL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DRIVE WHEEL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DRIVE Y CORNER", isNewIn26: false, playType: "Medium Pass" },
        { playName: "JAILBREAK SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "POST CORNER READ", isNewIn26: false, playType: "Deep Pass" },
        { playName: "QB DRAW", isNewIn26: false, playType: "QB Run" },
        { playName: "SPACING SWITCH", isNewIn26: false },
        { playName: "Z SPOT N GO", isNewIn26: false, playType: "Quick Pass" },
        { playName: "Z SPOT SMASH", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Spread",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CIRCLE", isNewIn26: false },
        { playName: "DEEP ATTACK", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA COMEBACKS", isNewIn26: false, playType: "Play Action" },
        { playName: "PA POWER READ", isNewIn26: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SLANTS MIDDLE", isNewIn26: false, playType: "Quick Pass" },
        { playName: "WR MID SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "WR SCREEN", isNewIn26: false, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Spread Flex",
      formationType: "Gun",
      plays: [
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "LOAD OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MOTION OPTION PASS", isNewIn26: false, playType: "Option" },
        { playName: "MOTION WR OPTION", isNewIn26: false, playType: "Option" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA DEEP OUTS", isNewIn26: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SMASH CORNERS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
        { playName: "WR MID SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trey 4WR",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DAGGER SMASH", isNewIn26: false },
        { playName: "DBL CORNER SWITCH", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DOUBLE POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA WR IN", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SHOCK", isNewIn26: false },
        { playName: "SHOCK HB SEAM", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SMASH", isNewIn26: false },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "WR SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "Y CORNER", isNewIn26: false, playType: "Deep Pass" },
        { playName: "Y CROSS FLOOD", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Wing Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false },
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DOUBLE CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DRAGON SPACING", isNewIn26: false },
        { playName: "DRIVE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "MTN COUNTER", isNewIn26: false },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SMASH HB SEAM", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SPACING", isNewIn26: false },
        { playName: "WHEEL POST DRAG", isNewIn26: false, playType: "Deep Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "619 SAIL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "BUCK SWEEP READ OPT", isNewIn26: false, playType: "Outside Run" },
        { playName: "GL FORK ZIG", isNewIn26: false },
        { playName: "GL SHORT POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "GL UNDERS", isNewIn26: false },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "PA INVERTED VEER", isNewIn26: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "X1ISO POCO", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, playType: "Inside Run" },
      ],
    },
    {
      formation: "Gun Wingback Doubles Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CURL FLAT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN LEAD READ OPTION", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN LOAD OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MTN PA WHEEL", isNewIn26: false },
        { playName: "MTN RPO READ Y FLAT", isNewIn26: false, playType: "RPO" },
        { playName: "MTN TRIPLE OPTION", isNewIn26: false, playType: "Option" },
        { playName: "ORBIT INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "ORBIT PA SHOT", isNewIn26: false },
        { playName: "ORBIT RPO READ Y FLAT", isNewIn26: false, playType: "RPO" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "RPO ALERT HITCHES", isNewIn26: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, playType: "RPO" },
        { playName: "SLOT FADE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SPRINT SLOT OUT", isNewIn26: false },
        { playName: "TRIPLE OPTION", isNewIn26: false, playType: "Option" },
        { playName: "X DAGGER", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wingback Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "DEEP POST CORNER", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DUO WRAP", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "LEAD READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MTN CURLS Y CORNER", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN DUO", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN HB SWEEP", isNewIn26: false, playType: "Outside Run" },
        { playName: "MTN LOAD OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MTN PA SWEEP", isNewIn26: false, playType: "Outside Run" },
        { playName: "MTN PA SWEEP Y SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "MTN PA TE LEAK", isNewIn26: false },
        { playName: "MTN TRIPLE OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MTN WR MID SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "PA POST SHOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA TE OUT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA U CORNER FLOOD", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Wingback Over",
      formationType: "Gun",
      plays: [
        { playName: "DUO WRAP", isNewIn26: false },
        { playName: "HB POWER", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB POWER LEAD", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB ZONE TOSS", isNewIn26: false, playType: "Outside Run" },
        { playName: "MTN HB CROSS SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "MTN HB WHEEL", isNewIn26: false },
        { playName: "MTN LEAD SWING CROSS", isNewIn26: false, playType: "Screen" },
        { playName: "MTN LOAD OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MTN PA SAIL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN TRIPLE OPTION", isNewIn26: false, playType: "Option" },
        { playName: "PA SWITCH", isNewIn26: false, playType: "Play Action" },
        { playName: "SMASH", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wingback Tight Offset",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "BENCH", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "MESH SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "MTN DUO", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN LEAD TRIPLE OPT", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN LOAD OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MTN OUTSIDE ZONE", isNewIn26: false, playType: "Outside Run" },
        { playName: "MTN PA COMEBACK", isNewIn26: false },
        { playName: "MTN PA WHEEL", isNewIn26: false },
        { playName: "MTN SPACING", isNewIn26: false },
        { playName: "MTN TRIPLE OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MTN TRIPLE OPTION ARC", isNewIn26: false, playType: "Option" },
        { playName: "PA SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "TRIPLE OPTION", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Gun Wingback Tight X Split",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false },
        { playName: "HB ATTACK", isNewIn26: false },
        { playName: "MTN INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN PA WHEEL", isNewIn26: false },
        { playName: "MTN SWING SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "PA POWER READ", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false },
        { playName: "QB BLAST", isNewIn26: false, playType: "Inside Run" },
        { playName: "X QUICK OUT", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Wingback Wing Stack Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB POWER", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN DAGGER", isNewIn26: false },
        { playName: "MTN INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN LEAD READ OPT", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN LEAD TRIPLE OPTIONLT", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN LOAD OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MTN OUTSIDE ZONE", isNewIn26: false, playType: "Outside Run" },
        { playName: "MTN PA FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "MTN PA VERTICALS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "MTN PA Y CORNER", isNewIn26: false, playType: "Deep Pass" },
        { playName: "MTN SLOT OPTION", isNewIn26: false, playType: "Option" },
        { playName: "MTN SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "MTN TRIPLE OPTION LT", isNewIn26: false, playType: "Option" },
        { playName: "PA FK SCREEN GO", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ SLANT BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "RPO ZONE ALERT SCREEN", isNewIn26: false, playType: "RPO" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "TRIPLE OPTION LT", isNewIn26: false, playType: "Option" },
      ],
    },
    {
      formation: "Gun Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "CURLS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DIY HB DIRECT REVERSE", isNewIn26: false },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, playType: "Screen" },
        { playName: "HB DIRECT SNAP", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "MTN STICK N NOD", isNewIn26: false, playType: "Quick Pass" },
        { playName: "MTN Y SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA DOUBLE POST", isNewIn26: false, playType: "Play Action" },
        { playName: "PA MTN SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "PA Y FLOOD", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO PEEK POST", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ WR SCREEN", isNewIn26: false, playType: "RPO" },
        { playName: "Y LEAD READ OPT", isNewIn26: false, playType: "Inside Run" },
      ],
    },
    {
      formation: "Gun Y Trio Offset Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET CHIP DAGGER", isNewIn26: false },
        { playName: "MTN OUTSIDE ZONE", isNewIn26: false, playType: "Outside Run" },
        { playName: "MTN Z SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "PA FL SCREEN", isNewIn26: false, playType: "Play Action" },
        { playName: "PA MTN SHOT", isNewIn26: false, playType: "Play Action" },
        { playName: "POST WHEEL DRAG", isNewIn26: false, playType: "Deep Pass" },
        { playName: "RPO PEEK POST", isNewIn26: false, playType: "RPO" },
        { playName: "SLOT 2 BUC", isNewIn26: false },
        { playName: "SLOT FADE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, playType: "Inside Run" },
      ],
    },
    {
      formation: "Gun Y Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "GL FORK ZIG", isNewIn26: false },
        { playName: "GL SHORT POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "GL UNDERS", isNewIn26: false },
        { playName: "HB CROSS SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "MESH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SHOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA WR IN", isNewIn26: false, playType: "Play Action" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "REVERSE", isNewIn26: false },
        { playName: "REVERSE PASS", isNewIn26: false },
        { playName: "RPO BASE ALERT LOOKIE", isNewIn26: false, playType: "RPO" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "RPO" },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
        { playName: "WR MID SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "Y-SAIL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "Z SPOT", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB COUNTER WK", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SPLIT O", isNewIn26: false },
        { playName: "HB STING", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "QB SNEAK", isNewIn26: false, playType: "QB Run" },
        { playName: "STRONG TOSS", isNewIn26: false, playType: "Outside Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HAIL MARY", isNewIn26: false },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false },
      ],
    },
  ],
};
