import type { TeamPlaybookSeed } from "../types";

export const SOUTH_CAROLINA_SEED: TeamPlaybookSeed = {
  team: "South Carolina",
  scheme: "Power Spread",
  sideOfBall: 'offense',
  source: {
    url: "https://cfb.fan/26/playbooks/south-carolina-off/",
    verified: "2026-05-02",
  },
  formations: [
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE", isNewIn26: false },
        { playName: "HB COUNTER WK", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB SPLIT O", isNewIn26: false },
        { playName: "HB STING", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false },
        { playName: "PA SPOT", isNewIn26: false },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false },
        { playName: "PA WAGGLE", isNewIn26: false },
        { playName: "POWER O", isNewIn26: false },
        { playName: "QB SNEAK", isNewIn26: false },
        { playName: "STRONG TOSS", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Bunch Wide",
      formationType: "Gun",
      plays: [
        { playName: "BRANCH RETURN", isNewIn26: false },
        { playName: "CLEAROUT FL IN", isNewIn26: false },
        { playName: "CROSS SCREEN", isNewIn26: false },
        { playName: "FLANKER DRIVE", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: true },
        { playName: "MTN PA CROSSERS", isNewIn26: true },
        { playName: "MTN RPO SPLIT ALERT", isNewIn26: true },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA POST", isNewIn26: false },
        { playName: "SEAM DIVIDE", isNewIn26: false },
        { playName: "SLANT SPACING DIG", isNewIn26: false },
        { playName: "VERTICALS", isNewIn26: false },
        { playName: "Y TRAIL", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Doubles Off Close",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "FAKE JET HB SEAM", isNewIn26: true },
        { playName: "FLOOD", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET PASS FK ZONE", isNewIn26: true },
        { playName: "JET POWER READ", isNewIn26: true },
        { playName: "JET QB COUNTER", isNewIn26: true },
        { playName: "JET SPRINT WK", isNewIn26: true },
        { playName: "JET TE MID SCREEN", isNewIn26: true },
        { playName: "JET TOUCH PASS", isNewIn26: true },
        { playName: "PA JET SWEEP", isNewIn26: true },
        { playName: "RPO GLANCE SLANT", isNewIn26: false },
        { playName: "RPO READ Y ARROW", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: true },
      ],
    },
    {
      formation: "Gun Doubles Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "CURL FLAT", isNewIn26: false },
        { playName: "DOUBLE POST", isNewIn26: false },
        { playName: "DOUBLE SLANTS", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "LEAD READ OPTION", isNewIn26: false },
        { playName: "MTN FAKE JET SHOT", isNewIn26: true },
        { playName: "MTN JET QB COUNTER", isNewIn26: true },
        { playName: "MTN JET TOUCH PASS", isNewIn26: true },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "PA SLIDE", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO GLANCE POST", isNewIn26: false },
        { playName: "RPO GLANCE SLANT", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "X DAGGER", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Empty Bunch",
      formationType: "Gun",
      plays: [
        { playName: "CURL FLATS", isNewIn26: false },
        { playName: "DIVIDE WHEEL", isNewIn26: false },
        { playName: "H TRAIL SMASH", isNewIn26: false },
        { playName: "QB CRACK SWEEP", isNewIn26: true },
        { playName: "QB DRAW", isNewIn26: false },
        { playName: "SPACING", isNewIn26: false },
        { playName: "VERTICALS", isNewIn26: false },
        { playName: "Y CURL", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Empty Chips",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "CURL FLAT", isNewIn26: false },
        { playName: "DAGGER", isNewIn26: false },
        { playName: "DEEP POST OUT", isNewIn26: false },
        { playName: "FLOOD", isNewIn26: false },
        { playName: "POST CROSS", isNewIn26: false },
        { playName: "SLOT CROSS", isNewIn26: false },
        { playName: "SLOT SAIL", isNewIn26: false },
        { playName: "TE SCREEN", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Empty Y-Flex",
      formationType: "Gun",
      plays: [
        { playName: "DEEP DIG", isNewIn26: false },
        { playName: "DRIVE POST", isNewIn26: false },
        { playName: "HOSS Y JUKE", isNewIn26: false },
        { playName: "JET SWEEP", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
        { playName: "QB DRAW", isNewIn26: false },
        { playName: "SHORT POSTS", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "SLUGGO", isNewIn26: false },
        { playName: "STICK N NOD", isNewIn26: false },
        { playName: "WR CORNERS", isNewIn26: false },
        { playName: "Y STICK", isNewIn26: false },
      ],
    },
    {
      formation: "Gun F Twins Over",
      formationType: "Gun",
      plays: [
        { playName: "JET CROSS SCREEN", isNewIn26: false },
        { playName: "JET HB COUNTER", isNewIn26: false },
        { playName: "JET INSIDE ZONE", isNewIn26: false },
        { playName: "JET QB COUNTER", isNewIn26: false },
        { playName: "JET QB POWER", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Normal Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "5 6 TRAP", isNewIn26: true },
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CURL COMBO", isNewIn26: false },
        { playName: "DOUBLE SLANTS", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE CROSS", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "PIVOT IN SEAMS", isNewIn26: false },
        { playName: "POWER READ", isNewIn26: false },
        { playName: "QB FOLLOW", isNewIn26: false },
        { playName: "RPO GLANCE SLANT", isNewIn26: false },
        { playName: "RPO PEEK POST", isNewIn26: false },
        { playName: "RPO READ BUBBLE", isNewIn26: false },
        { playName: "SHALLOW CROSS", isNewIn26: false },
        { playName: "SLOT HOOKS", isNewIn26: false },
        { playName: "SLOT OUT", isNewIn26: false },
        { playName: "SLUGGO SEAM", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "WR UNDER", isNewIn26: false },
        { playName: "X DAGGER", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Spread Offset",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false },
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CURL FLATS", isNewIn26: false },
        { playName: "DAGGER CURLS", isNewIn26: false },
        { playName: "FAKE JET HB CORNER", isNewIn26: true },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET POWER READ", isNewIn26: true },
        { playName: "JET TOUCH PASS", isNewIn26: true },
        { playName: "QUICK SLANTS", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO READ BUBBLE", isNewIn26: false },
        { playName: "SLANTS MIDDLE", isNewIn26: false },
        { playName: "SMASH CORNERS", isNewIn26: false },
        { playName: "SMASH CROSS", isNewIn26: false },
        { playName: "Y CROSS", isNewIn26: false },
        { playName: "ZONE SPEED OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Spread Y-Flex Wk",
      formationType: "Gun",
      plays: [
        { playName: "DOUBLE CROSS", isNewIn26: false },
        { playName: "DOUBLE POST", isNewIn26: false },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MTN BENCH", isNewIn26: false },
        { playName: "MTN BENCH CURLS", isNewIn26: false },
        { playName: "MTN DOUBLE POST", isNewIn26: false },
        { playName: "MTN HB SLIP SCREEN", isNewIn26: false },
        { playName: "MTN WHIP CROSS", isNewIn26: false },
        { playName: "MTN X REPLACE", isNewIn26: false },
        { playName: "PA CROSS", isNewIn26: false },
        { playName: "PA DAGGER", isNewIn26: false },
        { playName: "PA Y CROSS", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Spread Y-Slot",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "CURL WHEEL", isNewIn26: false },
        { playName: "DOUBLE SLANT", isNewIn26: false },
        { playName: "H SHALLOW CROSS", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "HITCH SEAM", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MESH", isNewIn26: false },
        { playName: "MTN HB SWING", isNewIn26: true },
        { playName: "MTN WR MID SCREEN", isNewIn26: true },
        { playName: "MTN Y SHALLOW CROSS", isNewIn26: true },
        { playName: "PA READ", isNewIn26: false },
        { playName: "PA SLOT RUB OUT", isNewIn26: true },
        { playName: "QUICK SLANTS", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "RPO READ SCREEN", isNewIn26: false },
        { playName: "SMASH", isNewIn26: false },
        { playName: "Y CROSS", isNewIn26: false },
        { playName: "Y SHALLOW CROSS", isNewIn26: false },
        { playName: "Y STICK", isNewIn26: false },
        { playName: "Z SHALLOW", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Stack Y Off",
      formationType: "Gun",
      plays: [
        { playName: "BENCH HB ANGLE", isNewIn26: false },
        { playName: "FAKE JET HB SEAM", isNewIn26: false },
        { playName: "FAKE JET PASS POWER", isNewIn26: false },
        { playName: "FLOOD DRIVE", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
        { playName: "REDZONE SCISSORS", isNewIn26: false },
        { playName: "RPO ALERT OUT", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips Y Slot Str",
      formationType: "Gun",
      plays: [
        { playName: "CROSSERS", isNewIn26: true },
        { playName: "DAGGER", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SWEEP", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MESH WHEEL", isNewIn26: true },
        { playName: "PA Y CROSS", isNewIn26: false },
        { playName: "QUICK SLANTS", isNewIn26: false },
        { playName: "RPO ALERT SHOCK", isNewIn26: false },
        { playName: "SHALLOW SCREEN", isNewIn26: true },
        { playName: "SLOT 2 BUC", isNewIn26: false },
        { playName: "SPRINT RIGHT SMASH", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips Y Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "BASH", isNewIn26: true },
        { playName: "CURLS", isNewIn26: true },
        { playName: "DEEP FLOOD", isNewIn26: true },
        { playName: "HANK", isNewIn26: true },
        { playName: "HB BASE", isNewIn26: true },
        { playName: "HB OFF TACKLE", isNewIn26: true },
        { playName: "INSIDE ZONE", isNewIn26: true },
        { playName: "MTN DASH FLOOD", isNewIn26: true },
        { playName: "MTN DASH SWITCH SAIL", isNewIn26: true },
        { playName: "MTN DEEP STICK", isNewIn26: true },
        { playName: "MTN HB COUNTER", isNewIn26: true },
        { playName: "MTN HB SWING", isNewIn26: true },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: true },
        { playName: "MTN LEAD SWING SPOT", isNewIn26: true },
        { playName: "MTN PA FLOOD", isNewIn26: true },
        { playName: "MTN VERTICALS", isNewIn26: true },
        { playName: "PA QB CHOICE", isNewIn26: true },
        { playName: "READ OPTION", isNewIn26: true },
        { playName: "SHOCK", isNewIn26: true },
        { playName: "TRIPS DASH FLOOD", isNewIn26: true },
        { playName: "Y CROSS", isNewIn26: true },
      ],
    },
    {
      formation: "Gun Wing Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "DRIVE", isNewIn26: false },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "HB COUNTER U", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MESH HB CORNER", isNewIn26: false },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false },
        { playName: "PA DAGGER", isNewIn26: false },
        { playName: "PA SE SCREEN", isNewIn26: false },
        { playName: "RPO GLANCE POST", isNewIn26: false },
        { playName: "RPO SWEEP ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO ZONE ALERT BUBBLE", isNewIn26: false },
        { playName: "SMASH", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "TE LEAD READ OPT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Trips",
      formationType: "Gun",
      plays: [
        { playName: "FADE Y CROSS", isNewIn26: false },
        { playName: "HB CROSS SCREEN", isNewIn26: false },
        { playName: "HB SWING", isNewIn26: true },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "PA SLANTS", isNewIn26: false },
        { playName: "PA X CROSS", isNewIn26: false },
        { playName: "POST-CURL", isNewIn26: false },
        { playName: "RPO ALERT OUT", isNewIn26: false },
        { playName: "RPO PEEK Y FLAT", isNewIn26: false },
        { playName: "SLOT CROSS", isNewIn26: false },
        { playName: "SLOT FADE", isNewIn26: false },
        { playName: "SPRINTOUT SLOT CORNER", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "STICK N NOD", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "ALL IN", isNewIn26: false },
        { playName: "BUCK SWEEP", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "DASH FLOOD", isNewIn26: false },
        { playName: "DASH X HITCH", isNewIn26: true },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "PA DEEP CROSS", isNewIn26: false },
        { playName: "PA POWER Y POP", isNewIn26: true },
        { playName: "PA READ", isNewIn26: false },
        { playName: "RPO ALERT SLANT", isNewIn26: false },
        { playName: "RPO READ Y FLAT", isNewIn26: true },
        { playName: "SHOT Y WHEEL", isNewIn26: false },
        { playName: "SLOT CROSS", isNewIn26: false },
        { playName: "SNAG Y CROSS", isNewIn26: true },
        { playName: "WIDE TRAP", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: true },
      ],
    },
    {
      formation: "Gun Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "FLOOD HB SWING", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: true },
        { playName: "PA DOUBLE POST", isNewIn26: false },
        { playName: "PA MTN SLIDE", isNewIn26: false },
        { playName: "PA READ SMASH", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT SHOCK", isNewIn26: false },
        { playName: "RPO BUBBLE Y POP", isNewIn26: false },
        { playName: "RPO READ Y FLAT", isNewIn26: false },
        { playName: "RPO X GLANCE BUBBLE", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "VERTICALS Y OPTION", isNewIn26: false },
        { playName: "Y LEAD READ OPT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Y Off Trips Stack",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: true },
        { playName: "DUO", isNewIn26: false },
        { playName: "FOUR VERTICALS", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "MTN PA BOOT SLIDE", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA DEEP OUT", isNewIn26: true },
        { playName: "PA ZONE SHOT", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT ZONE SCREEN", isNewIn26: true },
        { playName: "RPO READ WR SCREEN", isNewIn26: true },
        { playName: "RPO READ Y FLAT", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "SLOT 2 BUC", isNewIn26: false },
        { playName: "Y LEAD READ OPT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Y Trio Offset Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "FLOOD", isNewIn26: false },
        { playName: "HB POWER O", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "HI LO DIG", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "JET CHIP DAGGER", isNewIn26: false },
        { playName: "MOTION WR OPTION", isNewIn26: true },
        { playName: "MTN OUTSIDE ZONE", isNewIn26: false },
        { playName: "MTN PA CROSS SWITCH", isNewIn26: true },
        { playName: "MTN PA FLOOD", isNewIn26: true },
        { playName: "MTN Z SPOT", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA FL SCREEN", isNewIn26: false },
        { playName: "PA MTN SHOT", isNewIn26: false },
        { playName: "POST WHEEL DRAG", isNewIn26: false },
        { playName: "RPO PEEK POST", isNewIn26: false },
        { playName: "SHOT STREAK", isNewIn26: false },
        { playName: "SLOT FADE", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Y Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "619 SAIL", isNewIn26: false },
        { playName: "ALL GO", isNewIn26: false },
        { playName: "BUCK SWEEP", isNewIn26: false },
        { playName: "HB CROSS SCREEN", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "PA SHOT", isNewIn26: false },
        { playName: "REVERSE", isNewIn26: false },
        { playName: "REVERSE PASS", isNewIn26: false },
        { playName: "RPO BASE ALERT LOOKIE", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "WR MID SCREEN", isNewIn26: false },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false },
        { playName: "HAIL MARY", isNewIn26: false },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Doubles Off Close",
      formationType: "Pistol",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "JET PA SLIDE", isNewIn26: true },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO READ FLAT WHEEL", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Doubles Y Off",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "FADE SMASH", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "PA CROSS", isNewIn26: false },
        { playName: "PA POST SHOT", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO READ FLAT WHEEL", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol U Off",
      formationType: "Pistol",
      plays: [
        { playName: "CURL FLATS", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB SLAM", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "PA BOOT Y DRAG", isNewIn26: false },
        { playName: "PA DEEP CROSS", isNewIn26: false },
        { playName: "PA SHOT GOS", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "TE CROSS", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Y Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: true },
        { playName: "CURLS", isNewIn26: false },
        { playName: "DASH FLOOD", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB SLAM ALERT SMOKE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "PA BOOT SLIDE", isNewIn26: false },
        { playName: "PA DOUBLE POST", isNewIn26: false },
        { playName: "PA STRETCH SHOT", isNewIn26: false },
        { playName: "RPO ZONE X GLANCE", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "VERTICAL TE CROSS", isNewIn26: false },
        { playName: "WIDE ZONE", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Singleback Bunch",
      formationType: "Singleback",
      plays: [
        { playName: "CRACK TOSS", isNewIn26: false },
        { playName: "END AROUND LEAD", isNewIn26: false },
        { playName: "HB SLAM", isNewIn26: false },
        { playName: "HB SLASH FK END ARND", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "PA BOOT", isNewIn26: false },
        { playName: "PA BOOT SLIDE", isNewIn26: false },
        { playName: "PA CROSS SWITCH", isNewIn26: false },
        { playName: "PA END AROUND SIFT", isNewIn26: false },
        { playName: "PITCH WR REVERSE", isNewIn26: false },
        { playName: "SPACING SWITCH", isNewIn26: false },
        { playName: "TE ANGLE", isNewIn26: false },
      ],
    },
    {
      formation: "Wildcat Unbalanced",
      formationType: "Wildcat",
      plays: [
        { playName: "JET REVERSE PASS", isNewIn26: false },
        { playName: "JET SWEEP", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
      ],
    },
  ],
};
