import type { TeamPlaybookSeed } from "../types";

export const TEXAS_AM_SEED: TeamPlaybookSeed = {
  team: "Texas A&M",
  scheme: "Pro Style",
  source: {
    url: "https://cfb.fan/26/playbooks/texas-am-off/",
    verified: "2026-04-16",
  },
  formations: [
    {
      formation: "I Form Slot",
      formationType: "I Form",
      plays: [
        { playName: "26 DUO ALERT BUBBLE", isNewIn26: false, playType: "Inside Run" },
        { playName: "DAGGER", isNewIn26: false },
        { playName: "HB BLAST", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB LEAD DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB TOSS", isNewIn26: false, playType: "Outside Run" },
        { playName: "JET LEAD ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET SWEEP", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "PA JET SWEEP", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "PA X DAGGER", isNewIn26: false, playType: "Play Action" },
        { playName: "PA YTHROWBACK", isNewIn26: false, playType: "Play Action" },
        { playName: "POST WHEEL", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SAIL Y SHAKE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "WEAK FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "Y COP SMASH", isNewIn26: false },
      ],
    },
    {
      formation: "I Form Tight",
      formationType: "I Form",
      plays: [
        { playName: "26 DUO", isNewIn26: false, playType: "Inside Run" },
        { playName: "95 MIKE", isNewIn26: false },
        { playName: "FB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "FLEA FLICKER", isNewIn26: false },
        { playName: "GOAL LINE FADE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB BLAST", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB ISO", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB OFF TACKLE", isNewIn26: false },
        { playName: "HB POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA BOOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA CTR WAGGLE", isNewIn26: false, playType: "Play Action" },
        { playName: "PA HB WHEEL", isNewIn26: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "PA TE CORNER", isNewIn26: false, playType: "Deep Pass" },
        { playName: "PA Y-SEAM", isNewIn26: false, playType: "Deep Pass" },
      ],
    },
    {
      formation: "I Form Wing",
      formationType: "I Form",
      plays: [
        { playName: "CURLS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "FB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "FB FAKE HB FLIP", isNewIn26: false },
        { playName: "HB POWER G", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB TOSS", isNewIn26: false, playType: "Outside Run" },
        { playName: "ISO", isNewIn26: false, playType: "Inside Run" },
        { playName: "MOTION POWER WEAK", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN HB POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN PA POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA BOOT FLOW", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "PA X BURST CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "POST SHOT", isNewIn26: false, playType: "Deep Pass" },
        { playName: "STRONG STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "TE POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "X SLANT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "ZONE WEAK", isNewIn26: false },
      ],
    },
    {
      formation: "I Form Wing Over",
      formationType: "I Form",
      plays: [
        { playName: "HB COUNTER WK", isNewIn26: false },
        { playName: "HB INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB LEAD", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB POWER G", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB SWEEP", isNewIn26: false, playType: "Outside Run" },
        { playName: "MTN POWER", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN ZONE", isNewIn26: false },
        { playName: "PA BOOT FLOW", isNewIn26: false, playType: "Play Action" },
        { playName: "PA MTN POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA SCISSORS", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "PA WAGGLE", isNewIn26: false, playType: "Play Action" },
        { playName: "X SLANT", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Strong I Twins Over",
      formationType: "Strong I",
      plays: [
        { playName: "HB BLAST", isNewIn26: false, playType: "Inside Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA VERTICALS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "ROLLOUT SMASH", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Deuce",
      formationType: "Pistol",
      plays: [
        { playName: "BENCH", isNewIn26: false },
        { playName: "CORNER POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "HITCH CORNERS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "INSIDE CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA DEEP IN", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SHORT POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "STRONG POWER", isNewIn26: false, playType: "Inside Run" },
      ],
    },
    {
      formation: "Pistol Strong",
      formationType: "Pistol",
      plays: [
        { playName: "494 F FLAT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "HB BLAST ALERT X SMOKE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB STRETCH ALERT X LOOKIE", isNewIn26: false, playType: "Outside Run" },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA BOOT LT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SPACING", isNewIn26: false },
        { playName: "X POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "Z SPOT", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Pistol U Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "DBL POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SLAM", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "PA BOOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA BOOT OVER", isNewIn26: false, playType: "Play Action" },
        { playName: "PA CORNER DIG", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA FL CLOWN", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SLOT OUT", isNewIn26: false, playType: "Play Action" },
        { playName: "QUICK SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO ALERT FLAT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SHOCK", isNewIn26: false },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "TE CROSS", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Pistol Weak Slot Over",
      formationType: "Pistol",
      plays: [
        { playName: "COUNTER STIR", isNewIn26: false },
        { playName: "F LEAD READ OPTION", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB ZONE WK", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "PA CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "ZONE ALERT BUBBLE", isNewIn26: false, playType: "Screen" },
      ],
    },
    {
      formation: "Pistol Wing Slot",
      formationType: "Pistol",
      plays: [
        { playName: "DAGGER", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "HITCH CORNERS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "LEAD OPTION", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA BOOT LT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA CTR WAGGLE", isNewIn26: false, playType: "Play Action" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA SLOT CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "POSTS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "READ OPTION WK", isNewIn26: false, playType: "Option" },
        { playName: "STRONG POWER", isNewIn26: false, playType: "Inside Run" },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Pistol Wing Slot Over",
      formationType: "Pistol",
      plays: [
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB STRETCH", isNewIn26: false, playType: "Outside Run" },
        { playName: "PA DOUBLE POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "PA STRETCH SHOT", isNewIn26: false, playType: "Outside Run" },
        { playName: "POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "ROLLOUT FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "RPO GLANCE POST BUBBLE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SPLIT ZONE", isNewIn26: false },
        { playName: "STRONG POWER", isNewIn26: false, playType: "Inside Run" },
        { playName: "WIDE ZONE", isNewIn26: false },
        { playName: "ZONE ALERT BUBBLE", isNewIn26: false, playType: "Screen" },
      ],
    },
    {
      formation: "Pistol Y Off Trips",
      formationType: "Pistol",
      plays: [
        { playName: "COUNTER Y", isNewIn26: true },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SLAM", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA BOOT SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "PA DOUBLE POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "STRONG FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, playType: "Inside Run" },
      ],
    },
    {
      formation: "Gun Ace",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false },
        { playName: "BENCH", isNewIn26: false },
        { playName: "CORNER STRIKE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "FLANKER CURL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "HITCH CORNERS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "INSIDE CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA COMEBACKS", isNewIn26: false, playType: "Play Action" },
        { playName: "PA INVERTED VEER", isNewIn26: false, playType: "Option" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SHOT", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, playType: "Inside Run" },
        { playName: "QB BLAST", isNewIn26: false, playType: "Inside Run" },
        { playName: "QB ZONE", isNewIn26: false, playType: "QB Run" },
        { playName: "QUICK SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "TE ATTACK", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Ace Slot",
      formationType: "Gun",
      plays: [
        { playName: "DIY REVERSE", isNewIn26: false },
        { playName: "DIY ZONE REVERSE", isNewIn26: false },
        { playName: "FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB QUICK BASE", isNewIn26: false, playType: "Quick Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "POSTS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "QB POWER", isNewIn26: false, playType: "Inside Run" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, playType: "Screen" },
        { playName: "SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SMASH", isNewIn26: false },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "X SPOT", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Bunch Open Offset",
      formationType: "Gun",
      plays: [
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false, playType: "Screen" },
        { playName: "FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "RPO ALERT OUT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO PEEK WR SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, playType: "Screen" },
        { playName: "SPRINT Z SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "Y TRAIL", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Doubles",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER BASH", isNewIn26: true },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, playType: "Deep Pass" },
        { playName: "FAKE JET PASS POWER", isNewIn26: false, playType: "Inside Run" },
        { playName: "FOUR VERTICALS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "INVERTED VEER", isNewIn26: false, playType: "Option" },
        { playName: "JET HB POWER", isNewIn26: true, playType: "Inside Run" },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: true, playType: "Inside Run" },
        { playName: "MTN PA SLIDE", isNewIn26: true },
        { playName: "MTN RPO READ SLIDE", isNewIn26: true, playType: "RPO" },
        { playName: "ORBIT QB WRAP SWEEP", isNewIn26: true, playType: "Outside Run" },
        { playName: "ORBIT RPO READ Y FLAT", isNewIn26: true, playType: "Quick Pass" },
        { playName: "ORBIT Y STICK", isNewIn26: true, playType: "Quick Pass" },
        { playName: "PA DAGGER", isNewIn26: false, playType: "Play Action" },
        { playName: "PA QB CHOICE", isNewIn26: false, playType: "Play Action" },
        { playName: "QB POWER", isNewIn26: false, playType: "Inside Run" },
        { playName: "QB WRAP", isNewIn26: false, playType: "QB Run" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SPOT SMASH", isNewIn26: false, playType: "Quick Pass" },
        { playName: "X UNDER SEAMS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Doubles Y Off",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "ANGLE CURLS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "CORNER STRIKE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "CURL COMBO", isNewIn26: false, playType: "Medium Pass" },
        { playName: "FADE STOP", isNewIn26: false, playType: "Deep Pass" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, playType: "Deep Pass" },
        { playName: "FAKE JET HB WHEEL", isNewIn26: true },
        { playName: "FAKE JET PASS POWER", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET HB SPLIT ZONE", isNewIn26: true },
        { playName: "JET OUTSIDE ZONE", isNewIn26: true, playType: "Outside Run" },
        { playName: "JET POWER READ", isNewIn26: true, playType: "Inside Run" },
        { playName: "JET RPO GLANCE", isNewIn26: true, playType: "RPO" },
        { playName: "JET TE MID SCREEN", isNewIn26: true, playType: "Screen" },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "POST X CURL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO BUBBLE", isNewIn26: false, playType: "Screen" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SHARK HB WHEEL", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "VERT COMEBACKS", isNewIn26: false, playType: "Deep Pass" },
      ],
    },
    {
      formation: "Gun Empty Base Flex",
      formationType: "Gun",
      plays: [
        { playName: "LEVELS SWITCH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MIDDLE HI LO", isNewIn26: false },
        { playName: "QB DRAW", isNewIn26: false, playType: "QB Run" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "STRONG CURL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "VERTICALS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "WR SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "Y CORNER", isNewIn26: false, playType: "Deep Pass" },
        { playName: "Y SHALLOW CROSS", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Empty Trips Y Off",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CURLS SLOT OUT", isNewIn26: true, playType: "Medium Pass" },
        { playName: "DAGGER", isNewIn26: true },
        { playName: "DEEP CURLS", isNewIn26: true, playType: "Medium Pass" },
        { playName: "HITCHES X DIG", isNewIn26: true, playType: "Quick Pass" },
        { playName: "INS SLOT CORNER", isNewIn26: true, playType: "Deep Pass" },
        { playName: "LEVELS SEAM", isNewIn26: true, playType: "Medium Pass" },
        { playName: "QB G DOWN", isNewIn26: true, playType: "QB Run" },
        { playName: "QB ZONE", isNewIn26: true, playType: "QB Run" },
        { playName: "RPO ALERT BUBBLE QB POWER", isNewIn26: true, playType: "Inside Run" },
        { playName: "SLOT FADE", isNewIn26: true, playType: "Deep Pass" },
        { playName: "TE MID SCREEN", isNewIn26: true, playType: "Screen" },
      ],
    },
    {
      formation: "Gun Flex Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "CURLS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DOUBLE POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DOUBLE SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "FLANKER SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "PA JAILBREAK SCREEN", isNewIn26: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SLIDE", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "RPO READ SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "SLUGGO SEAM", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SMASH", isNewIn26: false },
        { playName: "X DAGGER", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, playType: "Inside Run" },
        { playName: "ZONE ALERT GLANCE", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Spread Dbl Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DEEP CURL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "FL CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "FLANKER DIG", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB DIRECT", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "HITCH CORNERS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA DIG", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "QB WRAP", isNewIn26: false, playType: "QB Run" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SLANTS MIDDLE", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SLOT OUT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Stack Y Off",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CURL FLATS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "FAKE JET HB SEAM", isNewIn26: false, playType: "Deep Pass" },
        { playName: "FAKE JET PASS POWER", isNewIn26: false, playType: "Inside Run" },
        { playName: "FLOOD DRIVE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "LEVELS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA JET SWEEP", isNewIn26: false, playType: "Outside Run" },
        { playName: "REDZONE SCISSORS", isNewIn26: false },
        { playName: "RPO ALERT OUT", isNewIn26: false, playType: "RPO" },
        { playName: "SWITCH WR DRAG", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Tight Open",
      formationType: "Gun",
      plays: [
        { playName: "BENCH", isNewIn26: false },
        { playName: "BENCH DIG PIVOT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "BENCH RETURN", isNewIn26: false },
        { playName: "DIG Z SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "MESH SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "POST CORNER DRIVE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SHALLOW CORNER STOP", isNewIn26: false, playType: "Medium Pass" },
        { playName: "SLOT POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
        { playName: "TIGHT SEAMS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "VERTICALS HB BURST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "Z SPOT DIG", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun U Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "DEEP POST CORNER", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB POWER", isNewIn26: false, playType: "Inside Run" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA POST SHOT", isNewIn26: false, playType: "Deep Pass" },
        { playName: "PA TE OUT", isNewIn26: false, playType: "Play Action" },
        { playName: "POST WHEEL SHALLOW", isNewIn26: false, playType: "Medium Pass" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, playType: "Screen" },
        { playName: "RPO ALERT X GIFT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ FLAT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SHOCK", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Slot Over",
      formationType: "Gun",
      plays: [
        { playName: "HB STRONG ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "PA INVERTED VEER", isNewIn26: false, playType: "Option" },
        { playName: "PA POST CURL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "PA WHEEL CURLS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "POWER READ", isNewIn26: false, playType: "Inside Run" },
        { playName: "QB WRAP", isNewIn26: false, playType: "QB Run" },
        { playName: "RPO ALERT SLANT-HITCH", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SPEED OPTION", isNewIn26: false, playType: "Option" },
        { playName: "SPRINT SWITCH SMASH", isNewIn26: false },
        { playName: "SPRINTOUT SMASH", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Slot Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "BUCK SWEEP READ OPT", isNewIn26: false, playType: "Outside Run" },
        { playName: "DOUBLE POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER READ", isNewIn26: false, playType: "Inside Run" },
        { playName: "RPO PEEK POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "SLANT STICK", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Y Off Trio Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "BUCK SWEEP", isNewIn26: false, playType: "Outside Run" },
        { playName: "CURLS COMBO", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DAGGER X OUT", isNewIn26: false },
        { playName: "DBL INS", isNewIn26: false },
        { playName: "DOUBLE GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "GL FORK ZIG", isNewIn26: false },
        { playName: "GL SHORT POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "GL UNDERS", isNewIn26: false },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "PA POST DIG SHOT", isNewIn26: false, playType: "Medium Pass" },
        { playName: "POWER READ", isNewIn26: false, playType: "Inside Run" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "Y LEAD READ OPTION", isNewIn26: false, playType: "Inside Run" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB COUNTER WK", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SPLIT O", isNewIn26: false },
        { playName: "HB STING", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "PA WAGGLE", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "QB SNEAK", isNewIn26: false, playType: "QB Run" },
        { playName: "STRONG TOSS", isNewIn26: false, playType: "Outside Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HAIL MARY", isNewIn26: false },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false },
      ],
    },
  ],
};
