import type { TeamPlaybookSeed } from "../types";

export const WEST_VIRGINIA_SEED: TeamPlaybookSeed = {
  team: "West Virginia",
  scheme: "Spread",
  source: {
    url: "https://cfb.fan/26/playbooks/west-virginia-off/",
    verified: "2026-05-02",
  },
  formations: [
    {
      formation: "I Form Tight",
      formationType: "I Form",
      plays: [
        { playName: "FB DIVE", isNewIn26: false },
        { playName: "FB FAKE HB TOSS", isNewIn26: false },
        { playName: "GOAL LINE FADE", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB LEAD", isNewIn26: false },
        { playName: "HB POWER O", isNewIn26: false },
        { playName: "HB STRETCH ALERT U POP", isNewIn26: false },
        { playName: "PA CTR SHOT", isNewIn26: false },
        { playName: "PA HB WHEEL", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false },
        { playName: "Y DIG", isNewIn26: false },
        { playName: "Z SLANT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Bunch Trio Open",
      formationType: "Gun",
      plays: [
        { playName: "FAKE SCREEN VERTICALS", isNewIn26: false },
        { playName: "FOUR VERTICALS", isNewIn26: false },
        { playName: "HB CROSS SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "RPO ALERT QB DRAW", isNewIn26: false },
        { playName: "RPO ALERT WR SCREEN", isNewIn26: false },
        { playName: "RPO READ WR SCREEN", isNewIn26: false },
        { playName: "Y TRAIL", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Deuce",
      formationType: "Gun",
      plays: [
        { playName: "BENCH SWAP", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "COUNTER Y READ OPTION", isNewIn26: false },
        { playName: "DIY TOSS REVERSE", isNewIn26: false },
        { playName: "FK TOSS", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "LEAD READ OPTION", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "MTN INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "MTN PA SLIDE", isNewIn26: false },
        { playName: "MTN Y LEAD READ OPT", isNewIn26: false },
        { playName: "PA SLIDE", isNewIn26: false },
        { playName: "QB ZONE", isNewIn26: false },
        { playName: "RPO READ FLAT WHEEL", isNewIn26: false },
        { playName: "RPO READ SNAG", isNewIn26: false },
        { playName: "SHALLOW CROSS", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "ZONE TOSS", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Deuce Twins Over",
      formationType: "Gun",
      plays: [
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "LEAD READ OPTION", isNewIn26: false },
        { playName: "PA SLIDE", isNewIn26: false },
        { playName: "RPO READ U SLIDE", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Empty Trio",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CURL FLATS", isNewIn26: false },
        { playName: "DOUBLE PIVOT", isNewIn26: false },
        { playName: "HITCH CORNERS", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MTN MESH Y POST", isNewIn26: false },
        { playName: "QB DRAW", isNewIn26: false },
        { playName: "SHALLOW CROSS", isNewIn26: false },
        { playName: "SHOCK SLOT OPTION", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "SPACING", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "STRONG FLOOD", isNewIn26: false },
        { playName: "WR OPTION", isNewIn26: false },
        { playName: "WR SCREENS", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Empty Y Off Trips",
      formationType: "Gun",
      plays: [
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "DBL SLOT CROSS", isNewIn26: false },
        { playName: "FOUR VERTICALS", isNewIn26: false },
        { playName: "JET QB COUNTER", isNewIn26: false },
        { playName: "JET QB POWER", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "PA JET FLOOD", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
        { playName: "PA JET SWEEP SHOT", isNewIn26: false },
        { playName: "QB POWER", isNewIn26: false },
        { playName: "QB SPLIT ZONE", isNewIn26: false },
        { playName: "QB ZONE", isNewIn26: false },
        { playName: "RZ DOUBLE UNDER", isNewIn26: false },
        { playName: "RZ DUSTY", isNewIn26: false },
        { playName: "SPRINT SMASH", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Normal Y Off",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "CURL FLATS", isNewIn26: false },
        { playName: "FAKE JET HB SEAM", isNewIn26: false },
        { playName: "FAKE JET PASS POWER", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET PASS FK ZONE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MIDLINE READ OPTION", isNewIn26: false },
        { playName: "MTN INSIDE ZONE", isNewIn26: false },
        { playName: "MTN LEAD OUTSIDE ZONE", isNewIn26: false },
        { playName: "MTN PA SWITCH", isNewIn26: false },
        { playName: "MTN PA VERTICALS", isNewIn26: false },
        { playName: "MTN POWER READ", isNewIn26: false },
        { playName: "MTN READ OPTION", isNewIn26: false },
        { playName: "PA BOOT SHOT", isNewIn26: false },
        { playName: "PA CROSS", isNewIn26: false },
        { playName: "PA JET SWEEP", isNewIn26: false },
        { playName: "PA SLOT POST", isNewIn26: false },
        { playName: "PA X SLUGGO", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO READ FL SCREEN", isNewIn26: false },
        { playName: "ZONE FAKE JET", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Normal Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COUNTER BASH", isNewIn26: false },
        { playName: "CURL COMBO", isNewIn26: false },
        { playName: "DASH HITCH SLOT OVER", isNewIn26: false },
        { playName: "DOUBLE SLANTS", isNewIn26: false },
        { playName: "ESCORT CURL COMBO", isNewIn26: false },
        { playName: "ESCORT QB BLAST", isNewIn26: false },
        { playName: "ESCORT SPEED OPTION", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE CROSS", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "ORBIT PA SLIDE", isNewIn26: false },
        { playName: "ORBIT Y LEAD READ OPTION", isNewIn26: false },
        { playName: "ORBIT Z UNDER", isNewIn26: false },
        { playName: "PA SLIDE", isNewIn26: false },
        { playName: "POWER READ", isNewIn26: false },
        { playName: "QB POWER", isNewIn26: false },
        { playName: "RPO GLANCE SLANT", isNewIn26: false },
        { playName: "RPO READ BUBBLE", isNewIn26: false },
        { playName: "RPO READ Y FLAT", isNewIn26: false },
        { playName: "RPO SPLIT ALERT BUBBLE", isNewIn26: false },
        { playName: "SEAMS DOUBLE CURL", isNewIn26: false },
        { playName: "SLOT FADE", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "X DAGGER", isNewIn26: false },
        { playName: "Z UNDER SEAMS", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Spread",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false },
        { playName: "ALL CURLS", isNewIn26: false },
        { playName: "ALL GO", isNewIn26: false },
        { playName: "BUBBLE SLANTS", isNewIn26: false },
        { playName: "CROSS Z DIG", isNewIn26: false },
        { playName: "DOUBLE POST BUBBLE", isNewIn26: false },
        { playName: "FAKE JET FLOOD", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET HB BASE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MTN RPO O DRAW BASE", isNewIn26: false },
        { playName: "MTN X SPOT", isNewIn26: false },
        { playName: "MTN Z SPOT N GO", isNewIn26: false },
        { playName: "PA POWER READ", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "POWER READ", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "SLANTS MIDDLE", isNewIn26: false },
        { playName: "SMASH HB SEAM", isNewIn26: false },
        { playName: "WR MID SCREEN", isNewIn26: false },
        { playName: "WR SCREEN", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Spread HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CAKE READ OPTION", isNewIn26: false },
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "FLANKER DIG", isNewIn26: false },
        { playName: "H SHALLOW CROSS", isNewIn26: false },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "HITCH SEAM", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA BUBBLE Y OVER", isNewIn26: false },
        { playName: "PA DAGGER", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "QUICK SLANTS", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "RPO READ BUBBLE", isNewIn26: false },
        { playName: "RPO READ WR SCREEN", isNewIn26: false },
        { playName: "SMASH CORNERS", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Spread Y-Flex",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "DRIVE HB WHEEL", isNewIn26: false },
        { playName: "FL SCREEN", isNewIn26: false },
        { playName: "H SHALLOW CROSS", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "MTN MESH SPOT", isNewIn26: false },
        { playName: "MTN REPLACE", isNewIn26: false },
        { playName: "MTN WHIPS", isNewIn26: false },
        { playName: "POWER READ", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT QB DRAW", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "SMASH HB CHECK", isNewIn26: false },
        { playName: "Y CORNER", isNewIn26: false },
        { playName: "Y CROSS", isNewIn26: false },
        { playName: "Y SAIL", isNewIn26: false },
        { playName: "Y SHALLOW CROSS", isNewIn26: false },
        { playName: "Y STICK", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trio Rt Open",
      formationType: "Gun",
      plays: [
        { playName: "ALL CURL", isNewIn26: false },
        { playName: "CORNER STRIKE", isNewIn26: false },
        { playName: "CROSS Z CURL", isNewIn26: false },
        { playName: "DOUBLE POST", isNewIn26: false },
        { playName: "DRIVE", isNewIn26: false },
        { playName: "FOUR VERTICALS", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "WR MID SCREEN", isNewIn26: false },
        { playName: "Z UNDER", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "CROSS FLOOD", isNewIn26: false },
        { playName: "CURLS", isNewIn26: false },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MIDDLE SLANT", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "PA WR IN", isNewIn26: false },
        { playName: "POWER READ", isNewIn26: false },
        { playName: "QB SLOT OPTION", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO BUBBLE QB POWER WK", isNewIn26: false },
        { playName: "RPO QB DRAW SWING", isNewIn26: false },
        { playName: "RPO READ BUBBLE", isNewIn26: false },
        { playName: "RPO READ SCREEN", isNewIn26: false },
        { playName: "SLOT DRIVE", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "WR MID SCREEN", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips Off Over Wk",
      formationType: "Gun",
      plays: [
        { playName: "DASH SLOT OVER", isNewIn26: false },
        { playName: "HB CROSS SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "RPO ALERT SPLIT BUBBLE", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "RPO READ Y FLAT", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Trips Offset",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false },
        { playName: "CURLS", isNewIn26: false },
        { playName: "FAKE BUBBLE POST", isNewIn26: false },
        { playName: "FAKE SCREEN WHEEL", isNewIn26: false },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "PA BUBBLE", isNewIn26: false },
        { playName: "QB SLOT OPTION", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT ZONE BUBBLE", isNewIn26: false },
        { playName: "RPO ALERT ZONE SCREEN", isNewIn26: false },
        { playName: "RPO READ BUBBLE", isNewIn26: false },
        { playName: "SLOT DRIVE", isNewIn26: false },
        { playName: "SLOT UNDER", isNewIn26: false },
        { playName: "SMASH", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "VERTICALS", isNewIn26: false },
        { playName: "WR MID SCREEN", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
        { playName: "ZONE SPEED OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing",
      formationType: "Gun",
      plays: [
        { playName: "HB ANGLE", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "PA FORK", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "SLOT 2 BUC", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "TE ATTACK", isNewIn26: false },
        { playName: "Y DRIVE CLOWN", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Pair Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "HB COUNTER WK", isNewIn26: false },
        { playName: "HB POWER", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA TE SEAM", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "SNAG SPACING", isNewIn26: false },
        { playName: "TE DRIVE", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Slot Offset",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "DRAGON SPACING", isNewIn26: false },
        { playName: "DRIVE", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "MTN HB SWING", isNewIn26: false },
        { playName: "MTN QB SWEEP", isNewIn26: false },
        { playName: "MTN RPO ALERT SCREEN", isNewIn26: false },
        { playName: "MTN RPO READ Y FLAT", isNewIn26: false },
        { playName: "MTN SWITCH HB WHEEL", isNewIn26: false },
        { playName: "PA DOUBLE POST", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "POWER O", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "RZ MTN WR ANGLE", isNewIn26: false },
        { playName: "SPOT OPTION", isNewIn26: false },
        { playName: "STICK NOD VERTICAL", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Slot Over",
      formationType: "Gun",
      plays: [
        { playName: "DIY REVERSE", isNewIn26: false },
        { playName: "HB STRONG ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "PA FLOOD", isNewIn26: false },
        { playName: "PA INVERTED VEER", isNewIn26: false },
        { playName: "PA POST CURL", isNewIn26: false },
        { playName: "PA WHEEL CURLS", isNewIn26: false },
        { playName: "POWER READ", isNewIn26: false },
        { playName: "QB POWER", isNewIn26: false },
        { playName: "QB POWER RPO", isNewIn26: false },
        { playName: "QB WRAP", isNewIn26: false },
        { playName: "QB ZONE", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT SLANT HITCH", isNewIn26: false },
        { playName: "RUB Z UNDER", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "SPRINT SWITCH SMASH", isNewIn26: false },
        { playName: "SPRINTOUT SMASH", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Tight Z",
      formationType: "Gun",
      plays: [
        { playName: "0 1 TRAP", isNewIn26: false },
        { playName: "DUO", isNewIn26: false },
        { playName: "GOAL LINE FADE", isNewIn26: false },
        { playName: "HB PUNCH", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "MESH SPOT", isNewIn26: false },
        { playName: "PA FLANKER CURL", isNewIn26: false },
        { playName: "RPO GLANCE POST", isNewIn26: false },
        { playName: "ZONE OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Trips",
      formationType: "Gun",
      plays: [
        { playName: "BUBBLE DOUBLE GO", isNewIn26: false },
        { playName: "DIY REVERSE", isNewIn26: false },
        { playName: "HB SWING", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "PA FAKE SWITCH", isNewIn26: false },
        { playName: "PA SHAKES", isNewIn26: false },
        { playName: "PA SLANTS", isNewIn26: false },
        { playName: "PA SLOT CROSS", isNewIn26: false },
        { playName: "PA SWITCH", isNewIn26: false },
        { playName: "PA X CROSS", isNewIn26: false },
        { playName: "POST CURL", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false },
        { playName: "RPO ALERT OUT", isNewIn26: false },
        { playName: "RPO PEEK Y FLAT", isNewIn26: false },
        { playName: "RPO READ BUBBLE", isNewIn26: false },
        { playName: "RPO ZONE ALERT SCREEN", isNewIn26: false },
        { playName: "SLOT CROSS", isNewIn26: false },
        { playName: "SPRINTOUT SLOT CORNER", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Trips Wk",
      formationType: "Gun",
      plays: [
        { playName: "619 SAIL", isNewIn26: false },
        { playName: "ALL GO", isNewIn26: false },
        { playName: "ALL IN", isNewIn26: false },
        { playName: "BASH", isNewIn26: false },
        { playName: "BUCK SWEEP", isNewIn26: false },
        { playName: "BUCK SWEEP READ OPT", isNewIn26: false },
        { playName: "COUNTER BASH", isNewIn26: false },
        { playName: "DASH WHEEL", isNewIn26: false },
        { playName: "GT COUNTER BASH", isNewIn26: false },
        { playName: "HB BASE", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "PA DEEP CROSS", isNewIn26: false },
        { playName: "PA INVERTED VEER", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "PA SLIDE", isNewIn26: false },
        { playName: "PA Y FLOOD", isNewIn26: false },
        { playName: "POWER READ", isNewIn26: false },
        { playName: "REVERSE", isNewIn26: false },
        { playName: "RPO ALERT QB COUNTER", isNewIn26: false },
        { playName: "RPO ALERT QB COUNTER RAIL", isNewIn26: false },
        { playName: "RPO READ Y FLAT", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "Y LEAD READ OPTION", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing X Off",
      formationType: "Gun",
      plays: [
        { playName: "JET DUO", isNewIn26: false },
        { playName: "JET INSIDE ZONE", isNewIn26: false },
        { playName: "JET PA BOOT HB WHEEL", isNewIn26: false },
        { playName: "JET PA DOUBLE POST", isNewIn26: false },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "RPO READ JET POP", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Wing Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "BASH", isNewIn26: false },
        { playName: "COUNTER BASH", isNewIn26: false },
        { playName: "DBL LEAD READ OPT", isNewIn26: false },
        { playName: "DRIVE", isNewIn26: false },
        { playName: "GT COUNTER BASH", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "INSIDE ZONE SPLIT", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA INVERTED VEER", isNewIn26: false },
        { playName: "PA SLIDE U OVER", isNewIn26: false },
        { playName: "POWER READ", isNewIn26: false },
        { playName: "QB WRAP", isNewIn26: false },
        { playName: "SLANTS", isNewIn26: false },
        { playName: "TE ATTACK", isNewIn26: false },
        { playName: "Z SPOT", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Y Trips Offset",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false },
        { playName: "COMEBACKS", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false },
        { playName: "INSIDE ZONE", isNewIn26: false },
        { playName: "OUTSIDE ZONE", isNewIn26: false },
        { playName: "PA READ", isNewIn26: false },
        { playName: "PA READ SMASH", isNewIn26: false },
        { playName: "PA ZONE SHOT", isNewIn26: false },
        { playName: "QB SLOT OPTION", isNewIn26: false },
        { playName: "READ OPTION", isNewIn26: false },
        { playName: "RPO BUBBLE Y POP", isNewIn26: false },
        { playName: "RPO GLANCE POST", isNewIn26: false },
        { playName: "RPO PEEK SLANT", isNewIn26: false },
        { playName: "RPO READ WR SCREEN", isNewIn26: false },
        { playName: "RPO READ Y FLAT", isNewIn26: false },
        { playName: "SLOT DRIVE", isNewIn26: false },
        { playName: "SPEED OPTION", isNewIn26: false },
        { playName: "SPRINTOUT SMASH", isNewIn26: false },
        { playName: "STICK", isNewIn26: false },
        { playName: "Y CORNER", isNewIn26: false },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE", isNewIn26: false },
        { playName: "HB COUNTER WK", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false },
        { playName: "HB SPLIT O", isNewIn26: false },
        { playName: "HB STING", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false },
        { playName: "PA SPOT", isNewIn26: false },
        { playName: "PA SPRINT HB FLAT", isNewIn26: false },
        { playName: "PA WAGGLE", isNewIn26: false },
        { playName: "POWER O", isNewIn26: false },
        { playName: "QB SNEAK", isNewIn26: false },
        { playName: "STRONG TOSS", isNewIn26: false },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false },
        { playName: "HAIL MARY", isNewIn26: false },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false },
      ],
    },
  ],
};
