import type { TeamPlaybookSeed } from "../types";

export const WESTERN_KENTUCKY_SEED: TeamPlaybookSeed = {
  team: "Western Kentucky",
  scheme: "Air Raid",
  sideOfBall: 'offense',
  source: {
    url: "https://cfb.fan/26/playbooks/western-kentucky-off/",
    verified: "2026-04-21",
  },
  formations: [
    {
      formation: "I Form Tight",
      formationType: "I Form",
      plays: [
        { playName: "26 DUO", isNewIn26: false, playType: "Inside Run" },
        { playName: "FB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB ISO", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB LEAD TOSS", isNewIn26: false, playType: "Outside Run" },
        { playName: "HB POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA BOOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA POWER O", isNewIn26: false, playType: "Play Action" },
        { playName: "Z SLANT", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun 5WR",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CROSS Z DIG", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DEEP DIVIDE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "QB DRAW", isNewIn26: false, playType: "QB Run" },
        { playName: "QUICK SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SCISSORS", isNewIn26: false },
        { playName: "SHALLOW CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "SHOCK", isNewIn26: false },
        { playName: "SLOT SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "STICK N NOD", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Bunch Quads Open",
      formationType: "Gun",
      plays: [
        { playName: "ALL CURL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "BUNCH TRAIL", isNewIn26: false },
        { playName: "HB SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "QB BLAST", isNewIn26: false, playType: "QB Run" },
        { playName: "RPO Q SCREEN DRAW", isNewIn26: false, playType: "RPO" },
      ],
    },
    {
      formation: "Gun Empty Bunch Open",
      formationType: "Gun",
      plays: [
        { playName: "BUNCH ARCHES", isNewIn26: false },
        { playName: "BUNCH TRAIL", isNewIn26: false },
        { playName: "CHOICE SHALLOW CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "CLEAR DEEP", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DAGGER", isNewIn26: false },
        { playName: "DRAG CURL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "DRIVE Y CORNER", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MESH CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MESH SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "QB DRAW", isNewIn26: false, playType: "QB Run" },
        { playName: "SLOT CHOICE SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SPEED DIG", isNewIn26: false, playType: "Medium Pass" },
        { playName: "Z SPOT N GO", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Empty Trey",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CORNER STRIKE", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CURL FLATS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "QB DRAW", isNewIn26: false, playType: "QB Run" },
        { playName: "QUICK SLANTS", isNewIn26: false, playType: "Quick Pass" },
        { playName: "SCISSORS", isNewIn26: false },
        { playName: "SHOCK", isNewIn26: false },
        { playName: "SLOT DRIVE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "SMASH", isNewIn26: false },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Normal Y Off",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, playType: "Quick Pass" },
        { playName: "COUNTER Y", isNewIn26: false },
        { playName: "DBL DIG", isNewIn26: false, playType: "Medium Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "JET TOUCH PASS", isNewIn26: false },
        { playName: "PA CROSS", isNewIn26: false, playType: "Play Action" },
        { playName: "PA DEEP CROSS", isNewIn26: false, playType: "Play Action" },
        { playName: "PA JET SWEEP", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SLOT POST", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO READ FL SCREEN", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, playType: "RPO" },
        { playName: "Y CROSS", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Normal Y Off Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CURL COMBO", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA Y CROSS", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO GLANCE SLANT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO PEEK POST", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO SPLIT ALERT BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "SLOT HOOKS", isNewIn26: false },
        { playName: "WR UNDER", isNewIn26: false },
        { playName: "X DAGGER", isNewIn26: false },
      ],
    },
    {
      formation: "Gun Spread",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, playType: "Quick Pass" },
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CROSS Z DIG", isNewIn26: false, playType: "Medium Pass" },
        { playName: "CURL FLATS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB COUNTER", isNewIn26: false },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MESH POST", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MESH SPOT", isNewIn26: false, playType: "Quick Pass" },
        { playName: "PA COMEBACKS", isNewIn26: false, playType: "Play Action" },
        { playName: "WR SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "Y CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "Y STICK", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Spread Y-Slot",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "CURL WHEEL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "H SHALLOW CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "HB DRAW", isNewIn26: false },
        { playName: "HITCH SEAM", isNewIn26: false, playType: "Quick Pass" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MESH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MTN H OPTION", isNewIn26: false, playType: "Option" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO PEEK SLANT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ SCREEN", isNewIn26: false, playType: "RPO" },
        { playName: "SMASH", isNewIn26: false },
        { playName: "Y CROSS", isNewIn26: false, playType: "Medium Pass" },
        { playName: "Y STICK", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Trips",
      formationType: "Gun",
      plays: [
        { playName: "45 QUICK BASE", isNewIn26: false, playType: "Quick Pass" },
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DEEP FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "FADE STOPS", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB MID DRAW", isNewIn26: false },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "PA DRIVE", isNewIn26: false, playType: "Play Action" },
        { playName: "PA MIDDLE", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO ALERT SHOCK", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "SAIL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "SLOT DRIVE", isNewIn26: false, playType: "Medium Pass" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Gun Trips HB Wk",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "DEEP FLOOD", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB ANGLE SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "HB SLIP SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MESH", isNewIn26: false, playType: "Medium Pass" },
        { playName: "MESH WHEEL", isNewIn26: false, playType: "Medium Pass" },
        { playName: "OUTSIDE ZONE", isNewIn26: false, playType: "Outside Run" },
        { playName: "READ OPTION", isNewIn26: false, playType: "Option" },
        { playName: "RPO ALERT BUBBLE", isNewIn26: false, playType: "RPO" },
        { playName: "SCISSORS", isNewIn26: false },
        { playName: "SHOCK H OPTION", isNewIn26: false, playType: "Option" },
        { playName: "TRIPS CROSS", isNewIn26: false, playType: "Medium Pass" },
      ],
    },
    {
      formation: "Gun Wing Trips",
      formationType: "Gun",
      plays: [
        { playName: "ALL GO", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HB CROSS SCREEN", isNewIn26: false, playType: "Screen" },
        { playName: "INSIDE ZONE", isNewIn26: false, playType: "Inside Run" },
        { playName: "MTN SPLIT ZONE", isNewIn26: false },
        { playName: "PA FLOOD", isNewIn26: false, playType: "Play Action" },
        { playName: "PA READ", isNewIn26: false, playType: "Play Action" },
        { playName: "RPO ALERT OUT", isNewIn26: false, playType: "RPO" },
        { playName: "RPO BUBBLE Y POP", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ SNAG", isNewIn26: false, playType: "RPO" },
        { playName: "RPO READ Y FLAT", isNewIn26: true, playType: "RPO" },
        { playName: "STICK", isNewIn26: false, playType: "Quick Pass" },
        { playName: "STICK N NOD", isNewIn26: false, playType: "Quick Pass" },
      ],
    },
    {
      formation: "Goal Line Normal",
      formationType: "Goal Line",
      plays: [
        { playName: "FB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB COUNTER WK", isNewIn26: false },
        { playName: "HB DIVE", isNewIn26: false, playType: "Inside Run" },
        { playName: "HB SPLIT O", isNewIn26: false },
        { playName: "HB STING", isNewIn26: false },
        { playName: "PA POWER O", isNewIn26: false, playType: "Play Action" },
        { playName: "PA SPOT", isNewIn26: false, playType: "Play Action" },
        { playName: "PA WAGGLE", isNewIn26: false, playType: "Play Action" },
        { playName: "POWER O", isNewIn26: false, playType: "Inside Run" },
        { playName: "QB SNEAK", isNewIn26: false, playType: "QB Run" },
        { playName: "STRONG TOSS", isNewIn26: false, playType: "Outside Run" },
      ],
    },
    {
      formation: "Hail Mary Hail Mary",
      formationType: "Hail Mary",
      plays: [
        { playName: "GOAL POST", isNewIn26: false, playType: "Deep Pass" },
        { playName: "HAIL MARY", isNewIn26: false },
        { playName: "SHOT SAVE CLOCK", isNewIn26: false },
      ],
    },
  ],
};
