-- Clear existing data
TRUNCATE TABLE team_offensive_playbooks CASCADE;
TRUNCATE TABLE team_defensive_schemes CASCADE;

-- ============================================
-- OFFENSIVE PLAYBOOKS
-- ============================================

INSERT INTO team_offensive_playbooks (team_name, playbook_name, scheme_style) VALUES
('Air Force', 'Air Force', 'Option'),
('Akron', 'Akron', 'Spread'),
('Alabama', 'Alabama', 'Multiple'),
('Appalachian State', 'Appalachian State', 'Multiple'),
('Arizona', 'Arizona', 'Multiple'),
('Arizona State', 'Arizona State', 'Multiple'),
('Arkansas', 'Arkansas', 'Multiple'),
('Arkansas State', 'Arkansas State', 'Power Spread'),
('Army', 'Army', 'Option'),
('Auburn', 'Auburn', 'Spread'),
('Ball State', 'Ball State', 'Spread'),
('Baylor', 'Baylor', 'Air Raid'),
('Boise State', 'Boise State', 'Pro Style'),
('Boston College', 'Boston College', 'Multiple'),
('Bowling Green', 'Bowling Green', 'Multiple'),
('Buffalo', 'Buffalo', 'Power Spread'),
('BYU', 'BYU', 'Power Spread'),
('California', 'California', 'Multiple'),
('Central Michigan', 'Central Michigan', 'Spread Option'),
('Charlotte', 'Charlotte', 'Spread'),
('Cincinnati', 'Cincinnati', 'Pistol'),
('Clemson', 'Clemson', 'Air Raid'),
('Coastal Carolina', 'Coastal Carolina', 'Power Spread'),
('Colorado', 'Colorado', 'Spread'),
('Colorado State', 'Colorado State', 'Air Raid'),
('Delaware', 'Delaware', 'Spread'),
('Duke', 'Duke', 'Veer & Shoot'),
('East Carolina', 'East Carolina', 'Veer & Shoot'),
('Eastern Michigan', 'Eastern Michigan', 'Spread'),
('Florida', 'Florida', 'Power Spread'),
('Florida Atlantic', 'Florida Atlantic', 'Air Raid'),
('Florida International', 'Florida International', 'Power Spread'),
('Florida State', 'Florida State', 'Spread'),
('Fresno State', 'Fresno State', 'Spread'),
('Georgia', 'Georgia', 'Multiple'),
('Georgia Southern', 'Georgia Southern', 'Spread'),
('Georgia State', 'Georgia State', 'Multiple'),
('Georgia Tech', 'Georgia Tech', 'Power Spread'),
('Hawaii', 'Hawaii', 'Run & Shoot'),
('Houston', 'Houston', 'Spread'),
('Illinois', 'Illinois', 'Multiple'),
('Indiana', 'Indiana', 'Spread'),
('Iowa', 'Iowa', 'Pro Style'),
('Iowa State', 'Iowa State', 'Power Spread'),
('Jacksonville State', 'Jacksonville State', 'Spread'),
('James Madison', 'James Madison', 'Spread'),
('Kansas', 'Kansas', 'Spread'),
('Kansas State', 'Kansas State', 'Multiple O'),
('Kennesaw State', 'Kennesaw State', 'Veer & Shoot'),
('Kent State', 'Kent State', 'Spread'),
('Kentucky', 'Kentucky', 'Pro Style'),
('Liberty', 'Liberty', 'Spread Option'),
('Louisiana', 'Louisiana', 'Spread'),
('Louisiana Tech', 'Louisiana Tech', 'Air Raid'),
('Louisville', 'Louisville', 'Multiple'),
('LSU', 'LSU', 'Power Spread'),
('Marshall', 'Marshall', 'Spread'),
('Maryland', 'Maryland', 'Spread'),
('Memphis', 'Memphis', 'Spread'),
('Miami', 'Miami', 'Spread'),
('Miami (OH)', 'Miami University', 'Air Raid'),
('Michigan', 'Michigan', 'Multiple'),
('Michigan State', 'Michigan State', 'Pro Style'),
('Middle Tennessee', 'Middle Tennessee St', 'Air Raid'),
('Minnesota', 'Minnesota', 'Multiple'),
('Mississippi State', 'Mississippi State', 'Veer & Shoot'),
('Missouri', 'Missouri', 'Pistol'),
('Missouri State', 'Missouri State', 'Power Spread'),
('Navy', 'Navy', 'Option'),
('NC State', 'NC State', 'Power Spread'),
('Nebraska', 'Nebraska', 'Multiple'),
('Nevada', 'Nevada', 'Spread'),
('New Mexico', 'New Mexico', 'Spread'),
('New Mexico State', 'New Mexico State', 'Spread'),
('North Carolina', 'North Carolina', 'Multiple'),
('North Texas', 'North Texas', 'Air Raid'),
('Northern Illinois', 'Northern Illinois', 'Multiple'),
('Northwestern', 'Northwestern', 'Spread'),
('Notre Dame', 'Notre Dame', 'Power Spread'),
('Ohio', 'Ohio', 'Pistol'),
('Ohio State', 'Ohio State', 'Spread'),
('Oklahoma', 'Oklahoma', 'Air Raid'),
('Oklahoma State', 'Oklahoma State', 'Power Spread'),
('Old Dominion', 'Old Dominion', 'Veer & Shoot'),
('Ole Miss', 'Ole Miss', 'Veer & Shoot'),
('Oregon', 'Oregon', 'Spread'),
('Oregon State', 'Oregon State', 'Power Spread'),
('Penn State', 'Penn State', 'Power Spread'),
('Pittsburgh', 'Pittsburgh', 'Spread'),
('Purdue', 'Purdue', 'Air Raid'),
('Rice', 'Rice', 'Spread Option'),
('Rutgers', 'Rutgers', 'Spread'),
('Sam Houston State', 'Sam Houston State', 'Air Raid'),
('San Diego State', 'San Diego State', 'Veer & Shoot'),
('San Jose State', 'San Jose State', 'Run & Shoot'),
('SMU', 'SMU', 'Spread'),
('South Alabama', 'South Alabama', 'Spread'),
('South Carolina', 'South Carolina', 'Power Spread'),
('Southern Miss', 'Southern Miss', 'Veer & Shoot'),
('Stanford', 'Stanford', 'Power Spread'),
('Syracuse', 'Syracuse', 'Spread'),
('TCU', 'TCU', 'Air Raid'),
('Temple', 'Temple', 'Spread'),
('Tennessee', 'Tennessee', 'Veer & Shoot'),
('Texas', 'Texas', 'Spread'),
('Texas A&M', 'Texas A&M', 'Power Spread'),
('Texas State', 'Texas State', 'Veer & Shoot'),
('Texas Tech', 'Texas Tech', 'Veer & Shoot'),
('Toledo', 'Toledo', 'Spread'),
('Troy', 'Troy', 'Power Spread'),
('Tulane', 'Tulane', 'Power Spread'),
('Tulsa', 'Tulsa', 'Spread'),
('UAB', 'UAB', 'Spread'),
('UCF', 'UCF', 'Spread'),
('UCLA', 'UCLA', 'Spread'),
('UConn', 'UConn', 'Spread'),
('UL Monroe', 'UL Monroe', 'Spread'),
('UMass', 'Massachusetts', 'Spread'),
('UNLV', 'UNLV', 'Spread'),
('USC', 'USC', 'Air Raid'),
('USF', 'South Florida', 'Veer & Shoot'),
('Utah', 'Utah', 'Spread'),
('Utah State', 'Utah State', 'Run & Shoot'),
('UTEP', 'UTEP', 'Air Raid'),
('UTSA', 'UTSA', 'Power Spread'),
('Vanderbilt', 'Vanderbilt', 'Pistol'),
('Virginia', 'Virginia', 'Spread'),
('Virginia Tech', 'Virginia Tech', 'Spread'),
('Wake Forest', 'Wake Forest', 'Air Raid'),
('Washington', 'Washington', 'Pro Style'),
('Washington State', 'Washington State', 'Power Spread'),
('West Virginia', 'West Virginia', 'Spread'),
('Western Kentucky', 'Western Kentucky', 'Air Raid'),
('Western Michigan', 'Western Michigan', 'Spread'),
('Wisconsin', 'Wisconsin', 'Multiple'),
('Wyoming', 'Wyoming', 'Multiple');

-- ============================================
-- DEFENSIVE SCHEMES
-- ============================================

INSERT INTO team_defensive_schemes (team_name, defensive_scheme) VALUES
('Air Force', '3-4 Multiple'),
('Akron', '4-2-5'),
('Alabama', '4-2-5'),
('Appalachian State', '3-3-5 Tite'),
('Arizona', '4-2-5'),
('Arizona State', '4-2-5'),
('Arkansas', '4-2-5'),
('Arkansas State', '4-2-5'),
('Army', '3-3-5 Tite'),
('Auburn', '3-3-5 Tite'),
('Ball State', '3-4'),
('Baylor', '3-3-5 Tite'),
('Boise State', '4-2-5'),
('Boston College', '4-2-5'),
('Bowling Green', '4-2-5'),
('Buffalo', '4-3'),
('BYU', '4-3 Multiple'),
('California', '4-2-5'),
('Central Michigan', '3-4'),
('Charlotte', '4-2-5'),
('Cincinnati', '3-3-5'),
('Clemson', '4-2-5'),
('Coastal Carolina', '4-2-5'),
('Colorado', '4-2-5'),
('Colorado State', '4-2-5'),
('Delaware', '3-3-5'),
('Duke', '4-3 Multiple'),
('East Carolina', '3-4'),
('Eastern Michigan', '4-2-5'),
('Florida', '3-3-5 Tite'),
('Florida Atlantic', '3-3-5 Tite'),
('Florida International', '4-2-5'),
('Florida State', '3-3-5 Tite'),
('Fresno State', '4-2-5'),
('Georgia', '3-3-5 Tite'),
('Georgia Southern', '4-2-5'),
('Georgia State', '3-4'),
('Georgia Tech', '4-2-5'),
('Hawaii', '4-2-5'),
('Houston', '3-3-5 Tite'),
('Illinois', '3-4 Multiple'),
('Indiana', '3-4 Multiple'),
('Iowa', '4-2-5'),
('Iowa State', '3-3-5'),
('Jacksonville State', '4-2-5'),
('James Madison', '4-2-5'),
('Kansas', '4-2-5'),
('Kansas State', '3-3-5'),
('Kennesaw State', 'Multiple'),
('Kent State', '4-3'),
('Kentucky', '3-4'),
('Liberty', '4-2-5'),
('Louisiana', '3-4'),
('Louisiana Tech', '4-3'),
('Louisville', '4-2-5'),
('LSU', '4-2-5'),
('Marshall', '3-3-5'),
('Maryland', '3-4'),
('Memphis', '4-3 Multiple'),
('Miami', '4-3 Multiple'),
('Miami (OH)', '3-4'),
('Michigan', '3-4 Multiple'),
('Michigan State', '4-2-5'),
('Middle Tennessee', '3-4'),
('Minnesota', '4-3'),
('Mississippi State', '3-3-5'),
('Missouri', '4-2-5'),
('Missouri State', '4-2-5'),
('Navy', '3-4 Multiple'),
('NC State', '3-4'),
('Nebraska', '3-3-5'),
('Nevada', '4-3 Multiple'),
('New Mexico', '4-2-5'),
('New Mexico State', '3-3-5'),
('North Carolina', '3-4 Multiple'),
('North Texas', '4-3'),
('Northern Illinois', '4-2-5'),
('Northwestern', '4-3'),
('Notre Dame', 'Multiple'),
('Ohio', '4-2-5'),
('Ohio State', '4-2-5'),
('Oklahoma', '4-2-5'),
('Oklahoma State', '3-4 Multiple'),
('Old Dominion', '3-2-6'),
('Ole Miss', '4-2-5'),
('Oregon', '3-4'),
('Oregon State', '4-2-5'),
('Penn State', '4-2-5'),
('Pittsburgh', '4-3'),
('Purdue', '3-2-6'),
('Rice', '4-2-5'),
('Rutgers', '4-3'),
('Sam Houston State', '3-3-5'),
('San Diego State', '4-2-5'),
('San Jose State', '4-2-5'),
('SMU', '4-2-5'),
('South Alabama', '4-2-5'),
('South Carolina', '4-2-5'),
('Southern Miss', '4-2-5'),
('Stanford', '3-4'),
('Syracuse', '3-3-5 Tite'),
('TCU', '3-3-5'),
('Temple', '3-4'),
('Tennessee', '4-2-5'),
('Texas', 'Multiple'),
('Texas A&M', '4-2-5'),
('Texas State', '4-2-5'),
('Texas Tech', '3-3-5 Tite'),
('Toledo', '4-2-5'),
('Troy', '3-3-5 Tite'),
('Tulane', '4-2-5'),
('Tulsa', '4-3'),
('UAB', '4-2-5'),
('UCF', '4-3 Multiple'),
('UCLA', '4-3 Multiple'),
('UConn', '3-3-5'),
('UL Monroe', '4-2-5'),
('UMass', 'Multiple'),
('UNLV', 'Multiple'),
('USC', '3-4 Multiple'),
('USF', '3-3-5'),
('Utah', '4-2-5'),
('Utah State', '3-4'),
('UTEP', '3-3-5'),
('UTSA', '3-4'),
('Vanderbilt', '4-2-5'),
('Virginia', '4-2-5'),
('Virginia Tech', '4-2-5'),
('Wake Forest', '4-2-5'),
('Washington', '4-2-5'),
('Washington State', '4-3'),
('West Virginia', '3-3-5'),
('Western Kentucky', '3-4'),
('Western Michigan', '4-2-5'),
('Wisconsin', '4-2-5'),
('Wyoming', '4-2-5');
