import type { ValidatedImportPlay } from "@/lib/importCsv";

export const IMPORT_SAMPLE_PLAYS: ValidatedImportPlay[] = [
  {
    drive_number: 1,
    play_number: 1,
    quarter: 1,
    down: 1,
    distance: 10,
    yard_line: "OWN 25",
    formation: "Gun Trips Open",
    play_name: "PA BOOT OVER",
    result: "GAIN",
    result_db: "GAIN",
    yards: 7,
  },
  {
    drive_number: 1,
    play_number: 2,
    quarter: 1,
    down: 2,
    distance: 3,
    yard_line: "OWN 32",
    formation: "Gun Empty Base Flex",
    play_name: "Y SHALLOW CROSS",
    result: "FIRST DOWN",
    result_db: "FIRST_DOWN",
    yards: 12,
  },
  {
    drive_number: 1,
    play_number: 3,
    quarter: 1,
    down: 1,
    distance: 10,
    yard_line: "OWN 44",
    formation: "Pistol Wing Slot",
    play_name: "INSIDE ZONE",
    result: "GAIN",
    result_db: "GAIN",
    yards: 4,
  },
  {
    drive_number: 1,
    play_number: 4,
    quarter: 1,
    down: 2,
    distance: 6,
    yard_line: "OWN 48",
    formation: "Gun Trips Open",
    play_name: "MESH CONCEPT",
    result: "INCOMPLETE",
    result_db: "INCOMPLETE",
    yards: 0,
  },
  {
    drive_number: 1,
    play_number: 5,
    quarter: 1,
    down: 3,
    distance: 6,
    yard_line: "OWN 48",
    formation: "Gun Empty Trips Y Off",
    play_name: "LEVELS SEAM",
    result: "GAIN",
    result_db: "GAIN",
    yards: 3,
  },
  {
    drive_number: 2,
    play_number: 6,
    quarter: 1,
    down: 1,
    distance: 10,
    yard_line: "OWN 15",
    formation: "Gun Doubles",
    play_name: "READ OPTION WK",
    result: "GAIN",
    result_db: "GAIN",
    yards: 8,
  },
  {
    drive_number: 2,
    play_number: 7,
    quarter: 1,
    down: 2,
    distance: 2,
    yard_line: "OWN 23",
    formation: "Pistol Wing Slot",
    play_name: "POWER",
    result: "FIRST DOWN",
    result_db: "FIRST_DOWN",
    yards: 5,
  },
  {
    drive_number: 2,
    play_number: 8,
    quarter: 1,
    down: 1,
    distance: 10,
    yard_line: "OWN 28",
    formation: "Gun Trips Open",
    play_name: "FOUR VERTICALS",
    result: "TOUCHDOWN",
    result_db: "TOUCHDOWN",
    yards: 72,
  },
  {
    drive_number: 3,
    play_number: 9,
    quarter: 2,
    down: 1,
    distance: 10,
    yard_line: "OWN 30",
    formation: "Gun Empty Base Flex",
    play_name: "SLANT FLAT",
    result: "SACK",
    result_db: "SACK",
    yards: -7,
  },
  {
    drive_number: 3,
    play_number: 10,
    quarter: 2,
    down: 2,
    distance: 17,
    yard_line: "OWN 23",
    formation: "Gun Trips Open",
    play_name: "Y SAIL",
    result: "GAIN",
    result_db: "GAIN",
    yards: 11,
  },
  {
    drive_number: 3,
    play_number: 11,
    quarter: 2,
    down: 3,
    distance: 6,
    yard_line: "OWN 34",
    formation: "Gun Empty Trips Y Off",
    play_name: "LEVELS SEAM",
    result: "TURNOVER",
    result_db: "TURNOVER",
    yards: 0,
  },
];
